### ISSUE TITLE
Unable to close Apply popup window on small screens

### ISSUE THREAD

**Issue by DaveGarlock** [bullhorn/career-portal#101]
A user of our site that utilizes the career portal found the following issue:

"I wanted to let you know about a design issue that is preventing me from closing a window or moving off the application pop up page.

When I click apply, this pop up on the attached image comes up.  However, there's no way to navigate from this page now.  The submit button doesn't appear on scroll, I can't tab down to choices beyond the input fields, and can't complete the application even after uploading a resume. 

Perhaps on a large screen this would work.  I'm on a MacBook 13.5".

The only way off the page is to close it."

We have duplicated the issue - if your screen size isn't tall enough to show the Cancel button there's no way to close the Apply popup in the career portal. This could be fixed by allowing scrolling within the popup (preferred, so you would also get to the Send button) or making it so if you click outside the popup it closes.

**Comment by bulbajackel** [comment]
Hey Dave, 

This was actually changed in #70 to apply a fix for smaller resolution screens along with a an additional fix recently within #94.  These changes are tentatively going to be applied within the next release of the portal but I suggest ensuring your portal is v1.6.0 for the #70 fix.   

Please let me know if you have any more questions.

**Comment by DaveGarlock** [comment]
We do have v1.60 installed to the best of my knowledge, but still have the
issue - the career portal is here:
https://www.scionstaffing.com/jobportal/#/jobs

**Comment by bulbajackel** [comment]
Hey Dave,

Version 2.0 was released recently that does address this issue.   I am not sure if you applied your own fix, but if you update the portal, you should see this fix from #70 

Just wanted to provide an update. Please let me know if you have any questions

**Comment by DaveGarlock** [comment]
Thanks for the update - I appreciate it. We probably won't be able to get
around to updating the fix for a week or so, but when we do I'll let you
know if it fixes the problem for me. Cheers,

Dave Garlock

**Comment by DaveGarlock** [comment]
Version 2.0 did fix this issue - thanks.
