### ISSUE TITLE
Cross Domain Issue

### ISSUE THREAD

**Issue by yamimaio** [bullhorn/career-portal#106]
Hi!

I'm trying to use the career portal out of the box as described here: https://github.com/bullhorn/career-portal/wiki/Downloading-and-Configuring. However, my dashboard, jobs (and everything) is blank due to a cross domain issue.

I'm getting the following console error:

_XMLHttpRequest cannot load https://public-restsl5.bullhornstaffing.com/rest-services/1BH7K4/search/Job…showTotalMatched=true&query=(isOpen:1)&fields=id&sort=id&count=500&start=0. No 'Access-Control-Allow-Origin' header is present on the requested resource.  Origin 'http://numan.com.ar' is therefore not allowed access. The response had HTTP status code 404._

To replicate this, I did exactly everything indicated here:  https://github.com/bullhorn/career-portal/wiki/Downloading-and-Configuring and uploaded it to my server here http://numan.com.ar/careerportal

I asked for support vía email but had no answer so far. Could my site be authorized? Is there anything I can do on my side to get this working?

Thanks in advance!

**Comment by bulbajackel** [comment]
Hello,
I have taken a look at your career portal at http://numan.com.ar/careerportal and have noticed that in your app.json file, the swimlane says "SL5".  The swimlane just should be the numeric value.  The app,json file is located here http://numan.com.ar/careerportal/app.json

Please let me know if you have any more questions.

**Comment by yamimaio** [comment]
Thanks! That solved the issue.
