### ISSUE TITLE
No Menu content is displayed

### ISSUE THREAD

**Issue by yamimaio** [bullhorn/career-portal#108]
Hi!
Everything seems to be OK (search works ok, can add jobs, clients, contacts, etc) from the search input. However, if I display the Menu, the menu is always empty. I originally thought this was normal until I saw a video tutorial where the menu provided useful information, such as the job list or candidate list that I can not access otherwise.

This is what I'm normally getting when I click on Menu

![nomenu](https://cloud.githubusercontent.com/assets/8672103/21485321/3cf89786-cb80-11e6-851f-11bf991f964a.png)

Console log displays this when clicking on menu the first time:

_**MainFrame.jsp:872 Uncaught ReferenceError: WarningsDialog is not defined
    at checkCookie_popUps (MainFrame.jsp:872)
checkCookie_popUps @ MainFrame.jsp:872**_

Any ideas? I used the out of the box installation.
User experience would definitely be better if the menu really displayed what it should!

You can check out the site here: www.numan.com.ar/careerportal

Thanks in advance

**Comment by bulbajackel** [comment]
Hello,

looks like you are logging into the API user.  The menu options are not available on API users as they are placeholder users for communicating with your database.  If you would like to get logged in to Bullhorn into the proper account, I suggest clicking the username "NumanAPI" in the top right and clicking log out and then logging into a user with the correct credentials.  

If you do need any further assistance with the ATS itself, please contact our support team following the steps in this article http://bullhorn.force.com/pkb/articles/Documentation/Contacting-Bullhorn-Support

Please let me know if you have any further questions

**Comment by yamimaio** [comment]
Yes, I'm so so sorry! I just realized I mixed the career portal with the Bullhorn Center. I came to edit my question and you had already answered. So sorry!! Thanks.
