### ISSUE TITLE
Still cannot get Job ID to Display

### ISSUE THREAD

**Issue by rmglass** [bullhorn/career-portal#109]
After making modifications described in Issue #83 I am still not seeing Job ID displayed. 

I created the new build by following the instructions provided here:
https://github.com/bullhorn/career-portal/blob/master/README.md#building

Here are the steps I followed:

1.  Install Git & node.js (Git Bash installed on Windows 10 desktop)
2.  In the Git Bash Console I issued the following sequence of commands:
     a.  git clone https://github.com/bullhorn/career-portal.git
     b.  cd career-portal
     c.  npm install -g bower
     d.  npm install -g gulp
     e.  npm install
     f.  bower install
3.  Edit the src/app/list/list.html and add the following line to <span class="card-title-category">:
    <span>{{::job.id}}</span>
4.  Edit the src/app/detail/detail.html and add the following line to <span class="card-title-category">:
    <span>{{::detail.job.id}}</span>
5. Final command:
    a.    gulp --corpToken='[our corp token]' --sl='[our swimlane]' --companyName='[our company name]'
6. Upload the dist directory to the root directory on the host (GoDaddy) and rename directory to careerportal.

FINAL RESULT:

The job listing displays fine, but still does not show the job ID. 

Here is what I added to list.html in the section span class="card-title-category":

        <span>{{::job.id}}</span>

Here is what I added to detail.html in the section span class="card-title-category":

        <span>{{::detail.job.id}}</span>

Here is the full listing of updated each file:

[list.docx](https://github.com/bullhorn/career-portal/files/676754/list.docx)
[detail.docx](https://github.com/bullhorn/career-portal/files/676753/detail.docx)

After making these two simple changes, the job listing displays fine but I still do not see the job id.

**Comment by krsween** [comment]
Hey, @rmglass —

I went through the exact same steps that you've listed above (I even copied and pasted your code), but mine worked, which tells me that this is probably like when you hear a rattle in your car but once you take it to the mechanic the rattling stops, haha. I've uploaded that version to my own site [here](http://krsween.com/_oscp) for you to see working (a little ugly, but working). 

I've also forked this repo onto my private account and uploaded the code changes I've used [here](https://github.com/krsween/career-portal). Could you try cloning that version locally, installing all the dependencies (step 2's b-f), then building and deploying that? Once you've done that, if you have a link to your build send it over and I can take a further look if it isn't working. 

Thanks!

**Comment by rmglass** [comment]
Hey Kameron,

Thanks for your quick response. I downloaded your version. It looks like everything is working fine now. I need to do a small tweak to the details page, but other than that I am in business:
http://wimmersolutions.com/careers/
Thanks again, for your help.
