### ISSUE TITLE
Apply now - email validation issues

### ISSUE THREAD

**Issue by cmec123** [bullhorn/career-portal#110]
OSCP allow users to enter the following in the email field and no error is returned:
X@X 

You only need to enter a character before and after the @ symbol.
It does not require a user to enter a "." or a domain extension. 

This is basic validation for most forms when it comes

**Comment by krsween** [comment]
Hey, @cmec123 —

Thanks for reaching out. We use an [HTML `input`](http://www.w3schools.com/html/html_form_input_types.asp) with a type of `email` in our app to provide the rules for our [angular form](https://docs.angularjs.org/api/ng/input/input%5Bemail%5D) to determine email validity. 

I extricated that part of our app [here](https://jsfiddle.net/krsween/k56qhz8r/) for you to see how Angular is listening to that HTML input. We didn't add any additional rules, but it wouldn't be too difficult to implement. 

Angular allows you to add [custom validators](https://docs.angularjs.org/guide/forms) to enforce custom rules. If you fork our repo and begin building this out and need some help, feel free to @ me to provide some additional help. Custom regex for email validation can be a complicated art!
