### ISSUE TITLE
Filter Counts Mismatch Job Results

### ISSUE THREAD

**Issue by therealjeffix** [bullhorn/career-portal#111]
User-facing discrepancy between the results count in the filters compared with the actual resulting jobs. There is a closed job somehow making it in to the filter count subtotal.

## Current behavior

The filter counts display higher job counts than the actual results pane. 

For example, when selecting state = "DE", the filter count shows "2", but only 1 job result is returned. The filter includes a job in the "manufacturing" category that is currently closed (and as of 3 hours ago not published/approved.) 

Checking in the Bullhorn account with filters for Open, Published/Approved jobs in DE, likewise only 1 job result is returned.

## Expected behavior

The filter counts on the left to match the number of job results on the right. I want to identify what the criteria difference is creating the mismatching counts.

## Steps to replicate behavior

1. Open: http://butlerjobs.digitalpmg.com/careerportal/#/jobs
2. Select filter "DE"

## Screenshots

__Current__

<img width="597" alt="screen shot 2017-01-12 at 12 18 53 pm" src="https://cloud.githubusercontent.com/assets/14004105/21907140/2f748ab6-d8c3-11e6-89df-99c375671e02.png">

__Expected__

(Open/Published Approved job in DE w/in Bullhorn CRM)
<img width="574" alt="screen shot 2017-01-12 at 12 22 07 pm" src="https://cloud.githubusercontent.com/assets/14004105/21907147/3b550496-d8c3-11e6-8f36-959ef39189c0.png">

(Closed/Not Published job in DE w/in Bullhorn CRM)
<img width="1172" alt="screen shot 2017-01-12 at 12 29 05 pm" src="https://cloud.githubusercontent.com/assets/14004105/21907157/43b489e0-d8c3-11e6-8fed-f907932a04c0.png">

**Comment by kbushkoBH** [comment]
Hi therealjeffix, 

I think I see the problem here, and I would advise contacting Bullhorn support to request assistance confirming the correct swimlane and corpToken values for your app.json file: 
http://bullhorn.force.com/pkb/articles/Documentation/Contacting-Bullhorn-Support

Let us know if they are not able to help resolve this issue by confirming the correct values (you may also see issue 112 resolved simultaneously).

**Comment by therealjeffix** [comment]
I'll try that, thanks. I'll report back with the result.

**Comment by therealjeffix** [comment]
Confirmed, the swim lane changed. I updated the app.json file and it is working properly.

Do you know why the swim lane would change?

**Comment by kbushkoBH** [comment]
Great! Glad to hear everything is working now.

Swimlane changes for existing customers will usually only take place as part of scheduled service improvements. We send information about this process in advance of any change, including a short list of action items, via the following document: 
http://bullhorn.force.com/pkb/articles/Documentation/Database-Hardware-Update
