### ISSUE TITLE
More post info to display

### ISSUE THREAD

**Issue by nnadeemm** [bullhorn/career-portal#113]
I want to few information relating my job post, is that possible here ? 
1.  The Job ID #  - would come from Bullhorn 
2.  Job Title -- Is already coming over 
3.  Employment Type would be Direct Hire, Contract or Contract to Hire 
4.  Location of the job

-

Just like 
http://cls6.bullhornstaffing.com/JobBoard/Standard/BHContent_JobDetail.cfm?privateLabelID=8840&jobPostingID=518
-

**Comment by nnadeemm** [comment]
How can i get email notification when someone applies for the job ?

**Comment by bulbajackel** [comment]
Hello nnadeemm,

For the job ID, there are details on how to display the job ID within issue #83.  Here, there was great communication included about viewing the job ID on each job card. 

For the Employment type, the career portal displays this information already on each card as well on the right-hand side in the list view.  On the detail page, it can be found on the apply card above the apply button.

Location is displayed as well in the center of the job card.  On the detail page, this can be found below the title and category, right next to the employment type.

Bullhorn is also capable delivering email notifications for new applicants.  If you need assistance with utilizing this, I suggest reaching out to the Bullhorn Support team following the steps in [this article](http://bullhorn.force.com/pkb/articles/Documentation/Contacting-Bullhorn-Support).

Please let me know if you have any more questions!
