### ISSUE TITLE
Job titles getting truncated on our website job postings

### ISSUE THREAD

**Issue by brentkannady** [bullhorn/career-portal#114]
Our bullhorn titles for our published jobs are truncating both on the main job title page:
http://www.synigent.com/open-jobs/

AND on the detail screen:

http://www.synigent.com/open-jobs/
Sr. Software Engineer - Bac...

Any help or code samples to point us to to give to our web developers would be appreciated.  I am sure we are not the first to have that problem.

brentk@synigent.com
804-217-6862

## Current behavior
truncating
-

## Expected behavior
wrapping OR decreasing the font to accomodate the screen
-

## Steps to replicate behavior
goto:
http://www.synigent.com/open-jobs/
see the truncation on the list of jobs screen and the detail screen
1.

## Screenshots

__Current__

__Expected__

**Comment by bulbajackel** [comment]
Hi Brent, 

To achieve this, there are several ways to adjust the font size dynamically so the full job title shows.  I do see that on your site, content is being viewed within and Iframe so this would mean that you have a smaller viewport.    For this situation two solutions immediately come to mind. 

First, manipulating the CSS comes to mind as you can make the font utilize VW units which represents viewport width.   I found a couple of few posts on the topic [here](http://stackoverflow.com/questions/14431411/pure-css-to-make-font-size-responsive-based-on-dynamic-amount-of-characters)

If you would like to go for even a more dynamic approach, you are also able to implement a couple of JavaScript libraries that may work for your situation. One example of which that I have found is [TextFit](https://github.com/nbrunt/TextFit).

Both solutions are for resizing the text so it fits within the given space as that personally is the best for appearance as well.  There are also options for CSS word wrap as well.  

Please let me know if you have any questions.
