### ISSUE TITLE
set default published contact recruiter

### ISSUE THREAD

**Issue by cmec** [bullhorn/career-portal#115]
This is not an issue. It's a feature request. I manage all my recruiter and prefer the default published contact recruiter be set to my user profile in Bullhorn. More specifically, don't allow recruiters to touch this drop down menu when in the published job page.

**Comment by charlesabarnes** [comment]
As this is a potential feature for the Bullhorn core platform, I have submitted this as feedback to them.  For now I am closing this as this isn't a feature for the career portal frontend
