### ISSUE TITLE
sign up for job alerts

### ISSUE THREAD

**Issue by cmec** [bullhorn/career-portal#117]
Would love to allow candidates to select jobs categories they are interested and have automated emails sent with jobs fitting their criteria. Just like Bullhorn Reach did.

**Comment by RichardCore37** [comment]
Is there any scope for email alerts yet? I'm about to go live with our career portal.

**Comment by pbearne** [comment]
We have this as part of the [Matador Jobs WordPress Plugin](https://matadorjobs.com/) if it is a must-have feature.

**Comment by RichardCore37** [comment]
My site is currently on Business Catalyst, soon to be moving to Treepl. I take it there's no equivalent?

**Comment by charlesabarnes** [comment]
Would "push notifications" satisfy this request?  Email alerts may be further off, but we may be able to implement notifications that alerts users to jobs outside the browser on their desktop computer and their phone.
