### ISSUE TITLE
Key not found appearing when you click apply

### ISSUE THREAD

**Issue by ndrummy** [bullhorn/career-portal#118]
%%KEY_NOT_FOUND%% is appearing in the apply button action see attached.

## Current behavior

[http://www.lloydconnect.com.au/careerportal/#/jobs/8](url)

## Expected behavior
Should have text there with the correct title of the cell but its appearing as an error with %%KEY_NOT_FOUND%%

## Steps to replicate behavior

1. View the site: [http://www.lloydconnect.com.au/careerportal/#/jobs/8](url)

## Screenshots

__Current__

![issue](https://cloud.githubusercontent.com/assets/19941959/23011925/c0fe0c1c-f477-11e6-9fa0-ff2435548e9e.png)

__Expected__

**Comment by bulbajackel** [comment]
Hey Ndrummy,

I have taken a look into this and the JSON file that displays the text on the modal popup.  In the [modal.json file found here](http://www.lloydconnect.com.au/careerportal/res/en-US/modal.json), the value for the "successSubHeading" key has a line break before the ending quote.  If you remove the line break, the content should display appropriately. 

Feel free to let me know if you need any assistance with this.
