### ISSUE TITLE
eeoc "genderRaceEthnicity": true making the checkbox too wide in IE

### ISSUE THREAD

**Issue by semakieht** [bullhorn/career-portal#119]
INSERT SHORT DESCRIPTION EXPLAINING THE HIGH-LEVEL REASON FOR THE NEW ISSUE HERE.

## Current behavior
gender ethnicity checklist is too wide in IE so the labels don't show up.
but it is good in Chrome
-

## Expected behavior
To look good in IE as it is in Chrome
-

## Steps to replicate behavior

1. Navigate to http://jabhcp.jetaviation.com/careerportal/index.html#/jobs/2 
2. Press Apply

## Screenshots
![capture](https://cloud.githubusercontent.com/assets/25907919/23138569/ce249476-f76d-11e6-94f5-1b4f63a8f31b.JPG)

__Current__

__Expected__

**Comment by eberletj** [comment]
Corrected this problem by changing the width: value in the modal.scss file width: auto;

    display: flex;
                                    align-items: center;
                                    justify-content: flex-start;
                                    height: 36px;

                                    input[type="checkbox"] {
                                        margin-top: 0;
                                        flex-shrink: 0;
                                        width: auto;
                                        height: 36px;
                                    }
