### ISSUE TITLE
CV Help tooltip will not close 

### ISSUE THREAD

**Issue by kbushkoBH** [bullhorn/career-portal#120]
## Current behavior

- If a user opens the CV/resume help tooltip, the X at top right will not close, even after canceling out of the apply modal

## Expected behavior

- If a user opens the CV/resume help tooltip, the X at top right should close it

## Steps to replicate behavior

1. Open apply modal and click CV/resume help

## Screenshots

![pasted image at 2017_03_03 04_45 pm](https://cloud.githubusercontent.com/assets/18052144/23560273/7205d44e-ffff-11e6-9175-96742f3fe6e8.png)

**Comment by TIIUNDER** [comment]
The tooltip isn't opening anymore.

**Comment by bulbajackel** [comment]
Hey @TIIUNDER to keep track of the individual occurrences of problems such as this, can you open a new issue?  In that issue, can you include a link to your portal build?  I would like to take a look.
