### ISSUE TITLE
Fonts returning 404

### ISSUE THREAD

**Issue by azavarben** [bullhorn/career-portal#121]
The fonts are 404ing and the requests are going off to directories that dont exist.

## Current behavior

- I'm seeing requests to /fonts/roboto/Roboto-Regular.woff2 but there is no "roboto" folder in the "fonts" directory

## Expected behavior

- Shouldn't the requests go to /fonts/Roboto-Regular.woff2 or are we supposed to create these folders locally?

## Steps to replicate behavior

1. Download the latest release
2. unzip to a directory in windows
 3. create a new site in iis and point it to the directory. 
4. browse the site

## Screenshots

__Current__
![fonts]

__Expected__

[fonts]: https://s3.us-east-2.amazonaws.com/azavar-qps/bullhorn-fonts.png "fonts"

**Comment by bosston812** [comment]
I solved this problem with just adding another folder fonts/roboto to my root folder and it fixed all errors with fonts.
