### ISSUE TITLE
Rest Service Returning 500 Errors

### ISSUE THREAD

**Issue by azavarben** [bullhorn/career-portal#122]
The following urls which are requested when using the career portal are giving me 500 errors: 

- https://public-rest0.bullhornstaffing.com/rest-services/{corpToken}/query/JobBoardPost?where=(isOpen=true)&fields=id,title,publishedCategory(id,name),address(city,state),employmentType,dateLastPublished,publicDescription,isOpen,isPublic,isDeleted&count=20&orderBy=-dateLastPublished&start=0
- https://public-rest0.bullhornstaffing.com/rest-services/{corpToken}/search/JobOrder?showTotalMatched=true&query=(isOpen:1)&fields=id&sort=id&count=500&start=0
- https://public-rest0.bullhornstaffing.com/rest-services/{corpToken}/search/JobOrder?showTotalMatched=true&query=(isOpen:1)&fields=id&sort=id&count=500&start=0

## Current behavior

- No jobs are listed

## Expected behavior

- Jobs would be listed

## Steps to replicate behavior

1. Go to http://52.23.238.72:82/careerportal/#/jobs

**Comment by kbushkoBH** [comment]
Hi azavarben,

Bullhorn Support received your request for swimlane and token but it does not appear that they were notified that this was for a career portal setup. We completed the Bullhorn career portal settings for the system associated to this token for you and you should no longer see the 500 errors. Please reach out to support for additional optional settings you may wish to enable.

**Comment by azavarben** [comment]
Cool thanks!
