### ISSUE TITLE
Not collecting EEOC information when people apply for a job

### ISSUE THREAD

**Issue by GLenotre** [bullhorn/career-portal#123]
INSERT SHORT DESCRIPTION EXPLAINING THE HIGH-LEVEL REASON FOR THE NEW ISSUE HERE.

##Current 
Our career portal can only collect the first name, last name, email, mobile phone, and resume.

##Expected

We want to collect EEOC information when people apply.

-

## Steps to replicate behavior

1. Click on an employment link
2. Click apply

![screen shot 2017-03-30 at 10 59 19 am](https://cloud.githubusercontent.com/assets/11380138/24513906/1bb7c216-1538-11e7-8c0a-995c3883eada.png)

__Current__

__Expected__

**Comment by bulbajackel** [comment]
Hey GLenotre,

For the EEOC fields to appear, you will need to update the app.json file to reflect the following.
```
    "eeoc": {
        "genderRaceEthnicity": true,
        "veteran": true,
        "disability": true
    }
```
In the [file found]( http://www.abbtech.com/careerportal/app.json), I can see the values are set to set to false currently.

Please let me know if you have any more questions!

**Comment by GLenotre** [comment]
Thanks!
