### ISSUE TITLE
cPanel Root Directory.

### ISSUE THREAD

**Issue by blakemoser** [bullhorn/career-portal#127]
I can easily get the  career portal to work if I load the files into a directory of an active site. However if I load the files into the root directory of my hosting account I can not get it to work.
What can I do if I want to have my career portal be the only content on my domain?
## Current behavior

-

## Expected behavior

-

## Steps to replicate behavior

1.

## Screenshots

__Current__

__Expected__

**Comment by bulbajackel** [comment]
Hey Blake, 

For your Career Portal, you should be able to upload it directly into your /public_html/ or /www/ directory.

If you got a new domain or subdomain, you will want to make sure you are uploading it into the correct directory for your site's content.  It will be best to contact your web host's support as there are a large number of configurations with each being unique. Your webhost should be able to direct you to the right place to place the files to ensure it displays correctly on your domain.

Please let me know if you have any questions about this, or head over to our [wiki](https://github.com/bullhorn/career-portal/wiki) where you can find more information for uploading to your site host.  

Thanks
