### ISSUE TITLE
Jobs doesn't show

### ISSUE THREAD

**Issue by PuneetChawla123** [bullhorn/career-portal#128]
I have downloaded and configured the repo as described in here https://github.com/bullhorn/career-portal/wiki/Downloading-and-Configuring . But it doesn't display jobs.

Live URL - http://poolingmate.com/test/index.html#/jobs

Some errors are coming but these are not related to this.

![errors](https://cloud.githubusercontent.com/assets/9328745/24889025/44034b2c-1e85-11e7-9cce-134d237ef3d3.PNG)

This is the response

{
  "start" : 0,
  "count" : 0,
  "data" : [ ]
}

from this URL

https://public-rest31.bullhornstaffing.com/rest-services/2cozdd/query/JobBoardPost?where=(isOpen=true)&fields=id,title,publishedCategory(id,name),address(city,state),employmentType,dateLastPublished,publicDescription,isOpen,isPublic,isDeleted&count=20&orderBy=-dateLastPublished&start=0
-

**Comment by bulbajackel** [comment]
Hello,

To show jobs on your career portal, your portal will need to be published.  To publish your jobs, inside of Bullhorn, open the job, click select an action then click publish.  You will see a publishing screen where you are able to click a blue publish button so it appears on your portal.  You are able to find more information in [this article.](http://bullhorn.force.com/pkb/articles/Documentation/Publishing-a-Job-to-Job-Boards-Social-Media-and-your-Bullhorn-Career-Portal) 

Please let me know if you have any more questions
