### ISSUE TITLE
Editing the default "thank you" 

### ISSUE THREAD

**Issue by talent1** [bullhorn/career-portal#129]
INSERT SHORT DESCRIPTION EXPLAINING THE HIGH-LEVEL REASON FOR THE NEW ISSUE HERE.

## Current behavior
I just downloaded this plugin with the help of Bullhorn support. I asked how to change the default "thank you, you will be contacted shortly." 

They sent me the following: "Ok, so to update the thank you message you will want to go into the back end of your website, and go to the res\en-EU\modal.json file"

I found the file in my site, but when I edit and make changes it's not reflected on my website. 
-

## Expected behavior
Edit code, save code, and see changes in my job page, but I'm still seeing the old text. I edited the en-GB, en-EU, and en-US and none pull through. 
-

## Steps to replicate behavior

1.

## Screenshots

__Current__

__Expected__

**Comment by bulbajackel** [comment]
Hello, 

You mentioned you were using the plugin for Wordpress? Are you changing the files in the plugin directory itself? 

The file that you are editing should look similar to the one found [here](https://github.com/bullhorn/career-portal/blob/master/src/res/en-US/modal.json).  The ones that you want to adjust would be the `"successSubHeading"` and `"successHeading"` key values.

If you are having further trouble with the update, can you post a link to your career portal so I can take a look and possibly point you in the right direction.

**Comment by talent1** [comment]
Thank you for getting back to me; today the message reflected my change so it appears it just needed more time to update. I was changing the files in the plugin directory, so I'm not sure what the delay was about. Thank you!
