### ISSUE TITLE
Error appling resume for deleted caditate

### ISSUE THREAD

**Issue by domus71** [bullhorn/career-portal#131]
I'm trying to apply a resume for a candidate that has been deleted from candidate list and has been removed from vacancy's online responses.

The request:
https://public-restXX.bullhornstaffing.com/rest-services/KEY/apply/JOBID/raw?externalID=Resume&type=Resume&firstName=MyName&lastName=MyLastNAme&email=myEmail&phone=555-555555&gender=&ethnicity=&veteran=&disability=&format=doc

The response:
{
  "message" : "org.hibernate.id.IdentifierGenerationException: the inserted row could not be located by the unique key: uuid",
  "errorCode" : 400,
  "errorMessage" : "org.hibernate.id.IdentifierGenerationException: the inserted row could not be located by the unique key: uuid"
}

The steps:
1. Apply for a position
2. Delete Vacancy's Online Responses
3. Delete Candidate
4. Clear browser local data (Session local storage)
5. Re-apply for tha same position.
6. Get this error

Any ideas?
Thanks

**Comment by bulbajackel** [comment]
Hello,

This is related to the email address associated with that test record that you possibly have used.  I suggest removing the email address before deleting for testing purposes.  This was discussed in a previous open issue #51 .

Thanks
