### ISSUE TITLE
Question: Adding and removing fields

### ISSUE THREAD

**Issue by eggmedia** [bullhorn/career-portal#132]
## Screenshots
![stembridge-screen](https://cloud.githubusercontent.com/assets/28601462/25905452/15c6b01c-3570-11e7-8186-69882da96db4.jpg)

__Current__
This seems simple, but our developer can't figure it out. The screenshot is what comes up when someone applies for a job, and attachment of a resume is required. We want to make the resume optional but also add a field for job title. The website that uses this is http://stembridgeagency.com

**Comment by bvkimball** [comment]
All the logic that control how the modal works is located here:
https://github.com/bullhorn/career-portal/tree/master/src/app/modal

Pre-submit validations occur here:
https://github.com/bullhorn/career-portal/blob/master/src/app/modal/modal.controller.js#L299

You can add all the fields you want to the form and submit them with the Apply Service.
