### ISSUE TITLE
Getting sidebar to use Filter

### ISSUE THREAD

**Issue by jdmills64** [bullhorn/career-portal#138]
I added Filter on customText5 field to list.html so jobs only appear for the filtered value.  However, the sidebar still lists all locations and categories for all jobs, not just filtered. The counts represent the full amount of jobs.  If you click on a location, only jobs that meet filter criteria as expected.

What do I need to change in sidebar? or search.service?

**Comment by bvkimball** [comment]
I am a little confused by your question. Are you trying to add a new filter to the sidebar or are you trying to filter out published jobs from the career portal?

you can modify the query constructed here: https://github.com/bullhorn/career-portal/blob/master/src/app/services/search.service.js#L164

**Comment by jdmills64** [comment]
Thanks for reply and I apologize for confusion as I am new to Bullhorn.  Your suggestion is how I attacked this initially, but it rendered an Oh No! no jobs message.  I then saw another thread  (#58) that pointed me to list.html.  That worked to display jobs only for division (customText5 = "First-Recruiting").  However the sidebar shows all locations and counts of jobs for all divisions not just First Recruiting.  So, I want to change the query that builds that list of locations and counts.

**Comment by jdmills64** [comment]
For further background, I made this change to search.service initially, but it was returning Oh No! 
   let query = `(isOpen${isSearch ? ':1' : '=true'})`;
                    query += ` AND (customText5 = 'First Recruiting')`;

**Comment by bvkimball** [comment]
So the issue might be that you are using "QuerySytax" when it is using the search API.
ie. try this instead

```
let query = `(isOpen${isSearch ? ':1' : '=true'})`;
query += `AND (customText5${isSearch ? ':"First Recruiting"' : "='First Recruiting'"})`;
```

or just assume its a search
```
let query = 'isOpen:1 AND customText5:"First Recruiting"';
```

**Comment by jdmills64** [comment]
OK so that corrected that, and now sidebar is correct but no jobs display. I used an untouched list.html and the modified search.service:

![image](https://user-images.githubusercontent.com/29442208/27300139-4070c3ea-54f4-11e7-9f32-e9e6dec0e82d.png)

With the change to list.html that I had previously made and no change to searxh.service, I get
![image](https://user-images.githubusercontent.com/29442208/27300310-ea6e5be6-54f4-11e7-9154-29456de5ad05.png)
here is what I did there: (adding filter:{customText5: 'First Recruiting' to list.html)
        
        <div class="card-wrapper" data-ng-repeat="job in list.SearchService.currentListData | orderBy:dateLastPublished | filter:{customText5: 'First Recruiting'}">

**Comment by jdmills64** [comment]
Here is the console messages from gulp serve:dist >consoleloog.txt  I am sorry but I don't see the network logs or how to capture them. I
[consolelog.txt](https://github.com/bullhorn/career-portal/files/1088635/consolelog.txt)

**Comment by jdmills64** [comment]
Just to be certain, I pulled a new, fresh copy and only added the change above to search.service with same results.  No jobs show up.

**Comment by jdmills64** [comment]
Any suggestions would be greatly appreciated.  Are you thinking it is something in my environment or in the code?

**Comment by jdmills64** [comment]
UPDATE: Problem was in the Filter statement.  I needed to use your first suggestion:
let query = `(isOpen${isSearch ? ':1' : '=true'})`;
query += `AND (customText5${isSearch ? ':"First Recruiting"' : "='First Recruiting'"})`;

I am closing this issue.  Thanks for your help.
