### ISSUE TITLE
Extra Form Fields

### ISSUE THREAD

**Issue by VR51** [bullhorn/career-portal#139]
Is there a way to add extra fields to the application form? If there is, where can I read more about it.

**Comment by bulbajackel** [comment]
Heya,

For adding extra fields to the application form, there may need to be some additional work done depending on the actions required.  Most fields that are added would need some sort of authentication process to authorize you to write data to the fields in the database.  I suggest checking out some of Bullhorn's [developer documentation found here ](http://bullhorn.github.io/rest-api-docs/).

Please let me know if you have any questions.

**Comment by VR51** [comment]
That's great. Thank you.
