### ISSUE TITLE
Job Order API call missing fields

### ISSUE THREAD

**Issue by jfetner** [bullhorn/career-portal#142]
I am trying to filter jobs by department which I believe I can get to by JobOrder.ClientCorporation.Department. When I query the JobOrders, ClientCorporation is not returned as a field, despite me specifying to return all fields (*). How can I get the department a job is in?

Query:
https://public-rest33.bullhornstaffing.com/rest-services/[CORP_TOKEN]/search/JobOrder?query=(isOpen:1)&fields=*&sort=id&count=500&start=0

Available Fields:
http://bullhorn.github.io/rest-api-docs/entityref.html#joborder

**Comment by bulbajackel** [comment]
Hello, the Public API used for The Bullhorn Career Portal has a limited amount of fields available to it within Bullhorn to protect the data accessible through the portal.   You are able to add to the available fields within the API by contacting Bullhorn Support.   You are able access any field available on a job order, but you are unable to access fields for other entities, such as CorporateUsers or ClientCorporations.   

You will be able to utilize a dropdown for determining how a job should be filtered.  Bullhorn Support will be able to help with that.

Please let me know if you have any questions about any of this.
