### ISSUE TITLE
Resume filetype tooltip not opening

### ISSUE THREAD

**Issue by TIIUNDER** [bullhorn/career-portal#144]
The file format tooltip at the applying form is not working

## Current behavior

If I click on the tooltip icon (question mark), nothing happens.

## Expected behavior

If I click on the tooltip icon, the tooltip opens.

## Steps to replicate behavior

1. Go to http://pragmatica.ch/career-portal/#/jobs (It's version 2.0.1)
2. Select a job and click "apply"
3. Click on the question mark button next to "Resume File"

**Comment by acrowe2** [comment]
Fixed in [v2.5.0](https://github.com/bullhorn/career-portal/releases/tag/v2.5.0)
