### ISSUE TITLE
Uglify not working with gulp build

### ISSUE THREAD

**Issue by mijgame** [bullhorn/career-portal#146]
Hello,

When I run `gulp build` or `gulp serve:dist`, scripts and styles are not minified. When I look in build\build.js, I see `$.uglify()` and `$.minifyCss({cache: true})` after the respective filters for js and css. I don't see any weird or unexpected output in the console when building.

Ideas on what could be happening here? I haven't changed the build scripts by hand, they are the same as the scripts in the master branch.

Thanks in advance

**Comment by charlesabarnes** [comment]
This was fixed in #159
