### ISSUE TITLE
Bullhorn career portal in spanish

### ISSUE THREAD

**Issue by joaquinorono** [bullhorn/career-portal#147]
Hi, i've translated the career portal in locale es-ES, how can I add to the repository?

Best Regards

**Comment by bvkimball** [comment]
That's awesome, please submit a pull request and we can merge it in.

**Comment by joaquinorono** [comment]
Sorry my ignorance, I can't find the place to send the files..... I have to copy/paste the content of the files I guess? Can I sent the files by email?

**Comment by bulbajackel** [comment]
You are able to submit a pull request by following the steps in the article [here](https://help.github.com/articles/creating-a-pull-request/).  Please let me know if you need any further assistance with performing the pull request and I'll be happy to help out.
