### ISSUE TITLE
%%KEY_NOT_FOUND%%

### ISSUE THREAD

**Issue by derekhawk** [bullhorn/career-portal#149]
![oscp issue](https://user-images.githubusercontent.com/30411640/28527250-f8f7cb88-7057-11e7-8e97-b221796267a4.PNG)

Please see screenshot. Page is not populated with data. 

Bullhorn has yet to enable our account until this issue has been resolved.

**Comment by bulbajackel** [comment]
This is due to the JSON files in the /res/ directory not being present.   To resolve this, please ensure all files are uploaded to the correct directories.  

Please let me know if you need any further assistance.
