### ISSUE TITLE
Python 2 dependency in build?

### ISSUE THREAD

**Issue by ryantheleach** [bullhorn/career-portal#150]
```
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\Administrator\Desktop\
Ryan\bullhorn\career-portal\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Administrator\Desktop\Ryan\bullhorn\c
areer-portal\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Administrator\Desktop\Ryan\bullhorn\c
areer-portal\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Administrator\Desktop\Ryan\bullhorn\care
er-portal\node_modules\which\which.js:89:16
```

It appears the build has a hidden dependency on Python2 that was not documented on the readme.

Either this should be documented, or the build should be adjusted to install python2?

Tested on Windows 7.

**Comment by MikeDpicks** [comment]
Hello Ryan,

The Open Source Career Portal itself does not have any Python dependencies. It sounds like you have a node module installed that has a Python dependency. A common one I have seen is that installing node-sass will require Python to be installed, but there are also many others. Hope this helps!

**Comment by ryantheleach** [comment]
This was from a fresh PC that hadn't used development previously.

I installed python and fixed this eventually (after moving directories to root C, NPM loves it's deep directories).. for some reason, something wanted admin access as well, which was unexpected.

This was more a heads up for documentation purposes, rather then a support ticket :)

**Comment by bvkimball** [comment]
I went through the dependencies and it does seem only node-sass is most likely the culprit. this dependency comes from gulp-sass which hasn't update to the latest node-sass version yet.  Not sure if that would fix it. https://github.com/sass/node-sass/issues/1379

**Comment by kjavia** [comment]
I had to update this `"gulp-sass": "~3.1.0"` in `package.json` to make it work.

**Comment by charlesabarnes** [comment]
We updated Gulp-sass This should be taken care of now.  Please let me know if you have any more questions or issues
