### ISSUE TITLE
Bullhorn Share has incorrectly built LinkedIn link source parameter.

### ISSUE THREAD

**Issue by danderson421** [bullhorn/career-portal#151]
INSERT SHORT DESCRIPTION EXPLAINING THE HIGH-LEVEL REASON FOR THE NEW ISSUE HERE.

## Current behavior
https://www.linkedin.com/shareArticle?mini=true&source=Misource%Job%20Portal&title=Check%20out%20this%20Web%20Developer%20Full%20Stack%20job!&url=http://google.com
-

## Expected behavior
https://www.linkedin.com/shareArticle?mini=true&source=Misource%20Job%20Portal&title=Check%20out%20this%20Web%20Developer%20Full%20Stack%20job!&url=http://google.com
-

## Steps to replicate behavior

1. navigate to a job description page
2. hit share
3. select LinkedIn
4. notice the missing "20" in the "source" url parameter

**Comment by bulbajackel** [comment]
By default, this is populated with a value in the [share.service.js](https://github.com/bullhorn/career-portal/blob/af5115f8664eb4cb2115770585265aae226abc18/src/app/services/share.service.js#L30) file.  It appears to have been modified to your company;s name.  I suggest checking out the modifications made there to ensure your share parameter has the changes mentioned.

Please let me know if you have any more questions

**Comment by danderson421** [comment]
Thanks for pointing me in the right direction. I didn't remember changing that.

**Comment by bulbajackel** [comment]
No problem! Happy to happy to help!
