### ISSUE TITLE
pound sign

### ISSUE THREAD

**Issue by danderson421** [bullhorn/career-portal#153]
INSERT SHORT DESCRIPTION EXPLAINING THE HIGH-LEVEL REASON FOR THE NEW ISSUE HERE.

## Current behavior
there is currently a "#" in the default url for each job.
http://jobportal.misource.com/#/jobs/20450
-

## Expected behavior
no # symbol...
http://jobportal.misource.com/jobs/20450
-

## Steps to replicate behavior

1. browse to a job description page.

**Comment by bulbajackel** [comment]
Hello,
The hashing in the URL is how angular addresses navigating to new pages without them being actually there (a physical HTML file in a separate directory) allowing you to successfully navigate to an individual job from an external resource without issue.
I have found a couple of [stackoverflow articles](https://stackoverflow.com/questions/16677528/location-switching-between-html5-and-hashbang-mode-link-rewriting) that provide a high level overview of making this change.  It would require implementing HTML5 routing features into the app.
   
For compatibility reasons this was elected to not be included initially but feel free to make the change and submit a pull request so we can get this merged into the app. Feel free to let me know if you need any additional assistance
