### ISSUE TITLE
no source parameter parsed by Bullhorn

### ISSUE THREAD

**Issue by danderson421** [bullhorn/career-portal#154]
## Current behavior
after a candidate applies through the job portal, the source of the candidate is non-specific and seems to be a default value in Bullhorn app.
-

## Expected behavior
ability to specify a source within the career portal so jobs that come in to Bullhorn from the career portal can be identified.

**Comment by bulbajackel** [comment]
The source is determined by an optional URL parameter that you can append to your URLs that you share to third party sites.  The source parameter can be added so the source tracks within the app. Below I am providing an example of how you may want to structure your URLs.

`acme.com/career/#/jobs/12?source='LinkedIn`

**Comment by danderson421** [comment]
is this the function the native apply modal uses?

 email: function email(job) {
	                    return '?subject=' + encodeURIComponent(job.title) + '&body=' + _this.description(job, window.location.href);
	                }

**Comment by bulbajackel** [comment]
The [apply service](https://github.com/bullhorn/career-portal/blob/e6a9202b2a6c339abe01cfc3abd7c1e6df966b31/src/app/services/apply.service.js#L72) actually checks for that parameter in the url.

**Comment by danderson421** [comment]
thanks - I have it working as needed.
