### ISSUE TITLE
Add bullhorn.com link to Bullhorn logo

### ISSUE THREAD

**Issue by kbushkoBH** [bullhorn/career-portal#156]
## Current behavior

- Bullhorn logo that appears in the bottom of left navigation ("Powered by Bullhorn") does not link to bullhorn.com

## Expected behavior

- Bullhorn logo that appears in the bottom of left navigation ("Powered by Bullhorn") should link to bullhorn.com

**Comment by acrowe2** [comment]
Fixed in [v2.5.0](https://github.com/bullhorn/career-portal/releases/tag/v2.5.0)
