### ISSUE TITLE
Removing "Job Submission" for applications

### ISSUE THREAD

**Issue by Royce-Robbins** [bullhorn/career-portal#160]
Not so much a universal issue as more or a process alignment issue.  Can we remove the Internal Submission function without wrecking the overall functionality of the Career Portal?

## Current behavior
All applications from the career portal are automatically logged as an Job Submission.

## Desired behavior
All applications are loaded as a candidate and flagged as a Web Response on the appropriate Job but no Job Submission is completed.

**Comment by bulbajackel** [comment]
Hey Royce,

With web responses, they are Job Submissions with the status of "New Lead" where in the application they are displayed as web responses.  They are the same entity, but in the application they should display separately. 

Are you seeing different behavior?

**Comment by Royce-Robbins** [comment]
No - that is the behavior we are seeing.  However, this breaks or process and associated reporting metrics.  We are looking to see if we can remove the Job Submission component, but retain the rest of the functionality.  The main reason is we only add candidates as a job submission when they are fully vetted and what is happening is any Portal Applicant is showing Job Submission dates that are a week or more older when they should be showing as the current date (does this make sense?)

**Comment by bulbajackel** [comment]
I gotcha, currently with the public API used within the Career Portal, it uses a single apply function that creates a candidate and adds them to the job as you are able to see.  

The functionality that you desire would require extending the app with the normal [REST API](http://bullhorn.github.io/rest-api-docs/) to add a candidate manually then add a note to a job and candidate to possibly track what job they applied to.

Does this sound like what you are looking for?  The biggest challenge would be to keep the association to the job they applied to, as a Job Submission establishes that relationship between the Job and Candidate.  

If you wanted to query the existing data in your system, and exclude when your web responses were added in your search, you can utilize the Job Submission History to determine when a Job submission was changed to a status that was not New Lead.

**Comment by Royce-Robbins** [comment]
Okay, that might work provided we can associate the note made to the specific job query...will investigate.
