### ISSUE TITLE
Getting 500 exceptions while running app locally

### ISSUE THREAD

**Issue by kjavia** [bullhorn/career-portal#163]
This is the first time I am trying to run the app locally. I cloned the repo and ran bower, gulp etc. I can start the app but all rest calls made by the code for e.g. below, throw a 500 exception

https://public-rest3.bullhornstaffing.com/rest-services/{{my_corp_token}}/search/JobOrder?query=(isOpen:1)&fields=id,title,publishedCategory(id,name),address(city,state),employmentType,dateLastPublished,publicDescription,isOpen,isPublic,isDeleted&count=20&sort=-dateLastPublished&start=0

comes back as 
````
{
errorMessage: "An internal error has occurred",
errorMessageKey: "errors.internalError"
}
````

The app is running under `localhost:3000`

**Comment by bulbajackel** [comment]
As there are steps to ensure the public API can be used, I wanted to check, have you contacted Bullhorn Support to enable use of your career portal?  That is a prerequisite action that has to be done for your jobs to display.

**Comment by kjavia** [comment]
Someone from BH support is on this case but they haven't mentioned anything about enabling public api's yet. I have access to the control panel, I don't see public api section anywhere. There is a `Web services API` section with key etc. but I think that is for server to server calls.

**Comment by bulbajackel** [comment]
Hello! I communicated with the representative assisting you in Bullhorn Support.  If you retry the request it should work properly for you without the errors.  They will be following up with you via email shortly. Please let me know if you have any more questions.
