### ISSUE TITLE
Resume is required on application.  Send button won't activate.

### ISSUE THREAD

**Issue by technoicon** [bullhorn/career-portal#164]
Hi,

We have setup the default install and just changed a few required fields.

We have a huge issue in that no one can apply unless they upload a resume.  I have tried to figure out how to bypass this but can't figure it out.

We need people to be able to apply with just first, last name and email.

Any help would be appreciated.

**Comment by bulbajackel** [comment]
Currently, you are not able to apply to the public-rest API without some form of resume.  This is to ensure the record is successfully parsed into the system.  You can do one of two things to meet the requirements for a "abbreviated apply". 

First, you can utilize the full Bullhorn Rest API to create a candidate record with the information entered in.  You can find documentation on this api [here](http://bullhorn.github.io/rest-api-docs/).  

The second option is to submit applications in a way similar to the way the Apply with LinkedIn applications work,  We submit a txt format resume containing all of the relevant details from the applicant's LinkedIn account.  If the elect to not use the resume, you can possibly have a radio button to control whether or not to upload a resume and then behind the scenes, send a txt "resume" that contains text that says "no resume" or something similar.  

You are able to also change the validation for the send button by modifying the [`enableSendButton `method found here](https://github.com/bullhorn/career-portal/blob/master/src/app/modal/modal.controller.js#L115).  This will need to be done after executing one of the previously mentioned options.   

Please let me know if you have any questions.

**Comment by aciavolino** [comment]
Charles, I am having this same issue. Could you please provide a working ink for the enableSendButton method?
