### ISSUE TITLE
Custom Filters and extra job fields

### ISSUE THREAD

**Issue by sudar77** [bullhorn/career-portal#165]
How do I add extra fields to the filters? I would like to add an extra filter for "Salary From" which exists in the Bullhorn backend dashboard but I would like it on the Career Portal aswell.

Is this possible? and where would I look? Thanks

**Comment by bulbajackel** [comment]
Hello Sudar, 
You are able to add additional filters to the sidebar, but there will need to be several modifications made in different areas, first you will want to adjust the sidebar controller and template to include your additional fiels, then, you will want to modify the search service as well.   

#46 and #138 are two examples of people attempting to utilize additional or customized filters on their portal

**Comment by sudar77** [comment]
Do you know which files these are in? Are they in the various js files?

Thanks for the quick reply

**Comment by bulbajackel** [comment]
You'll be able to find the sidebar files in [the sidebar directory found here](https://github.com/bullhorn/career-portal/tree/master/src/app/sidebar) and the[ search service](https://github.com/bullhorn/career-portal/blob/master/src/app/services/search.service.js) in the services directory.

**Comment by sudar77** [comment]
Thanks so much. I will take a look at this shortly

Is there also a way to display the "Salary From" details on the job listings on the right hand panel?

**Comment by bulbajackel** [comment]
You are able to do that by adding the data you would like to add to the[ list template ](https://github.com/bullhorn/career-portal/blob/master/src/app/list/list.html) using [angular interpolation](https://docs.angularjs.org/guide/interpolation).

What you will add is something like `{{::job.salary}}`

**Comment by sudar77** [comment]
Ok great - thank you very much

**Comment by sudar77** [comment]
I will take a proper look at the code I have when I get home as I dont remember seeing all these HTML files in the version of the Career Portal that I have. The examples you have shown seem to have a lot more HTML pages than the one I have

**Comment by bulbajackel** [comment]
It is possible that you are taking a look at the built version of the career portal (found on the releases page) you will instead want to [clone down the career portal and start from there](https://github.com/bullhorn/career-portal#building).

**Comment by sudar77** [comment]
ah - ok great. Thanks for all your help. I think that will be the version I have because it was easy to put it onto my clients shared hosting account
