### ISSUE TITLE
Installation process onto shared hosting

### ISSUE THREAD

**Issue by sudar77** [bullhorn/career-portal#166]
I have seen that you need to build the code especially if you want to brand and add your own filters etc but I am using a shared hosting account(UKhost4U). Is there another way to do this as I cant see how this can be done easily.....I was hoping for a download and upload to hosting via FTP process.

Can anyone help? Thanks

**Comment by bulbajackel** [comment]
Hello, looks like [this is what you are looking for](https://github.com/bullhorn/career-portal/wiki/Uploading-via-Site-Host-FTP).  This is located in our wiki.

**Comment by sudar77** [comment]
Hi, The only problem is that is for built version of the career portal (therefore without my custom added extra filter fields and extra job field added). 

As you mentioned in #165 I need to clone the site and then build but I cannot build (or at least I dont know how to on shared hosting). Unless there is another way to build it with my changes and then upload

**Comment by bulbajackel** [comment]
In the link that I provided there, it also includes the steps for building.  This build process generates files used for static hosting.  You can find the steps for building [here](https://github.com/bullhorn/career-portal#building).
