### ISSUE TITLE
Error 500 in search/JobOrder

### ISSUE THREAD

**Issue by jmarti** [bullhorn/career-portal#167]
Just when I wake up the app, I get an Error 500 in this service:

https://public-rest23.bullhornstaffing.com/rest-services/{{corpToken}}/search/JobOrder?query=(isOpen:1)&fields=id,title,publishedCategory(id,name),address(city,state),employmentType,dateLastPublished,publicDescription,isOpen,isPublic,isDeleted&count=20&sort=-dateLastPublished&start=0

I got that response

```json
{
  "errorMessage" : "An internal error has occurred",
  "errorMessageKey" : "errors.internalError"
}
```

**Comment by bulbajackel** [comment]
To utilize the public rest API you need to contact Bullhorn Support.  There are some steps that must be done on our end to enable communication to your database.  Have you been in touch with our support team yet?

**Comment by jmarti** [comment]
Yes! They send me the corp token, the company name and the SL.
Is there anything else?

**Comment by bulbajackel** [comment]
Yes, usually they enable the API after they receive the address you will be hosting the site at, however it seems as if you will be customizing it locally, so I suggest reaching back out to them and asking to have the API enabled.  I will submit feedback so you will not have to do so in the future.

**Comment by jmarti** [comment]
They whitelisted my local URL, but there is some other things that caused this problem:
- Seems BhRestToken headers value is not implemented.
- The REST API Url is wrong. Now is `https://rest23.bull...` instead of `https://public-rest23.bull...`

**Comment by bulbajackel** [comment]
So that would be a different API. The public API is the correct URL for your career portal. Do you have an email that I can reach you on directly to get this resolved?

**Comment by jmarti** [comment]
I sent you an email.

**Comment by bulbajackel** [comment]
Jmarti and I are working on this via email.
