### ISSUE TITLE
Error: angular is not installed

### ISSUE THREAD

**Issue by billy-bacon** [bullhorn/career-portal#169]
Running steps in README to configure/build and serve the career portal app for local development is not working. 

## Current behavior
After cloning the repo, I ran the following commands a noted in the README.

```
npm install -g bower
npm install -g gulp
npm install
bower install
```

```
gulp --corpToken='[CORP_TOKEN]' --sl='[SWIMLANE]' --companyName='[COMPANY_NAME]' 
gulp serve --corpToken='[CORP_TOKEN]' --sl='[SWIMLANE]' --companyName='[COMPANY_NAME]'
```
Keep in mind I've substituted the actual values for these tokens/flags in my terminal and I'm not using the placeholders above.

## Expected behavior

The app starts up on a local web server and can be accessed via http://localhost:3000. This is not happening and it doesn't appear that my machine is listening on port 3000 or any new port for that matter. 

I've attached the output from my terminal. It looks like gulp is _running_ but nothing is being served. I can't figure out what step I'm missing or why this is happening.

[career-portal-output.log](https://github.com/bullhorn/career-portal/files/1507371/career-portal-output.log)

**Comment by bulbajackel** [comment]
Hey Billy, were there any errors when you ran `npm install` or `bower install`?  It seems as if it BrowserSync isn't kicking in.

**Comment by billy-bacon** [comment]
Nope, `npm install` and `bower install` ran clean and like a charm. I even tried nuking my `bower_components` directory and ran `bower install` again and watched it rip through everything.

I'm attaching the terminal output from `bower install` for reference. 

[bower-install.log](https://github.com/bullhorn/career-portal/files/1507435/bower-install.log)

**Comment by billy-bacon** [comment]
Not sure if this is relevant but I just thought to check and provide my versions of npm and node.

npm --version
3.10.10
node --version
v6.10.3

**Comment by bvkimball** [comment]
Can you try setting all the angular library versions to 1.5.8 instead of ~1.5.8, then clean bower_components and re-install

**Comment by billy-bacon** [comment]
Apologies for the _user error_. Somehow, I did not have the following files in my workspace, which was the root of my problem.

```
	.babelrc
	.bowerrc
	.codeclimate.yml
	.editorconfig
	.jscsrc
	.travis.yml
```

After getting those back in place, ```gulp server``` spews a bunch warnings regarding ES6 but the app launches just fine and is accessible via http://localhost:3000.

Thank you for commenting and assisting me in this.
