### ISSUE TITLE
Career Portal page blank. No Content

### ISSUE THREAD

**Issue by arnatusc** [bullhorn/career-portal#174]
Followed the configuration process to up date my portal site after I migrated my hosting over to Windows hosting service on GoDaddy.  Created a new sub-domain http://jobs3.hsf.io  , uploaded all contents of career-portal-v2.5.1 folder and when you go to the new sub-domain, I am seeing The Bullhorn logo and Career Portal in the chrome in my Chrome browser but none of my job content is appearing.

**Comment by bulbajackel** [comment]
Hello,
I am personally not seeing anything currently, are you sure everything is uploaded?

After that, have you published your jobs yet? That is how you make your jobs available to the public.

**Comment by arnatusc** [comment]
Back Story-

Previously had jobs.hsf.io as a seperate domain hosted and publishing all
my jobs.

As of yesterday shut down jobs.hsf.io.  Created subdomain under hsf.io
called jobs3.hsf.io, uploaded files, etc and not working.

Not seeing anything as in you are not seeing the Config Files uploaded?  I
used my GoDaddy hosting control panel to upload everything and seems to be
in there just fine.

Plenty of published jobs should be showing up.
-Andy

**Comment by bulbajackel** [comment]
I am currently receiving 404 errors on the CSS and Javascript files necessary for displaying the page

**Comment by arnatusc** [comment]
Sorry I am not following you. Translation?
What's the fix?  Upload my files again?  Or something else.


-- 
*Andy Natusch*
Owner & Principal Recruitment Consultant
HSF Consulting
(415) 599-0255
www.hsf.io
andy@hsf.io

[image: www.linkedin.com/in/andyhsfio/]
<http://www.linkedin.com/in/andyhsfio/>

**Comment by arnatusc** [comment]
Here is a screen shot of what I uploaded.

https://goo.gl/zx4zeu

This was the contents of the edited Career-portal V2.5.1 folder.





On Tue, Jan 2, 2018 at 5:21 PM, Charles Barnes <notifications@github.com>
wrote:
>
> I am currently receiving 404 errors on the CSS and Javascript files
necessary for displaying the page

**Comment by bulbajackel** [comment]
It seems as if your files are not all uploaded.  You may want to contact your website's support to receive assistance with uploading all of the files so they can be accessible by the public.

**Comment by arnatusc** [comment]
Hey Charles-

Did you see the screen shot I sent you?  The screen shot shows that all the
files uploaded.  Did it not?  Please confirm.

As for support, there is none, it's just me so I really appreciate the help
in sorting this out.  Seems I am 80% of the way there just have something
that's hanging up.

-Andy

**Comment by bulbajackel** [comment]
Hello, by your website's support I mean Godaddy as the files are still not showing as present at the specified location.  After taking a second look at the screenshot provided I noticed that you have none of the necessary files that are located in directories within the career portal [release](https://github.com/bullhorn/career-portal/releases/download/v2.5.1/career-portal-v2.5.1.zip) download.

There are contents that needs to be uploaded from the assets, fonts, res, scripts, and styles directories that are not currently present.

**Comment by arnatusc** [comment]
I was able to upload all the files.

Screen shot here:
https://goo.gl/hESzyY
https://goo.gl/vAz88x

Attached PDF is what my json.app file looks like.

Career Portal still not working.

**Comment by bulbajackel** [comment]
You are almost there! looks like the MIME Type of json is currently not active on the webserver.  I would suggest contacting Godaddy support for enabling this as this can be different on each vendor.

**Comment by arnatusc** [comment]
Just so nothing gets lost in translation, what specifically should I
tell/ask Godaddy?  If you could please let me know I'll just read what you
write to them verbatim.  Thanks!

-- 
*Andy Natusch*
Owner & Principal Recruitment Consultant
HSF Consulting
(415) 599-0255
www.hsf.io
andy@hsf.io

[image: www.linkedin.com/in/andyhsfio/]
<http://www.linkedin.com/in/andyhsfio/>

**Comment by arnatusc** [comment]
I've located where I can enable the MIME type.  What is the MIME type?
For example:
text/plain .mytxt
image/jpeg .myjpeg

**Comment by bulbajackel** [comment]
The MIME media type for JSON text is application/json

**Comment by arnatusc** [comment]
That's not an option.  Here's my options:

text/h323 .323
video/3gpp2 .3g2
video/3gpp .3gp
video/3gpp2 .3gp2
video/3gpp .3gpp
video/x-ivf .IVF
audio/aac .aac
application/octet-stream .aaf
application/octet-stream .aca
application/msaccess .accdb
application/msaccess .accde
application/msaccess .accdt
application/internet-property-stream .acx
audio/vnd.dlna.adts .adt
audio/vnd.dlna.adts .adts
application/octet-stream .afm
application/postscript .ai
audio/x-aiff .aif
audio/aiff .aifc
audio/aiff .aiff
application/x-ms-application .application
image/x-jg .art
application/octet-stream .asd
video/x-ms-asf .asf
application/octet-stream .asi
text/plain .asm
video/x-ms-asf .asr
video/x-ms-asf .asx
application/atom+xml .atom
audio/basic .au
video/avi .avi
application/olescript .axs
text/plain .bas
application/x-bcpio .bcpio
application/octet-stream .bin
image/bmp .bmp
text/plain .c
application/vnd.ms-cab-compressed .cab
application/vnd.ms-office.calx .calx
application/vnd.ms-pki.seccat .cat
application/x-cdf .cdf
application/octet-stream .chm
application/x-java-applet .class
application/x-msclip .clp
image/x-cmx .cmx
text/plain .cnf
image/cis-cod .cod
application/x-cpio .cpio
text/plain .cpp
application/x-mscardfile .crd
application/pkix-crl .crl
application/x-x509-ca-cert .crt
application/x-csh .csh
text/css .css
application/octet-stream .csv
application/octet-stream .cur
application/x-director .dcr
application/octet-stream .deploy
application/x-x509-ca-cert .der
image/bmp .dib
application/x-director .dir
text/xml .disco
application/x-msdownload .dll
text/xml .dll.config
text/dlm .dlm
application/msword .doc
application/vnd.ms-word.document.macroEnabled.12 .docm
application/vnd.openxmlformats-officedocument.wordprocessingml.document
.docx
application/msword .dot
application/vnd.ms-word.template.macroEnabled.12 .dotm
application/vnd.openxmlformats-officedocument.wordprocessingml.template
.dotx
application/octet-stream .dsp
text/xml .dtd
application/x-dvi .dvi
video/x-ms-dvr .dvr-ms
drawing/x-dwf .dwf
application/octet-stream .dwp
application/x-director .dxr
message/rfc822 .eml
application/octet-stream .emz
application/vnd.ms-fontobject .eot
application/postscript .eps
text/x-setext .etx
application/envoy .evy
application/octet-stream .exe
text/xml .exe.config
application/vnd.fdf .fdf
application/fractals .fif
application/octet-stream .fla
x-world/x-vrml .flr
flv-application/octet-stream .flv
image/gif .gif
application/x-gtar .gtar
application/x-gzip .gz
text/plain .h
application/x-hdf .hdf
text/x-hdml .hdml
application/x-oleobject .hhc
application/octet-stream .hhk
application/octet-stream .hhp
application/winhlp .hlp
application/mac-binhex40 .hqx
application/hta .hta
text/x-component .htc
text/html .htm
text/html .html
text/webviewhtml .htt
text/html .hxt
image/x-icon .ico
text/calendar .ics
image/ief .ief
application/x-iphone .iii
application/octet-stream .inf
application/x-internet-signup .ins
application/x-internet-signup .isp
application/java-archive .jar
application/octet-stream .java
application/liquidmotion .jck
application/liquidmotion .jcz
image/pjpeg .jfif
application/octet-stream .jpb
image/jpeg .jpe
image/jpeg .jpeg
image/jpeg .jpg
application/javascript .js
text/jscript .jsx
application/x-latex .latex
application/x-ms-reader .lit
application/octet-stream .lpk
video/x-la-asf .lsf
video/x-la-asf .lsx
application/octet-stream .lzh
application/x-msmediaview .m13
application/x-msmediaview .m14
video/mpeg .m1v
video/vnd.dlna.mpeg-tts .m2ts
audio/x-mpegurl .m3u
audio/mp4 .m4a
video/mp4 .m4v
application/x-troff-man .man
application/x-ms-manifest .manifest
text/plain .map
application/x-msaccess .mdb
application/octet-stream .mdp
application/x-troff-me .me
message/rfc822 .mht
message/rfc822 .mhtml
audio/mid .mid
audio/mid .midi
application/octet-stream .mix
application/x-smaf .mmf
text/xml .mno
application/x-msmoney .mny
video/quicktime .mov
video/x-sgi-movie .movie
video/mpeg .mp2
audio/mpeg .mp3
video/mp4 .mp4
video/mp4 .mp4v
video/mpeg .mpa
video/mpeg .mpe
video/mpeg .mpeg
video/mpeg .mpg
application/vnd.ms-project .mpp
video/mpeg .mpv2
application/x-troff-ms .ms
application/octet-stream .msi
application/octet-stream .mso
application/x-msmediaview .mvb
application/x-miva-compiled .mvc
application/x-netcdf .nc
video/x-ms-asf .nsc
message/rfc822 .nws
application/octet-stream .ocx
application/oda .oda
text/x-ms-odc .odc
application/oleobject .ods
audio/ogg .oga
video/ogg .ogg
video/ogg .ogv
application/onenote .one
application/onenote .onea
application/onenote .onepkg
application/onenote .onetmp
application/onenote .onetoc
application/onenote .onetoc2
application/opensearchdescription+xml .osdx
font/otf .otf
application/pkcs10 .p10
application/x-pkcs12 .p12
application/x-pkcs7-certificates .p7b
application/pkcs7-mime .p7c
application/pkcs7-mime .p7m
application/x-pkcs7-certreqresp .p7r
application/pkcs7-signature .p7s
image/x-portable-bitmap .pbm
application/octet-stream .pcx
application/octet-stream .pcz
application/pdf .pdf
application/octet-stream .pfb
application/octet-stream .pfm
application/x-pkcs12 .pfx
image/x-portable-graymap .pgm
application/vnd.ms-pki.pko .pko
application/x-perfmon .pma
application/x-perfmon .pmc
application/x-perfmon .pml
application/x-perfmon .pmr
application/x-perfmon .pmw
image/png .png
image/x-portable-anymap .pnm
image/png .pnz
application/vnd.ms-powerpoint .pot
application/vnd.ms-powerpoint.template.macroEnabled.12 .potm
application/vnd.openxmlformats-officedocument.presentationml.template .potx
application/vnd.ms-powerpoint.addin.macroEnabled.12 .ppam
image/x-portable-pixmap .ppm
application/vnd.ms-powerpoint .pps
application/vnd.ms-powerpoint.slideshow.macroEnabled.12 .ppsm
application/vnd.openxmlformats-officedocument.presentationml.slideshow .ppsx
application/vnd.ms-powerpoint .ppt
application/vnd.ms-powerpoint.presentation.macroEnabled.12 .pptm
application/vnd.openxmlformats-officedocument.presentationml.presentation
.pptx
application/pics-rules .prf
application/octet-stream .prm
application/octet-stream .prx
application/postscript .ps
application/octet-stream .psd
application/octet-stream .psm
application/octet-stream .psp
application/x-mspublisher .pub
video/quicktime .qt
application/x-quicktimeplayer .qtl
application/octet-stream .qxd
audio/x-pn-realaudio .ra
audio/x-pn-realaudio .ram
application/octet-stream .rar
image/x-cmu-raster .ras
image/vnd.rn-realflash .rf
image/x-rgb .rgb
application/vnd.rn-realmedia .rm
audio/mid .rmi
application/x-troff .roff
audio/x-pn-realaudio-plugin .rpm
application/rtf .rtf
text/richtext .rtx
application/x-msschedule .scd
text/scriptlet .sct
application/octet-stream .sea
application/set-payment-initiation .setpay
application/set-registration-initiation .setreg
text/sgml .sgml
application/x-sh .sh
application/x-shar .shar
application/x-stuffit .sit
application/vnd.ms-powerpoint.slide.macroEnabled.12 .sldm
application/vnd.openxmlformats-officedocument.presentationml.slide .sldx
audio/x-smd .smd
application/octet-stream .smi
audio/x-smd .smx
audio/x-smd .smz
audio/basic .snd
application/octet-stream .snp
application/x-pkcs7-certificates .spc
application/futuresplash .spl
audio/ogg .spx
application/x-wais-source .src
application/streamingmedia .ssm
application/vnd.ms-pki.certstore .sst
application/vnd.ms-pki.stl .stl
application/x-sv4cpio .sv4cpio
application/x-sv4crc .sv4crc
image/svg+xml .svg
image/svg+xml .svgz
application/x-shockwave-flash .swf
application/x-troff .t
application/x-tar .tar
application/x-tcl .tcl
application/x-tex .tex
application/x-texinfo .texi
application/x-texinfo .texinfo
application/x-compressed .tgz
application/vnd.ms-officetheme .thmx
application/octet-stream .thn
image/tiff .tif
image/tiff .tiff
application/octet-stream .toc
application/x-troff .tr
application/x-msterminal .trm
video/vnd.dlna.mpeg-tts .ts
text/tab-separated-values .tsv
application/octet-stream .ttf
video/vnd.dlna.mpeg-tts .tts
text/plain .txt
application/octet-stream .u32
text/iuls .uls
application/x-ustar .ustar
text/vbscript .vbs
text/x-vcard .vcf
text/plain .vcs
application/vnd.ms-visio.viewer .vdx
text/xml .vml
application/vnd.visio .vsd
application/vnd.visio .vss
application/vnd.visio .vst
application/x-ms-vsto .vsto
application/vnd.visio .vsw
application/vnd.visio .vsx
application/vnd.visio .vtx
audio/wav .wav
audio/x-ms-wax .wax
image/vnd.wap.wbmp .wbmp
application/vnd.ms-works .wcm
application/vnd.ms-works .wdb
video/webm .webm
application/vnd.ms-works .wks
video/x-ms-wm .wm
audio/x-ms-wma .wma
application/x-ms-wmd .wmd
application/x-msmetafile .wmf
text/vnd.wap.wml .wml
application/vnd.wap.wmlc .wmlc
text/vnd.wap.wmlscript .wmls
application/vnd.wap.wmlscriptc .wmlsc
video/x-ms-wmp .wmp
video/x-ms-wmv .wmv
video/x-ms-wmx .wmx
application/x-ms-wmz .wmz
font/x-woff .woff
application/vnd.ms-works .wps
application/x-mswrite .wri
x-world/x-vrml .wrl
x-world/x-vrml .wrz
text/xml .wsdl
video/x-ms-wtv .wtv
video/x-ms-wvx .wvx
application/directx .x
x-world/x-vrml .xaf
application/xaml+xml .xaml
application/x-silverlight-app .xap
application/x-ms-xbap .xbap
image/x-xbitmap .xbm
text/plain .xdr
application/xhtml+xml .xht
application/xhtml+xml .xhtml
application/vnd.ms-excel .xla
application/vnd.ms-excel.addin.macroEnabled.12 .xlam
application/vnd.ms-excel .xlc
application/vnd.ms-excel .xlm
application/vnd.ms-excel .xls
application/vnd.ms-excel.sheet.binary.macroEnabled.12 .xlsb
application/vnd.ms-excel.sheet.macroEnabled.12 .xlsm
application/vnd.openxmlformats-officedocument.spreadsheetml.sheet .xlsx
application/vnd.ms-excel .xlt
application/vnd.ms-excel.template.macroEnabled.12 .xltm
application/vnd.openxmlformats-officedocument.spreadsheetml.template .xltx
application/vnd.ms-excel .xlw
text/xml .xml
x-world/x-vrml .xof
image/x-xpixmap .xpm
application/vnd.ms-xpsdocument .xps
text/xml .xsd
text/xml .xsf
text/xml .xsl
text/xml .xslt
application/octet-stream .xsn
application/octet-stream .xtp
image/x-xwindowdump .xwd
application/x-compress .z
application/x-zip-compressed .zip

**Comment by bulbajackel** [comment]
As previously mentioned, GoDaddy Support may be the best to reach for this to ensure this is done properly without negatively impacting the rest of your site as it does not have the required MIME type listed.

**Comment by arnatusc** [comment]
I did contacted GoDaddy support and they got me to the point where I just
need to select the MIME type.  Beyond that there is nothing they can do as
it's up to me to know which MIME type to use/.  Are you saying if I cannot
select application/json then I need to find a work around?

**Comment by bulbajackel** [comment]
I contacted our support team who will be reaching out as soon as possible to get this resolved.  This may require some additional troubleshooting that is best done over a screenshare.

**Comment by arnatusc** [comment]
Thanks Charles, still have not heard from support.  Is there a reference
number I can use if I call in?

-- 
*Andy Natusch*
Owner & Principal Recruitment Consultant
HSF Consulting
(415) 599-0255
www.hsf.io
andy@hsf.io

[image: www.linkedin.com/in/andyhsfio/]
<http://www.linkedin.com/in/andyhsfio/>

**Comment by bulbajackel** [comment]
Heya, I made sure that they reached out to you and looks like your portal is up and running feel free to let me know if you have any more questions.

**Comment by arnatusc** [comment]
Thanks for all the help.  Fix was super easy.  I thought I could only
select the MIME type from the list but I could actually enter the MIME I
needed into the Goddady list.

Just about to try and add the Apply with LinkedIn feature
