### ISSUE TITLE
Want to add 'Location' search alike 'Keyword Search' filter

### ISSUE THREAD

**Issue by sajtab** [bullhorn/career-portal#177]
INSERT SHORT DESCRIPTION EXPLAINING THE HIGH-LEVEL REASON FOR THE NEW ISSUE HERE.

## Current behavior

-

## Expected behavior

-

## Steps to replicate behavior

1.

## Screenshots

__Current__

__Expected__

Want to add 'Location' search alike 'Keyword Search' filter. Like below image

![image001 1](https://user-images.githubusercontent.com/22739179/35485231-a2e4bd22-0482-11e8-8d74-442ceea73b7a.png)

**Comment by bulbajackel** [comment]
Since City and state are two separate fields to search against, you will want to modify how the query is constructed for location when a location is selected. You are able to find where the location query is constructed in the [search service](https://github.com/bullhorn/career-portal/blob/cec4a679f63fad6a837480b33752a71c07f90928/src/app/services/search.service.js#L147).   You also will just want to ensure you are using the wildcard character (*) in your queries.

Feel free to let me know if you have any questions.

**Comment by sajtab** [comment]
We want to use city, Make searchable through city name

**Comment by sajtab** [comment]
Dear Team,

We have only scripts folder where 2 files allocated named app.js and vendor.js.

**Comment by sajtab** [comment]
This is want i make the change on code and make it searchable by city 

 location: function location(isSearch, fields) {
	                    if ('address(city)' !== fields) {
	                        if (_this3.searchParams.location.length > 0) {
	                            var delimiter = isSearch ? '"' : '\'';
	                            var equals = isSearch ? ':' : '=';

	                            var fragment = ' AND (';
	                            var first = true;

	                            for (var j = 0; j < _this3.searchParams.location.length; j++) {
	                                if (!first) {
	                                    fragment += ' OR ';
	                                } else {
	                                    first = false;
	                                }

	                                var location = _this3.searchParams.location[j];

	                                var city = isSearch ? location.split('|')[0] : location.split('|')[0].replace(/'/g, '\'\'');
	                                //var state = location.split('|')[1];

	                                **fragment += '(address.city' + equals + delimiter + city + delimiter + ')';**
	                            }

	                            return fragment + ')';
	                        }
	                    }

	                    return '';
	                },

**Comment by sajtab** [comment]
Dear Team, 

Below i changed the code and input field. Still not working. Could you rectify the the mistake.

fragment += '(address.city' + equals + delimiter + city + delimiter + ')';

<section><div class="keyword-search"><label for="location"><i class="bhi-search"></i></label><input class="search" type="text" data-ng-change="sidebar.searchOnDelay()" data-ng-model="sidebar.SearchService.searchParams.location" id="location" name="location"  data-ng-checked="sidebar.hasLocationFilter(location)" data-ng-click="sidebar.addOrRemoveLocation(location)" data-i18n-attr="{placeholder: \'sidebar.sidebarSearchPlaceholder\'}"></div></section>

**Comment by sajtab** [comment]
Dear Team,

Below i changed the code and input field. Still not working. Could you rectify the the mistake.

fragment += '(address.city' + equals + delimiter + city + delimiter + ')';


`<section><div class="keyword-search"><label for="location"><i class="bhi-search"></i></label><input class="search" type="text" data-ng-change="sidebar.searchOnDelay()" data-ng-model="sidebar.SearchService.searchParams.location" id="location" name="location"  data-ng-checked="sidebar.hasLocationFilter(location)" data-ng-click="sidebar.addOrRemoveLocation(location)" data-i18n-attr="{placeholder: \'sidebar.sidebarSearchPlaceholder\'}"></div></section>`

**Comment by bulbajackel** [comment]
Hi, you will want to ensure you are using [Lucene Query Syntax for your searches](https://lucene.apache.org/core/2_9_4/queryparsersyntax.html).  

You will want your query to look something like `(address.city:' + city +'*)'`.

**Comment by sajtab** [comment]
Dear Team,

Did you please provide the Query for City search?

Thanks

**Comment by charlesabarnes** [comment]
Hello, 

I provided an example of what your fragment may look like in my previous reply.  You may want to add additional logic to handle states.  If you need some documentation on the API you can find it [here](http://bullhorn.github.io/rest-api-docs/).
