### ISSUE TITLE
Mobile Optimize Career Portal 

### ISSUE THREAD

**Issue by talent1** [bullhorn/career-portal#181]
INSERT SHORT DESCRIPTION EXPLAINING THE HIGH-LEVEL REASON FOR THE NEW ISSUE HERE.

## Current behavior
Our career portal isn't mobile optimized, but the rest of the site is. I was wondering if there was a way to fix this so the job description doesn't get cut off on phones. We use WordPress. Thank you! 
-

## Expected behavior
Job postings will resize to so nothing gets cut off/ so people don't have to move back and worth to read the whole description 
- 

## Screenshots

__Current__

![career portal](https://user-images.githubusercontent.com/27704648/36318930-433a094a-130f-11e8-9e90-37c7414fcc30.jpg)

__Expected__

**Comment by charlesabarnes** [comment]
Hello,

This appears to be due to your career portal being in an iframe on the page, you may want to lower the resolution of the iframe or adjust your CSS rules to move your Iframe to the left some. 

Please let me know if you have any questions.

**Comment by pbearne** [comment]
That looks a WordPress if so look at using the Matador plugin [https://matadorjobs.com](https://matadorjobs.com) and not the Iframe plugin. As it integrates with your theme
