### ISSUE TITLE
Question on capturing Name/Email on website before going to Bullhorn

### ISSUE THREAD

**Issue by example7** [bullhorn/career-portal#182]
INSERT SHORT DESCRIPTION EXPLAINING THE HIGH-LEVEL REASON FOR THE NEW ISSUE HERE.

## Current behavior

Join Talent Pool/online profile – Bullhorn has an online profile capability as an add-on feature.   It’s a link we can place on our site to facilitate:  “join our talent pool.”   User would click and be taken to Access database hosted by Bullhorn where they could fill in profile info and attach a resume for consideration for future jobs.  My guess is that we would need to frame with the right copy / CTA on our career page (and also place within the bullhorn find a job page so if don’t see job you want can join the talent pool). 

## Expected behavior

Question is whether we should ask the jobseeker to provide name and email address before they are taken to the bullhorn online profile.  Hubspot best practices says to  capture name and email address so we can recognize them when they come back to the site and also respond to emails and other behavior…  But don’t want to put too many doors in front of the user… One way to do it would be to design copy and call to action to join talent pool with a link.  Link brings up a hubspot form to capture name and email address then sends them to bullhorn application to fill out online profile.  The user will  register with email and set up a password to manage their online profile…

**Comment by charlesabarnes** [comment]
Hello, 

It seems like you're asking what modifications you should make to the portal to accommodate the candidate portal that you have that already collects the candidate info.
What I would suggest is removing the fields for name, email, and phone and instead when you link the portal, put the information in the URL as URL parameters, then, when the resume is uploaded you can grab the information and submit it to Bullhorn with the resume.  When you do that, Bullhorn will handle associating that email with the existing candidate. 

As far as using the URL parameters, we actually do this in the [apply service](https://github.com/bullhorn/career-portal/blob/master/src/app/services/apply.service.js#L72) for getting the applicant source.

Please let me know if you have any questions.
