### ISSUE TITLE
Whitespace in filters

### ISSUE THREAD

**Issue by platypusjones** [bullhorn/career-portal#184]
Bullhorn dashboard may have some issues with sanitizing user entered data. We encountered a case today affecting filter functionality should this whitespace be parsed into the career portal. 

In my particular case, it was affecting the job location filters. Should whitespace be added to either city or state, the results won't match anything and the user sees the no matching jobs text. I'm assuming this may be a problem for other filters as well, but the pipe-separated string comes through with whitespace included. So, for example, you would find `Boston |Massachusetts` instead of the expected `Boston|Massachusetts`. 

This should be fairly easy to replicate as I was able to save whitespace back into a field via the job post editing screen on the backend. A current stopgap solution is to use `trim()`, but that's not very elegant. This should probably ultimately be fixed in the BH platform so that users can't save trailing whitespace, but for time being if this happens inadvertently it's a rather big problem since it stops filtering from working at all.

**Comment by charlesabarnes** [comment]
The filter strategy is a bit different in Career Portal V3.  Can you check that out and see if this is the same issue?
