### ISSUE TITLE
Logo/URL instead of Company Name

### ISSUE THREAD

**Issue by hutch2080** [bullhorn/career-portal#186]
Hi, not sure if this is where to ask questions, but I've been asked to add a linked logo to our career-portal page instead of the standard companyName.  Is this possible OOTB, or would it require customization?  I've seen it done on other versions (example below), but don't see any documentation on how to do it.

Here's an example: http://dietitiansondemand.com/careerportal/#/jobs

Thanks!

**Comment by charlesabarnes** [comment]
Hello, 

A customization such as that would require a modification to the [header.html](https://github.com/bullhorn/career-portal/blob/master/src/app/header/header.html#L11) file.   

You are able to use standard `img` and `a` tags for this

**Comment by hutch2080** [comment]
Thanks much!
