### ISSUE TITLE
Career Portal not showing on page

### ISSUE THREAD

**Issue by RichardCore37** [bullhorn/career-portal#187]
Career Portal not showing on page

Hi, I'm new to github so apologies if I'm not following the correct conventions.

I've been trying to test Bullhorn's career portal on my Adobe Business Catalyst site. I've followed all the guidelines on github, downloaded the code, included the correct info from Bullhorn, transferred it via SFTP to my site in a newly-created folder 'careerportal'. However, when I go to www.core-asset.co.uk/careerportal nothing shows. 

Am I missing something really obvious?

**Comment by charlesabarnes** [comment]
Hello Richard, 

I am not 100% familiar with Adobe Business Catalyst.  Is it capable of hosting additional static site files?  If index.html is in the careerportal directory there may need to be a configuration change on the web server to serve that file.

**Comment by RichardCore37** [comment]
Hi Charles, thanks for the swift response. I couldn't find any index.html in the careerportal directory?

**Comment by charlesabarnes** [comment]
The files you are supposed to upload to the webserver is found on the [release](https://github.com/bullhorn/career-portal/releases/tag/v2.5.1) page.  in the root directory of the zip file the index.html file will be there which is used by the browser to run the portal.   All of the files from the release zip file need to be uploaded.

**Comment by RichardCore37** [comment]
Hmm, I thought I had done that. I will double check. Thank you Charles.

**Comment by RichardCore37** [comment]
Right, I've redone the transfer. And although the index file shows up in FileZilla as being transferred, it doesn't seem to be on the backend of my site?

**Comment by RichardCore37** [comment]
I've made some progress, Charles. It now shows on http://www.core-asset.co.uk/careerportal/index.html I just need to work out why it's now showing any jobs!

**Comment by charlesabarnes** [comment]
The swimlane on your site needs to only say "23"  not "sl23" it seems.

**Comment by RichardCore37** [comment]
Changed. It now shows the following message "Oh No! Looks like there are no jobs matching the criteria." I'm taking this as progress!

**Comment by RichardCore37** [comment]
Still no luck. Do you think it's because I need to actively publish jobs from BH, i.e. the portal won't automatically scrape all live vacancies on BH?

**Comment by MDDesignstl** [comment]
If you are seeing the "Oh No! Looks like there are no jobs matching the criteria." message then your portal is working. You will need to Publish jobs from the within the app in order for them to show on the portal. The jobs will need to have a publishing status of "publish-approved."

**Comment by RichardCore37** [comment]
Thanks. Currently liaising with BH over this particularly aspect, so hopefully just about there!

**Comment by RichardCore37** [comment]
Now working. Thank you to @charlesabarnes and @MDDesignstl for your help!
