### ISSUE TITLE
Apply with Linked In not working - updated the app.json file and uploaded, but it's not showing on Career Portal.  Can anyone help?

### ISSUE THREAD

**Issue by SherpaGreg** [bullhorn/career-portal#188]
INSERT SHORT DESCRIPTION EXPLAINING THE HIGH-LEVEL REASON FOR THE NEW ISSUE HERE.

## Current behavior

-

## Expected behavior

-

## Steps to replicate behavior

1.

## Screenshots

__Current__

__Expected__

**Comment by charlesabarnes** [comment]
Hello,

I'm not sure if you're still editing the post, but for the apply with LinkedIn button to appear on your career portal, you need to input the LinkedIn client id into your app.json file.   You can find steps to obtain the client Id [here](https://github.com/bullhorn/career-portal/wiki/Downloading-and-Configuring).

**Comment by SherpaGreg** [comment]
I followed those instructions, but when I moved the new .json with the Client ID included (the one generated from the LI Developer site) into GoDaddy nothing changed on our career portal.  Is there something else that has to be turned on?  Where would I see the Apply with Linked In button?

**Comment by charlesabarnes** [comment]
On the career portal the apply with LinkedIn button appears on the job detail above the normal apply button.  Is the button present there?

**Comment by SherpaGreg** [comment]
It isn’t.  I just downloaded and configured the newest version of the career portal this morning and used the LI ID they generated yesterday.  I still just have the normal apply button – no linked in.

**Comment by SherpaGreg** [comment]
Our career portal is at www.sherpallc.com/careerportal<http://www.sherpallc.com/careerportal>

**Comment by charlesabarnes** [comment]
I see the apply with LinkedIn button on the job detail page.   It appears to work if you access the site at www.sherpallc.com.  If you access it at sherpallc.com the button appears but when you click it it doesn't open the LinkedIn popup.  You will want to add sherpallc.com to the javascript domains on developer.linkedin.com.

![image](https://user-images.githubusercontent.com/4327754/38425466-8df62528-3979-11e8-9f8a-677ee263f2d3.png)

**Comment by SherpaGreg** [comment]
I’m on Chrome – does that matter?

On the LI Developer JavaScript section, I have http://www.sherpallc.com/careerportal as the only Valid SDK Domain.  Are you saying I should add sherpallc.com as well?

**Comment by charlesabarnes** [comment]
I am on Chrome as well, you may need to clear your Browser's cache.   Also yes, you should add sherpallc.com as well.

**Comment by SherpaGreg** [comment]
You don’t happen to know how to get the Apply with Linked In option to appear on mobile do you?

**Comment by charlesabarnes** [comment]
In IOS Safari, that feature is not available due to how the browser handles cross origin requests.  If it was available, it would just produce an error.
