### ISSUE TITLE
Addition of Agree to Terms and Conditions checkbox in Apply PopUp (GDPR Requirement)

### ISSUE THREAD

**Issue by Bluebilities** [bullhorn/career-portal#189]
Is there an option for adding checkboxes according to GDPR laws that candidates need to read and agree to our terms and conditions with a link to it.
Is it possible to add this to the popup
![popup](https://user-images.githubusercontent.com/38135409/38425974-a2c4243c-39b5-11e8-910b-eaba48fb871e.PNG)

Is there any alternate ways that Bullhorn can help German companies be GDPR law compliant on this regard?

**Comment by mpaus18** [comment]
This is important for us as well! 

Until the Career Portal has a checkbox to accept our Privacy Policy we can't use the portal for legal reasons. Please be aware of two requirements for the check box to be GDPR compliant:

1) It needs to link to our Privacy Policy (admin needs to be able to add a custom link to the check box description text - or configure the text freely; latter is preferred)
2) It cannot be pre-checked

If you would add this functionality in the near future you would help us a lot!

**Comment by pbearne** [comment]
Hi All

If you are using WordPress or can use. [Matador Jobs](https://matadorjobs.com/) has this as a standard feature. 

Paul

**Comment by mpaus18** [comment]
Hi Paul,

thanks for following up! Matador is rather expensive, and adding this check box functionality is pretty important on an international level for privacy policy compliance. If you would include it in a future roll-out you'd improve our Bullhorn experience significantly.

**Comment by charlesabarnes** [comment]
Hello, 

The customization made may have resulted in an invalid JSON file.  To check what is wrong you can use a json validator website such as this: https://jsonformatter.curiousconcept.com

As far as the feature, I am currently working on a simple way to implement this as well as creating a simple privacy policy tooltip/excerpt.  I will be updating github on the over the next week.

**Comment by mpaus18** [comment]
Hi Charles,

thanks a lot for working on it! Much appreciated :)!
