### ISSUE TITLE
Remove "Powered by Bullhorn" if CSS is modified

### ISSUE THREAD

**Issue by ahuberbullhorn** [bullhorn/career-portal#19]
If the Career Portal CSS is modified, we should remove the "Powered by Bullhorn" stamp found on the left hand pane.

![image](https://cloud.githubusercontent.com/assets/13653329/11035798/2a102be0-86ba-11e5-8bee-cb65b576977c.png)

**Comment by jgodi** [comment]
I am wondering how we can detect if the CSS has been changed. @ahuberbullhorn, do we even need to have this "Powered by Bullhorn" label at all?

**Comment by ahuberbullhorn** [comment]
@bryanjroy Maybe you have some suggestions for this.

**Comment by tazplay** [comment]
Edit this to your styles/app-XXXXXXXXXX.css file -

this:
```
*aside>section>section.credits {
	margin-top: 4em;
	color: #797c7e;
}
```

to this:
```
aside>section>section.credits {
	margin-top: 4em;
	color: #797c7e;
	display:none;
}
```

**Comment by Powerpersonnel** [comment]
Ive tried what tazplay suggested but it did not work. is there any other way ?

**Comment by bvkimball** [comment]
`.credits {
    display:none !important;
}`

**Comment by Powerpersonnel** [comment]
i've done that too but the powered by bullhorn icon is still there. :(

**Comment by Powerpersonnel** [comment]
update. thanks bvkimball for the tips it works perfectly. I have another request. would you please show me how to replace the company name with an img or our company title. thanks

**Comment by bvkimball** [comment]
Yes can you please open that as a new issue for tracking purposes?

**Comment by mmccarthycreative** [comment]
I have added this line to the app.css file but the Bullhorn logo/credits tag is still showing?

**Comment by bvkimball** [comment]
the app.css file will get overridden everytime you build.  You might need to update this in: https://github.com/bullhorn/career-portal/blob/master/src/app/sidebar/sidebar.scss

You can also just remove the section in the html
