### ISSUE TITLE
Mobile CSS & LinkedIn "Apply Now" Function

### ISSUE THREAD

**Issue by paulclix** [bullhorn/career-portal#191]
Couple aspects to this question:

Mobile CSS
Is there a stylesheet associated with the mobile styling of the Wordpress bullhorn integration? See attached screenshot. I was able to edit theme's css to hide overflow, but I'd like to know where the file is located to update how the widgets respond to mobile. 

![mobile-screenshot](https://user-images.githubusercontent.com/37589989/38698617-48cac9ea-3e5b-11e8-9265-eadf4033fe50.jpg)

LinkedIn "Apply Now" Function
When I click "Apply Now," a notification then prompts me to retry which doesn't work. I disabled pop-ups in chrome and firefox then retried with no luck. (Quick Video: https://cl.ly/qq6Z).

**Comment by charlesabarnes** [comment]
Hey Paul,

That information for the plugin can be found in your plugins directory on your web host. There is a config.css file and that is where the styles for the plugin are stored.   

For the apply with LinkedIn functionality you most likely need to add the JavaScript API domain on developer.linkedin.com.

**Comment by paulclix** [comment]
Thanks Charles! I'll work off of your response and reply with an update!
