### ISSUE TITLE
Branding Fields to Sort 

### ISSUE THREAD

**Issue by trgriffith** [bullhorn/career-portal#194]
INSERT SHORT DESCRIPTION EXPLAINING THE HIGH-LEVEL REASON FOR THE NEW ISSUE HERE.

## Current behavior

-

## Expected behavior

-

## Steps to replicate behavior

1.

## Screenshots

__Current__

__Expected__

What are the field names for Branding?  I have two different branded portals and need to ensure jobs on one don't get posted to the other.  Right now all jobs are on both portals.

Also I assume that it would be put in the search.service.js file?  Any examples of what code to use?  While comfortable with HTML and most PHP, the rest is new to me.  So any help or code examples would be greatly appreciated.  I'm a one man shop here and time to go and learn all this is not a luxury I really have these days.

**Comment by charlesabarnes** [comment]
Hello, 
The field to determine brand is not exposed via the API.  You are able to use most other fields, however if it is not currently available via the API, you will need to contact our Support team to get the field exposed.  

For examples I suggest checking out #137, #165, and #177

**Comment by charlesabarnes** [comment]
My apologies, I was a bit unclear in my first post.  You are not able to use the brand field to filter.  That field is only used within Bullhorn for sharing to social media sites. I suggest utilizing a different field such as a `customText` field so a dropdown can be added to separate the two different portals.  

I am noting down the feature request however on my end for exposing that field in the API because that would be useful in this use case.  

Please let me know if you have any more questions.

**Comment by trgriffith** [comment]
That makes no sense what so ever. How is it used for social media? There
are no settings beyond picking one for social media however, when you set
up the brand you give it a different url for the different oscp and the
documentaion alludes to that being a factor.

It seems like there is a major disconnect here.

**Comment by trgriffith** [comment]
Right, exactly.  That's what I thought.  And the example you provided is
exactly what we want.  So for instance I have 2 jobs published one to the
Rhino instance and one to the HPlus instance.  However, both jobs are
showing up on both urls (http://www.rhinomedical.com/jobs &
https://www.hospitalistsplus.com/jobs).

I don't understand why a field would be created and then not used at all
and then why the documentation doesn't say that in order to actually do
what you obviously intended on doing that you need to create another field
and then use that to complete the action.  Either that field needs to be
opened up and used or the documentation needs to be changed to reflect
what's true and code examples given.

So, I take a custom field and call it, Publish To and put my two options
Rhino | HPLus as the options.  How do I add that filter to the OSCP?  I've
mentioned before I'm not a Javascript guy, I'm pretty good with HTML & some
PHP, but Javascript and JSON are not my thing.

**Comment by charlesabarnes** [comment]
Hello, I looked for the most straightforward way to address this and it is probably easiest to just hard-code this into the search service file similar to the work done in #175.  We added a criteria for a single field that can be used as a template to base your changes on.  

Please let me know if you have any more questions.

**Comment by charlesabarnes** [comment]
You will want it to be `':siteA' : '=siteA'` for the query as it doesn't need to be boolean.
