### ISSUE TITLE
State and not City, State

### ISSUE THREAD

**Issue by trgriffith** [bullhorn/career-portal#195]
I know it's been covered and amongst you developers I'm sure you understand what you all are talking about.  However for someone that's got to get it done regardless, I have a few more questions to get me through it.

I've gone through all the files where city lives and removed it.  Removed all the code where city and state are joined and made it so only state is used to sort, etc.  It looks right.  But when I go to filter, I get no results.  Pointers & code examples are highly appreciated, as that's the only way I am going to be able to learn what I need to in the time-frame I have.

http://www.rhinomedical.com/jobs/#/jobs

**Comment by charlesabarnes** [comment]
It seems like the city is returning undefined whenever the checkbox is clicked. I also see that it i attempting to filter on the text 'address(state)'  There are some changes you may need to make in the sidebar controller as well as the search service. 

I suggest checking out some of the previous issues to get some footing in this. The issues I would suggest checking out are #46 #130

**Comment by trgriffith** [comment]
OK, I found a few places that were still calling city and removed them, rebuilt it and it's still giving me a problem.  I don't see anywhere else.  What are you using to see what it's attempting to filter on?  Chrome developer tools?  What part if so.  Teach me to troubleshoot this a little better and I'm sure I can figure it out.

**Comment by charlesabarnes** [comment]
I am looking at the parameters in the requests URLs.  You can find this in the [network tab](https://developers.google.com/web/tools/chrome-devtools/network-performance/) of Chrome developer tools.
