### ISSUE TITLE
Multiple Employments Types Display as one

### ISSUE THREAD

**Issue by trgriffith** [bullhorn/career-portal#196]
I need for 3 of the multiple employment types we use in Bullhorn to be displayed as a singular type in the portal.  

## Current behavior

Locums-Direct
Locums-VMS/MSP
Locums-Group
Perm

Those are our types and they all are needed to filter information to the team in the CRM.

## Expected behavior

On career portal it needs to display as:

Locum Tenens (All 3 Locums categories are lumped together since candidates don't need to know what type of Locums job it is)
Permanent

Please keep in mind that I am not a full time developer like most of you.  I'm an HTML/PHP guy who is trying to quickly work my way through this so code examples or references to where I can learn more are greatly appreciated.

**Comment by charlesabarnes** [comment]
This one is a bit tricky and the solution is possibly not ideal to handle fully on the frontend.  What I suggest is utilizing the "published category" option on the job to group everything in one group for Locums as the Published Category and the normal category fields are separate.

**Comment by trgriffith** [comment]
That won't work since we need that field for what it's intended for.  We need a third sidebar selection criteria.  I can use a customText field and make it a radio for the two types of jobs (Locums/Perm).  I'll see if I can figure out how Published Category is used and try to re-create it using that customText field.

**Comment by charlesabarnes** [comment]
The public category field is different than the published category field.  This allows the jobs to fall under one category in the career portal to not confuse applicants, while keeping your jobs in specific categories to make it easier to filter and search.  

Below I am providing some screenshots of the separate fields as it will achieve the functionality you're looking for without a code modification.
# On the edit page
![image](https://user-images.githubusercontent.com/4327754/40070481-ce13cc86-5833-11e8-9b21-00f3b0ec0bad.png)

# On the publish page
![image](https://user-images.githubusercontent.com/4327754/40070540-fb923a1c-5833-11e8-8578-e6d73b73ea2e.png)

**Comment by charlesabarnes** [comment]
My apologies, I misunderstood.  #46 and #138 are two examples of people attempting to utilize additional or customized filters on their portal.  I suggest checking out the two threads for this.  Most of the work for this will be done in the search service and the sidebar controller.
