### ISSUE TITLE
Add view style to app.json

### ISSUE THREAD

**Issue by ahuberbullhorn** [bullhorn/career-portal#20]
We should add the view style (grid or list) to the app.json so that companies can easily change this preference. We should default this variable to grid-view.

**Comment by jgodi** [comment]
@ahuberbullhorn Are you referring to the default view when you initially load the application? There are the buttons to switch from list/grid at the top.

**Comment by ahuberbullhorn** [comment]
@jgodi Correct. Currently we default to the list, but we should default to the grid. Per feedback, this seems to be a more desirable viewing state. However, we should add this into the app.json file to allow for companies to easily change this.

**Comment by jeremy-dobler** [comment]
Beginning work on allowing configuration of default view. Still need to add unit tests
[feature branch](https://github.com/bullhorn/career-portal/tree/f/defaultView)

**Comment by jeremy-dobler** [comment]
Merge Request pending
