### ISSUE TITLE
EEOC help tooltip does not display Company name

### ISSUE THREAD

**Issue by MDDesignstl** [bullhorn/career-portal#201]
# EEOC help tooltip does not display Company name

## Current behavior

When clicking on the help tooltip for certain EEOC fields, the company name does not bind properly except for the first instance. The 2nd or greater instance(s) just display {companyName}

## Expected behavior

Company Name should display properly in the tooltip in all cases

## Steps to replicate behavior

1. Go to a EEOC enabled portal
2. Enter a Job
3. Click Apply
4. Click the help icon for the veteran status field.
5. Note that the Company name displays correctly the first time, but not the 2nd and 3rd.

![image 1](https://user-images.githubusercontent.com/21197268/40695989-52fd2586-6389-11e8-9c63-1b042cb9ea61.png)

**Comment by jmccardle77** [comment]
How were you able to create that form for your EEOC? Our webmaster is not able to do this and I'm trying to figure out what needs to be done so we can report off of the finished forms?

**Comment by charlesabarnes** [comment]
@jmccardle77 You mean adding the EEOC fields?  That is available by setting the eeoc properties in your `app.json` file to true.

**Comment by jmccardle77** [comment]
How do I access that?


Very Respectfully,

Jamie C.E. McCardle
Marketing Manager
P 720-355-1285
F 877-228-4392

**Comment by charlesabarnes** [comment]
In the files downloaded for the portal, there is a file in there with the name of 'app' and the extension of 'json'

**Comment by charlesabarnes** [comment]
Fixed with #216
