### ISSUE TITLE
Mail

### ISSUE THREAD

**Issue by Lauravanbrunschot** [bullhorn/career-portal#204]
INSERT SHORT DESCRIPTION EXPLAINING THE HIGH-LEVEL REASON FOR THE NEW ISSUE HERE.

## Current behavior
When we click on the share button and then on the Mail button in a vacancy, we can not send the vacancy to an email. Besides that is not possible to print the vacancy, if we would like to print the whole vacancy it is only possible to print one page. 

## Expected behavior

- We would like to print the whole vacancy and share the vacancy by email. 

## Steps to replicate behavior

1.

## Screenshots

__Current__

__Expected__

**Comment by charlesabarnes** [comment]
Hello @Lauravanbrunschot ,

The email share button uses your default mailto provider set within your computer's settings.  Once those are configured you should be able to share the job link as expected.   

As far as printing, it should print the whole webpage.  Are there any steps you can provide to reproduce this issue?
