### ISSUE TITLE
Font path is wrong in /styles/vendor.css

### ISSUE THREAD

**Issue by twickstrom** [bullhorn/career-portal#206]
## Current behavior
In the network panel I noticed many 404 errors while loading the robots fonts.

Example of one of the non-face rules:
```
@font-face {
    font-family: 'Roboto';
    src: url('../../fonts/roboto/Roboto-Thin.eot');
    src: local('Roboto Thin'), local('Roboto-Thin'), url('../fonts/roboto/Roboto-Thin.eot?#iefix') format('embedded-opentype'), url('../fonts/roboto/Roboto-Thin.woff2') format('woff2'), url('../fonts/roboto/Roboto-Thin.woff') format('woff'), url('../fonts/roboto/Roboto-Thin.ttf') format('truetype'), url('../fonts/roboto/Roboto-Thin.svg#Roboto') format('svg');
    font-weight: 100;
    font-style: normal;
}
```

## Expected behavior
Not to have 404 errors. If the path was correct this wouldn't be an issue.

The font folder is only up one level, not two:

```
@font-face {
    font-family: 'Roboto';
    src: url('../fonts/roboto/Roboto-Thin.eot');
    src: local('Roboto Thin'), local('Roboto-Thin'), url('../fonts/roboto/Roboto-Thin.eot?#iefix') format('embedded-opentype'), url('../fonts/roboto/Roboto-Thin.woff2') format('woff2'), url('../fonts/roboto/Roboto-Thin.woff') format('woff'), url('../fonts/roboto/Roboto-Thin.ttf') format('truetype'), url('../fonts/roboto/Roboto-Thin.svg#Roboto') format('svg');
    font-weight: 100;
    font-style: normal;
}
```

## Steps to replicate behavior

1. Fresh install in a subdomain or subfolder. Navigate to the site and watch the network panel.

## Screenshots

__Current__
<img width="1061" alt="screen shot 2018-06-15 at 5 20 14 pm" src="https://user-images.githubusercontent.com/775346/41491694-68157650-70c0-11e8-97d2-b1eab852386c.png">

__Expected__
<img width="1069" alt="screen shot 2018-06-15 at 5 18 58 pm" src="https://user-images.githubusercontent.com/775346/41491672-47373428-70c0-11e8-9b05-5d66a90ab467.png">

**Comment by charlesabarnes** [comment]
This has been resolved as of release v2.6.0 https://github.com/bullhorn/career-portal/releases/tag/v2.6.0
