### ISSUE TITLE
Custom fields

### ISSUE THREAD

**Issue by moosewebdev** [bullhorn/career-portal#207]
Im very new to this thansk for your help,
My client has Job title (job.title) set to be an internal name not to be shown. They have created a custom field instead called customTextBlock5 as the title of the job. How do i access this custom field.
i am tring job.customTextBlock5

## Current behavior

-

## Expected behavior

-

## Steps to replicate behavior

1.

## Screenshots

__Current__

__Expected__

**Comment by charlesabarnes** [comment]
Hey @moosewebdev,  

You're on the right track.  You will need to do 3 things:  two code modifications and the other is to contact Bullhorn support.  

First you will need to contact Bullhorn Support to make that custom field accessible.  This something that only can be done on our side.

Once that is done, you will need to add that field to what the [field getter](https://github.com/bullhorn/career-portal/blob/master/src/app/services/search.service.js#L18) returns in search service

Finally, you will want to add `job.customTextBlock5` in the interpolated sections where you will want this job title to display.

Please let me know if you have any questions

**Comment by moosewebdev** [comment]
Thanks for your reply.

So the field getter would be something like

SearchService._.fields || (SearchService._.fields = 'id,title,publishedCategory(id,name),customTextBlock5,....

Then I can use job.customTextBlock5 in the appropriate section to be displayed.

I've started a ticket with bullhorn through my client. To get them to add the fields. There are a couple others I'll need to include also.

**Comment by charlesabarnes** [comment]
Correct
