### ISSUE TITLE
Assigning user when an applicant applies in the OSCP

### ISSUE THREAD

**Issue by jasonziolo** [bullhorn/career-portal#209]
We are using the 2 separate instances of the OSCP that point to the same BullHorn instance.  Each instance is for a different site we have configured.  The OSCP uses this endpoint to apply to the job:

https://public-rest5.bullhornstaffing.com/rest-services/{swimlane}/apply/{job_id}/raw

We'd like the job application to be assigned to a different user depending on what site the request comes from.  The sites are at two different URL's.  Is there a way to specify what user to assign the application to in this endpoint?  We've been speaking with customer support and they say it is possible but we need to ask in this forum to get help.

Thank you!

## Current behavior

Applied jobs don't get assigned to the correct user.

## Expected behavior

Based on the site they're applying from, a different user should be assigned.

**Comment by charlesabarnes** [comment]
Hey @jasonziolo ,

That is possible, however you will need to change your career portal from using the public-api endpoints to our normal rest api.  This would involve adding backend files for authorization. 

Instead, I suggest modifying your portal's code to send with the candidate payload a source of which portal the application has come from.  That way you are still operating within the bounds of the public API.

**Comment by jasonziolo** [comment]
For the first option, this would require a drastic overhaul of your out of the box OSCP, true?

For the second option, is there any documentation for this API endpoint to do this (this endpoint doesn't show up anywhere in your documentation I can find)?  Also, I believe that will require additional configuration inside of BullHorn to read that payload and assign it to the correct user.  Do you agree?

Thanks for the prompt reply.

**Comment by charlesabarnes** [comment]
The first option would require a major out of the box career portal change, correct.

The latter option, there isn't much documentation on the public api as there isn't much variability in behavior.   

There is not any additional configuration required to read the source parameter from the payload.

**Comment by charlesabarnes** [comment]
I just reread your message,

This option would not attribute to a specific user.  This option would only add the source to the user record inside Bullhorn.

**Comment by jasonziolo** [comment]
Can you provide more details on the latter option?  From the source code, I see we can specify name, email, phone, gender, ethnicity, veteran, disability and title.  I'm not sure how to use these fields to specify which user to assign the application to.  Is there ANY documentation on this web service I can reference?  If not, can you provide an example of how to send in the information to specify which user to assign this to or what portal it came from?

**Comment by charlesabarnes** [comment]
https://github.com/bullhorn/career-portal/blob/master/src/app/services/apply.service.js#L74

We already optionally add a source if a parameter is in the URL.  instead of optionally adding the source option, you can just hardcode the source to the portal of choice. 

I would also like to reiterate: This is not going to assign ownership within Bullhorn to a recruiter. This is only going to set the source field, which you can then filter by the source of each candidate.

**Comment by jasonziolo** [comment]
Thank you, I see source now.  One final question, is there a way assign the issue to the right person in BullHorn based on this source by adding a configuration in BullHorn?

**Comment by charlesabarnes** [comment]
There is not a way to do this within Bullhorn's settings.

**Comment by jasonziolo** [comment]
Thank you for your prompt replies, I think I have what I need for now.

**Comment by jasonziolo** [comment]
Note to other developers:

I think this definitively answers the fact there isn't any documentation or ability to extend the web service at 

https://public-rest5.bullhornstaffing.com/rest-services/{swimlane}/apply/{job_id}/raw. 

Hopefully that saves you the time I spent scouring their documentation for more details.  =)

**Comment by charlesabarnes** [comment]
Heya,

The url actually is https://public-rest{swimlane}.bullhornstaffing.com/rest-services/{corpToken}/apply/{job_id}/raw.
