### ISSUE TITLE
How is this integrated into indeed?

### ISSUE THREAD

**Issue by moosewebdev** [bullhorn/career-portal#210]
How is indeed integrated? My client is wondering how indeed will scrape the jobs detail section without actually having its own page.

Is there a way to integrate with indeed?

## Current behavior

-

## Expected behavior

-

## Steps to replicate behavior

1.

## Screenshots

__Current__

__Expected__

**Comment by charlesabarnes** [comment]
Hey @moosewebdev,

That's all taken care of on our end.   Please contact Bullhorn Support to get that set up.
