### ISSUE TITLE
Url parameter and apply filter

### ISSUE THREAD

**Issue by moosewebdev** [bullhorn/career-portal#211]
I have the portal setup and working on one page showing all results. My client has asked if we can have a second page setup where employment type of Permanent is already checked and filtered but still give the ability to check Contract. 

Is this possible with a url parameter?

## Current behavior

-

## Expected behavior

-

## Steps to replicate behavior

1.

## Screenshots

__Current__

__Expected__

**Comment by charlesabarnes** [comment]
That is possible by checking `window.location.href.indexOf('employmentType=')`.  This would require modifications to the sidebar controller to check the parameter and then it would want to check that box.
