### ISSUE TITLE
Question regarding REST API and Bullhorn career portal

### ISSUE THREAD

**Issue by SrujithPoondla** [bullhorn/career-portal#212]
Hi,
I am looking for parsing the resume and found bullhorn REST API might be useful. Do I need to host the bullhorn career portal to access the REST API for resume parsing? or bullhorn career portal is for showing the list of jobs? I couldn't find the discussion related to this topic, I figured that we need an authorization token for parsing the resume but do we need the instance as well?
Thanks!

**Comment by charlesabarnes** [comment]
Hey @SrujithPoondla 

The career portal is a job board that allows candidates to apply to jobs and takes care of resume parsing and job listing all in one.  

For getting credentials for the API, you will want to reach out to Bullhorn Support.

I suggest checking out some of our API docs http://bullhorn.github.io/docs/
