### ISSUE TITLE
Google Jobs integration

### ISSUE THREAD

**Issue by moosewebdev** [bullhorn/career-portal#214]
INSERT SHORT DESCRIPTION EXPLAINING THE HIGH-LEVEL REASON FOR THE NEW ISSUE HERE.
Google has released their jobs integration. Has this been integrated in to bullhorn?

https://developers.google.com/search/docs/data-types/job-posting

## Current behavior

-

## Expected behavior

-

## Steps to replicate behavior

1.

## Screenshots

__Current__

__Expected__

**Comment by pbearne** [comment]
Hi Moosewebdev

This has not been added to the career portal. I believe it may be on the roadmap but not scheduled.
If this a real problem for you and you are using WordPress the Matador Plugin does provide the structured data needed by Google.

Paul

**Comment by charlesabarnes** [comment]
This has not been added to the Bullhorn Career Portal as of yet.  We do have an open issue keeping track of progress of this request. The issue is #143
