### ISSUE TITLE
Windows edge issue

### ISSUE THREAD

**Issue by moosewebdev** [bullhorn/career-portal#215]
In chrome everything works fine but in Windows Edge i am receiving a windows defender error Here is the page http://tfdl.com/opportunities/

Also in internet explorer i am receiving a syntax error here.
employTypes: (isSearch, fields) => {
                    if ('employType' !== fields) {
                        if (this.searchParams.employType.length > 0) {
                             var delimiter = isSearch ? '"' : '\'';
                            let equals = isSearch ? ':' : '=';

                            let fragment = ' AND (';
                            let first = true;

                            for (let i = 0; i < this.searchParams.employType.length; i++) {
                                if (!first) {
                                    fragment += ' OR ';
                                } else {
                                    first = false;
                                }
                                
                                fragment += 'employmentType' + equals + delimiter + _this3.searchParams.employType[i] + delimiter;
                            }

                            return fragment + ')';
                        }
                    }

                    return '';
                },
## Current behavior

-

## Expected behavior

-

## Steps to replicate behavior

1.

## Screenshots

__Current__

__Expected__

**Comment by charlesabarnes** [comment]
I am unable to reproduce the error in Microsoft edge.  I tested this on multiple machines. Can you provide more details?

**Comment by moosewebdev** [comment]
![tfdlcap](https://user-images.githubusercontent.com/17207170/42948339-45a733a0-8b3d-11e8-92bf-f6e97198c640.PNG)


here is a screen shot of MS Edge

**Comment by charlesabarnes** [comment]
Well, I ended up being able to reproduce this issue on another PC that I have locked down. 
I suggest doing two things, the first of which is getting the site secured with SSL.   That seems like that is the main motivator for that message.  Chrome is going to do the same thing to other websites not certified with a SSL certificate.

Next, use that report button to report the website as safe. 

Unfortunately, when I visit your website on my other pc, not even just the opportunities page I am getting the error even outside of the career portal.   I would suggest acting on this as soon as possible as it may detract any potential website users from using your site.

**Comment by moosewebdev** [comment]
thanks, Ill get my client to get a SSL certificate

**Comment by moosewebdev** [comment]
The warning is now gone. But in Internet explorer I am still getting a syntax error. In Chrome and edge all is good.

**Comment by moosewebdev** [comment]
![tfdlerror](https://user-images.githubusercontent.com/17207170/43005052-a8e404c6-8bff-11e8-9967-7d0acb45a281.PNG)

**Comment by charlesabarnes** [comment]
This is because of your use of arrow functions for employTypes.   If you refactor the bit it points to it will will work.

Sources:
https://stackoverflow.com/questions/40216015/arrow-function-not-working-in-ie-why
https://caniuse.com/#feat=arrow-functions
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions

**Comment by moosewebdev** [comment]
Sorry i thought i could fix this. Now im just getting more errors. What do you mean by refactor what it is pointing to?

**Comment by charlesabarnes** [comment]
When you click the link to what line the error it occurs on it points to the part the error happens.

You can pretty much ctrl + f for  places an arrow function is used ( `=>` ) and just use the nomal  `function functionName() {}` format

**Comment by moosewebdev** [comment]
I updated like this. But am getting an error
![tfdlerror2](https://user-images.githubusercontent.com/17207170/43016656-86cb2ee2-8c21-11e8-9170-55bff22bcddc.PNG)


`employTypes: function employType(isSearch, fields) {
                    if ('employType' !== fields) {
                        if (this.searchParams.employType.length > 0) {
                             var delimiter = isSearch ? '"' : '\'';
                            let equals = isSearch ? ':' : '=';

                            let fragment = ' AND (';
                            let first = true;

                            for (let i = 0; i < this.searchParams.employType.length; i++) {
                                if (!first) {
                                    fragment += ' OR ';
                                } else {
                                    first = false;
                                }
                                
                                fragment += 'employmentType' + equals + delimiter + _this3.searchParams.employType[i] + delimiter;
                            }

                            return fragment + ')';
                        }
                    }`
