### ISSUE TITLE
Capture signature and date for EEOC fields

### ISSUE THREAD

**Issue by billy-bacon** [bullhorn/career-portal#219]
Enabling the EEOC form fields on the application form is fairly straightforward but the Voluntary Self-Identification of Disability section that allows a candidate to indicate if they have a disability or not does not provide a form field for their signature as well as a date it was entered/signed. This is in form CC-305. I've attached a screenshot of the normal PDF file that needs to be replicated on the application form of the career portal.

## Current behavior

It's not clear how to achieve this within the current system and have the additional form fields passed through to the API and end up in the Bullhorn backend system

## Expected behavior

Enabling the EEOC fields for the career portal application form provides additional fields for the candidates name/signature and date in which they are applying for the job.

## Steps to replicate behavior

1.) Click the Apply for a job button on the career portal
2.) Have form fields to capture the candidates name/signature as well as today's date.

## Screenshots
<img width="787" alt="voluntary_self-identification_of_disability_form_cc-305" src="https://user-images.githubusercontent.com/1653971/44153084-76292a56-a064-11e8-9983-ef305b253374.png">

**Comment by kbushkoBH** [comment]
Thank you for your inquiry and your patience!

Bullhorn's EEOC fields allow customers to capture information to help them decide when to send official forms if needed - however the fields are not meant to replicate the official forms in any way. 

You can certainly enhance the apply modal with an electronic signature element on a per portal basis if desired.
