### ISSUE TITLE
WP Plugin Activation Error

### ISSUE THREAD

**Issue by Moolar** [bullhorn/career-portal#220]
Hello -I am getting this error when attempting to install the plugin for Wordpress, "Bullhorn-oscp"

Parse error: syntax error, unexpected '[', expecting ')' in /home/lili2732/public_html/wp-content/plugins/bullhorn-oscp/wp-oscp.php on line 354
![plugins libertyit wordpress - google chrome 2018-08-19 12 03 51](https://user-images.githubusercontent.com/42519365/44311157-0647c480-a3a8-11e8-8616-a172f20ef4d9.png)

**Comment by pbearne** [comment]
Hi Moolar

Sorry to hear you are having problems.
As you trying to link Bullhorn to Wordpress you might want to look at the MatadorJobs.com as our plugin integrates bullhorn directly into Wordpress rather than just an Iframe around OSCP (Big SEO benefits)  

As I am a bit WordPress/PHP expert I have had quick look at the code and this my guess to as the fix

fin this block of code line 253

$scrollableConfig = array(
[
'label' => 'Yes',
'value' => 'yes'
],
[
'label' => 'No',
'value' => 'no'
]
);
and change it to 

$scrollableConfig = array(
array(
'label' => 'Yes',
'value' => 'yes'
),
array(
'label' => 'No',
'value' => 'no'
)
);
and see it that fixes it (code not tested)

I suspect it due to your PHP version not support the short version of the array construction

I hope this helps 

Paul

**Comment by charlesabarnes** [comment]
Thank you Paul, 

The plugin was updated via your suggestion.

@Moolar, as the plugin was updated you are free to give it another try, but I will suggest upgrading your version of PHP up to 5.6.  The plugin will soon be updated to require supported versions of PHP and more recent versions of Wordpress, so to continue to receive updates, please begin upgrading.  Thank you.

**Comment by charlesabarnes** [comment]
Oh! looks like you set it up correctly.  You just need to contact Bullhorn Support to complete the setup!

**Comment by Moolar** [comment]
ok, thanks much. We are in that process now.

**Comment by Moolar** [comment]
Hi @charlesabarnes , maybe you have a tip for me here. We had it working, but then activated our ssl / https . Now we are getting,

> The page at 'https://www.libertyit.com.au/career-portal/' was loaded over HTTPS, but requested an insecure resource 'http://www.libertyit.com.au/wp-content/plugins/bullhorn-oscp/'. This request has been blocked; the content must be served over HTTPS.

**Comment by charlesabarnes** [comment]
Did you update the URLs under Settings > General?

**Comment by Moolar** [comment]
yes

![image](https://user-images.githubusercontent.com/42519365/44605536-64f9ad80-a7af-11e8-9681-9e44ff76510f.png)

**Comment by Moolar** [comment]
I also have "Really Simple SSL" installed

**Comment by charlesabarnes** [comment]
I am investigating this now,

It's telling me the resource uses "http://" even though when I check out the DOM it shows "https://" 

This may be related to this error I get in firefox specifically.

> An error occurred during a connection to www.libertyit.com.au. SSL received a record that exceeded the maximum permissible length. Error code: SSL_ERROR_RX_RECORD_TOO_LONG
> 
>     The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
>     Please contact the website owners to inform them of this problem.

**Comment by charlesabarnes** [comment]
I have found a possible explanation but this would require intervention with your webhost support.

https://stackoverflow.com/questions/48138364/https-iframe-inside-a-https-page-not-working

![image](https://user-images.githubusercontent.com/4327754/44606473-d555fe00-a7b2-11e8-91f9-4eeb2a07ae96.png)



I am pushing an update now however that is adding the trailing slash.   Weird issue!

**Comment by charlesabarnes** [comment]
I pushed an update to the plugin to fix this issue

**Comment by Moolar** [comment]
What can I do on my end? (or Bullhorn?)

**Comment by charlesabarnes** [comment]
Now you just need to update your plugin and it should work.

In the future however you may want to look into why your server wasn't redirecting to https

**Comment by Moolar** [comment]
Ok, thanks.

How do I update? It doesn't say there is an auto-update. Do I download and upload/update manually?

**Comment by charlesabarnes** [comment]
WordPress plugins auto-updates every 12 hours or so. You can manually update by removing the plugin and installing it back in with by downloading the zip file from the [WordPress ](https://wordpress.org/plugins/bullhorn-oscp/)website

**Comment by charlesabarnes** [comment]
If you have FTP access you can also replace the files directly under wp-content/plugins/bullhorn-oscp

**Comment by Moolar** [comment]
Yep! (used the file manager) and it's good to go! https://www.libertyit.com.au/career-portal/

Thanks much. I've passed on to the client(s) our history and success here.
