### ISSUE TITLE
500 Response, no jobs returned

### ISSUE THREAD

**Issue by LakenH** [bullhorn/career-portal#221]
## Overview
  
Receiving 500 HTTP response from Bullhorn API. Using the WordPress plugin, though the behavior is the same as the "regular" install.
  
Similar issues found on this repo mention that this is due to the career portal not being enabled on the Bullhorn account. My client has been in contact with Bullhorn support, and the career portal should be enabled. 
 
## Attempted Remedies
  
- Confirmed that the app.json generated by the WordPress plugin looks correct
- The client contacted their Bullhorn support representative and confirmed the swimlane & corp token.
- The client also ensured that career portal access was enabled for their account.
  
## Relevant Issues
 
#29 #72 #167

**Comment by charlesabarnes** [comment]
Hey @LakenH As mentioned previously (thanks for your diligence in researching this btw).  This is still the same behavior that companies with the public api disabled exhibit.  

Can you share with me the company's name so I can make sure they are taken care of?   

Thank you

**Comment by LakenH** [comment]
Sure - my client's company name is `Healthcare Support`

**Comment by charlesabarnes** [comment]
I took a look at this and fixed the issue preventing the jobs from loading they should work now.  A user was disabled that shouldn't have been.

**Comment by LakenH** [comment]
Thank you, working great now.
