### ISSUE TITLE
eeoc config options from app.json.template file not honored

### ISSUE THREAD

**Issue by billy-bacon** [bullhorn/career-portal#222]
## Current behavior

If you set any/all of the `eeoc` config options in your app.json.template file (for example, to `true`), when you build the app for local development or distribution, the values are not honored/persisted and they default to `false`.

## Expected behavior

When you make configuration changes to try and turn on some/all of the `eeoc` features in your app.json.template file, running `gulp` will honor the values set and build the distribution correctly. The section for the app.json.template file I'm referring to is below.

```
"eeoc": {
        "genderRaceEthnicity": true,
        "veteran": true,
        "disability": true
}
```
## Steps to replicate behavior

1. Change the `eeoc` config values from `false` to `true` in your app.config.template file.
2.) Run `gulp` to build your distribution.
3.) Once gulp finishing building the app, view the resulting `app.json` file under the `/dist` directory.
4.) You'll find that the `eeoc` section does not reflect the values you specified in your `app.json.template` file.

**Comment by billy-bacon** [comment]
I tried to push a feature branch to the remote and was denied due to persmissions. I have a fix for this issue and would like to create a pull request for it. How do I obtain permission to do so? I didn't see the proper method of contributing a fix like this in the CONTRIBUTING.md document.

**Comment by charlesabarnes** [comment]
Hello, 
To contribute to this project you need to create a pull request from your github fork of the code.  The steps are outlined in the article below.

https://gist.github.com/MarcDiethelm/7303312
