### ISSUE TITLE
CCP (Corporate Compliance Plan) 

### ISSUE THREAD

**Issue by shelldjohnson** [bullhorn/career-portal#223]
INSERT SHORT DESCRIPTION EXPLAINING THE HIGH-LEVEL REASON FOR THE NEW ISSUE HERE.

Trying to uploade the code for Open Source Career Portal to our website. Our developers would like to know how the CCPCode is generated or where they can find it.

**Comment by charlesabarnes** [comment]
Hello, all text found on the career portal is stored in language JSON files found in the `/res` directory.  Adjusting the text found there will reflect on your portal wherever you would like.
