### ISSUE TITLE
HELP SETTING UP BULLHORN CAREER PORTAL

### ISSUE THREAD

**Issue by MunishJoshi72** [bullhorn/career-portal#228]
INSERT SHORT DESCRIPTION EXPLAINING THE HIGH-LEVEL REASON FOR THE NEW ISSUE HERE.

## Current behavior

- I have installed the files that I downloaded and all I see is page with Key word search, Location, Category and then the footer details and no portal.

## Expected behavior

- I was expecting to see the job board

## Steps to replicate behavior

1. Downloaded latest release and Ftp'd the files to a sub-directory I called career_portal

## Screenshots
![image](https://user-images.githubusercontent.com/43548686/45967337-ad4cfb00-bffb-11e8-8db4-db10ec51c18f.png)

__Current__

__Expected__

**Comment by charlesabarnes** [comment]
Hello,

It looks like all of the stylesheets are missing.  Are there any errors in the browser console?

**Comment by MunishJoshi72** [comment]
No errors in the browser but I will go back and see if the style sheets are missing (I assume the files under the directory titled styles).

Let me know if this is incorrect.

**Comment by charlesabarnes** [comment]
Hello, to post a job, it appears as if the public api needs to be enabled. 

To do so, you will want to contact bullhorn support. Please let me know if you have any questions.
