### ISSUE TITLE
Career Portal date formatting

### ISSUE THREAD

**Issue by CreatiVue** [bullhorn/career-portal#229]
Date displayed in Career Portal different from the Locale set in BullHorn settings

## Current behavior

- date displaying as en_US  (MM/DD/YYYY) 

## Expected behavior

- date to display the same as Locale set in BullHorn Setting currently en_GB (DD/MM/YYYY)

## Screenshots

__Current__
![img_20181017_140022](https://user-images.githubusercontent.com/44229848/47088249-ec92f400-d215-11e8-9f19-20023ea6e0c4.png)
![img_20181017_140309](https://user-images.githubusercontent.com/44229848/47088259-f4eb2f00-d215-11e8-9368-d6a417ab00bd.png)

**Comment by charlesabarnes** [comment]
Hi @CreatiVue,

That particular setting does not affect the career portal.   This configuration is controlled via the defaultLocale setting in your app.json file.

Please let me know if you have any more questions

**Comment by arnevanbrainbridge** [comment]
Neither en-EU nor en-GB seem to set the date to DD-MM-YYYY

**Comment by CreatiVue** [comment]
We endend up renaming/changing the default date format for en-US as the settings would not save that we'd selected en-GB as default locale.
