### ISSUE TITLE
Job posting date & Company header

### ISSUE THREAD

**Issue by NetworklinkHaarlem** [bullhorn/career-portal#231]
Hi!

Hope you can help me out.
I have the Bullhorn Career Portal integrated on my Wordpress website with an iFrame.
Is it possible to remove: the company name + date added (see screenshot)?
The website is https://networklink.nl/digital-interim-opdrachten/
Many thanks in advance!
![knipsel](https://user-images.githubusercontent.com/38694326/47354079-08871180-d6be-11e8-86cd-175300d66e28.JPG)

Kind regards,

Remco

**Comment by charlesabarnes** [comment]
Hello, there are several approaches you can make for this, currently the best approach would be to customize the code for your portal by modifying the html template files for the [list items](https://github.com/bullhorn/career-portal/tree/master/src/app/list) and the [header](https://github.com/bullhorn/career-portal/tree/master/src/app).  Once that is done you are able to [build the portal ](https://github.com/bullhorn/career-portal#building) and publish it out as you have done previously.

Please let me know if you have any more questions.
