### ISSUE TITLE
MailTo Link on Job Page Encodes Ampersands in Job Titles Incorrectly

### ISSUE THREAD

**Issue by djohnsonbh** [bullhorn/career-portal#236]
On the job page in the OSCP, when attempting to share by email a job with an ampersand in the title, the body of the email is not properly sent to the email program.

## Current behavior

This appears to be a result of ampersands in the title of the job being encoded as &amp instead of %26 in the mailto link:
`<a data-ng-href="mailto:?subject=Banking%20%26%20Finance%20Associate&amp;body=Check out this Banking &amp; Finance Associate job: https%3A%2F%2Fwww.acmeco.com%2Fopportunities%2F%23%2Fjobs%2F490" href="mailto:?subject=Banking%20%26%20Finance%20Associate&amp;body=Check out this Banking &amp; Finance Associate job: https%3A%2F%2Fwww.acmeco.com%2Fopportunities%2F%23%2Fjobs%2F490"><i class="bhi-email"></i></a>`

## Expected behavior

Editing the link in dev tools will result in the link functioning correctly:
`<a data-ng-href="mailto:?subject=Banking%20%26%20Finance%20Associate&amp;body=Check out this Banking %26 Finance Associate job: https%3A%2F%2Fwww.acmeco.com%2Fopportunities%2F%23%2Fjobs%2F490" href="mailto:?subject=Banking%20%26%20Finance%20Associate&amp;body=Check out this Banking %26 Finance Associate job: https%3A%2F%2Fwww.acmeco.com%2Fopportunities%2F%23%2Fjobs%2F490"><i class="bhi-email"></i></a>`
Issue occurs regardless of what the default email program is (Chrome/Gmail or Outlook)
Workaround is to replace "&" with "and" in job titles and republish

## Steps to replicate behavior

1. Navigate to an OSCP with a job containing an ampersand. e.g.: "M&A Manager"
2. Share > Email
3. Observe in the email that opens the body reads "Check out this M"
Inspect the email share button and observe the & character in the mailto link:
`<a data-ng-href="mailto:?subject=M%26A%20Manager&amp;body=Check out this M&amp;A Manager job: http%3A%2F%2Fwww.acmeco.com%2F%23%2Fjobs%2F6" href="mailto:?subject=M%26A%20Manager&amp;body=Check out this M&amp;A Manager job: http%3A%2F%2Fwww.acmeco.com%2F%23%2Fjobs%2F6"><i class="bhi-email"></i></a>`
4. Edit the element and encode the ampersand:
`<a data-ng-href="mailto:?subject=M%26A%20Manager&amp;body=Check out this M%26A Manager job: http%3A%2F%2Fwww.acmeco.com%2F%23%2Fjobs%2F6" href="mailto:?subject=M%26A%20Manager&amp;body=Check out this M%26A Manager job: http%3A%2F%2Fwww.acmeco.com%2F%23%2Fjobs%2F6"><i class="bhi-email"></i></a>`
5. Click the email button again
6. Observe the email body reads "Check out this M&A Manager job: http://www.acmeco.com/#/jobs/6"

**Comment by charlesabarnes** [comment]
can you try retesting this in one of the V3 portals?

**Comment by jamesco** [comment]
Still experiencing this error with v3.1.1 on a local install.
