### ISSUE TITLE
Exclude a Category and its jobs from the List, Sidebar, and Counts

### ISSUE THREAD

**Issue by timelytree** [bullhorn/career-portal#238]
Hey,

This is not actually an issue - but is a particular use case that I can't seem to implement and can't seem to figure out in reading the API docs. Here's the rundown:

- We need to be able to **exclude** an entire Category (and all jobs in this category) from the job List, Sidebar and Counts (re: numbers beside the Locations in the sidebar)
- The jobs that are in this Category should only be accessible in the Single Job Post view

Would someone be able to point me in the right direction?

**Comment by charlesabarnes** [comment]
Hello @timelytree,

You are able to adjust this within the files for the [Search Service](https://github.com/bullhorn/career-portal/blob/master/src/app/services/search.service.js). Basically in there you are able to utilize the `NOT` operator within your queries.

Please let me know if you have any more questions.

**Comment by timelytree** [comment]
Hey @charlesabarnes, thanks a million for the super quick reply. If it's not too much to ask, can you give me an example of how to use the `NOT` operator within queries?

**Comment by charlesabarnes** [comment]
An example would be [here ](https://github.com/bullhorn/career-portal/blob/master/src/app/services/search.service.js#L160).  

For a query this will evaluate as `isOpen:1 AND isDeleted:0`  What you can add to the end of that is `NOT publishedCategory.id:{categoryIdHere}`

**Comment by timelytree** [comment]
Worked like a charm, thanks again!!
