### ISSUE TITLE
Automated Job Expiry

### ISSUE THREAD

**Issue by mpaus18** [bullhorn/career-portal#239]
**Is your feature request related to a problem? Please describe.**
Currently, jobs stay published until they are manually un-published.

**Describe the solution you'd like**
It would be very useful if jobs would get un-published automatically if one of 2 conditions is met:
1) If the end date assigned to the job is exceeded (if one is assigned) or 
2) If the job status is set to 'Placed' (this is the status value which Bullhorn assigns to a job when a placement is made and the job is filled)

**Describe alternatives you've considered**
The only other way to do this is the current manual process. But that's time-intensive and someone has to manage the placements all the time - while the system already contains the necessary information to automatically un-publish jobs.

**Comment by charlesabarnes** [comment]
Hello, 

While it doesn't address both use cases,[ there is a system setting to automatically close jobs when there is a placement](https://help.bullhorn.com/s/article/Automatically-Closing-Jobs-Upon-Placement). This will remove the job from the career portal.

For this enhancement, there is potentially a way to implement this in the career portal project, however this would best be implemented in the Bullhorn ATS itself as it would need to also remove the job from any other job sites that the job is published to.  I suggest submitting this feature request as feedback [here on our customer Portal](http://customerportal.bullhorn.com/feedback/).   

Please let me know if you have any questions.

**Comment by pbearne** [comment]
Hi,

This is something we may be able to help with the Matador Jobs WordPress Plugin. As we use the full private API we can adjust the search params when we fetch the jobs, so if we can construct a search to filter the jobs as you need or/and we can fetch extra data and filter as part of the importing/sync process

Reach out if you would like to explore this.

https://matadorjobs.com/

Paul

**Comment by mpaus18** [comment]
Hi Charles,

thanks for letting me know! I had talked to Bullhorn Support and they said there was no way at all to automatically un-publish a job. I'm glad to hear that a closed job will disappear from the career portal.
