### ISSUE TITLE
Job board title change

### ISSUE THREAD

**Issue by NetworklinkHaarlem** [bullhorn/career-portal#240]
Hi!

I would like to change the job board header title:
![website](https://user-images.githubusercontent.com/38694326/49515851-5a63af80-f898-11e8-8d0d-de1a48dad8c8.JPG)

I found the line of code where I can do this:
![code](https://user-images.githubusercontent.com/38694326/49515871-664f7180-f898-11e8-8a47-215c44f94415.JPG)

Can I change this? Or is this an exact match with my Bullhorn account, and therefore needed for a pairing with the back-end?

Thanks in advance!!

**Comment by lewispaige** [comment]
Well we changed ours and no issues.. http://take.ms/TG0w5

**Comment by charlesabarnes** [comment]
That can be changed to whatever you like without affecting the job listings.  It changes what you see at the top, and what company name you see in the EEOC tooltips (if enabled)

**Comment by NetworklinkHaarlem** [comment]
Great, thank you so much!!

**Comment by nlakamsany** [comment]
Can we change it to something like ‘current openings’ across the board. Who uses company name over there and why?

**Comment by charlesabarnes** [comment]
Yes it can be set to be any string of text
