### ISSUE TITLE
UTM Tracking

### ISSUE THREAD

**Issue by ravi1017** [bullhorn/career-portal#241]
Can Bullhorn identify UTM parameters set by our company and have it trigger "Source" field in the interface?

I have candidates applying from many sources such as LinkedIn, Indeed, Glassdoor, etc...I want applicants from these various sources to be redirected to our company's website and then fill out an application form. The redirect is the easy part, but what I need more information on is whether Bullhorn can identify UTM parameters I set for distinct lead sources. Example, a candidate redirected from LinkedIn will visit our careers site with a specified UTM and if that candidate submits an application, then Bullhorn should receive relevant information including UTM code via an API connection we currently have set up between our Careers Site and Bullhorn. 

We have a "Source" field in Bullhorn that is a custom field listing various lead sources candidates can come from. Once applications are sent to Bullhorn with UTM information, can Bullhorn trigger the "Source" field automatically based on a if then logic and discern where candidates are coming from based on UTM code?

**Comment by charlesabarnes** [comment]
Hello,

We don't use UTM parameters but we do have a simple parameter that is very similar. You are able to include a source parameter when a job is linked on an external website.   This will be added into Bullhorn on the appropriate field.  The parameter can only be used when linking to a specific job and not to the whole job board itself.  To do this you will want to format the url as `site.com/portalDirectory/#/jobs/JOBID?source=LinkedIn`.

Please let me know if you have any questions

**Comment by pbearne** [comment]
Hi Charles

We have been asked to get this to work as well in Matador jobs

So which field in the candidate object?

So we use the same object :-)

Have a good break

Paul

*Paul Bearne*
*Phone: +1 647 780 7594*
*E-mail: **paul@bearne.com* <pbearne@gmail.com>
*@pbearne <http://twitter.com/pbearne> *or +pbearne
<https://plus.google.com/u/0/100456877588970933323>

**Comment by ravi1017** [comment]
Hey Charles,

I created a dummy LinkedIn job post redirecting the applicant to the following URL: https://careers.newdayusa.com/careers/corporate-recruiter/?source=LinkedIn

The redirect works fine but once an application is submitted and candidate profile is created in Bullhorn, the “Source” field does not update automatically to “LinkedIn” despite both values being a match. Is there something I am doing incorrectly?

**Comment by charlesabarnes** [comment]
Hey @ravi1017 that appears to not be the Bullhorn Career Portal and falls out of scope of the Career Portal project.   I suggest checking out our [REST docs](http://bullhorn.github.io/rest-api-docs/) for reference.  

@pbearne 
To answer both questions at the same time, you will just want to add the `source` to the `JobSubmission` and the `Candidate`  creation requests

**Comment by ravi1017** [comment]
Thanks Charles, do you believe we can make this work effectively by setting up UTM parameters per distinct source and having that trigger the “Source” field in Bullhorn post application submission?


Ravi Sachania, CRU
Digital Business Analyst
MLONMLS # 1541627
Company NMLS # 1043
Tel: 877-236-1968|Fax: 844-494-1718
==========================================================================
 NewDay USA is a registered dba of NewDay Financial, LLC.
==========================================================================
 CONFIDENTIALITY NOTICE: This e-mail message and any attachments are proprietary and
​confidential information intended only for the use of the recipient(s) named above. If you are
​not the intended recipient, you may not print, distribute, or copy this message or any attachments.
​If you have received this communication in error, please notify the sender by return e-mail and 
​delete this message and any attachments from your computer.
 ==========================================================================
