### ISSUE TITLE
Additional fields

### ISSUE THREAD

**Issue by RichardCore37** [bullhorn/career-portal#244]
I'm looking to add additional fields/filters to the career portal. But currently on the back end of Bullhorn the Publish page only shows 'Published Category' and 'Published Contact Recruiter'. How do I add addition drop down options, e.g. 'Published Sector', 'Published Specialism'?

**Comment by charlesabarnes** [comment]
Hello, the fields on the publish page are fields that are intended to be specific to the job itself.  You are able to add additional custom fields to jobs published on the portal via fields such as `customText2` however they will not be available on the publishing screen. You may want to take a look at #208 and #207 because they both describe the steps necessary to add a field and add a filter.  Thanks!

**Comment by RichardCore37** [comment]
Thanks Charles. I'm making some headway but I'm finding that some fields - customtext7, for example - just doesn't seem to be pulling through from the back end to the front end. Do you know why this might be?

Best regards,
Richard


________________________________

Richard England
Communications Director
Core-Asset Consulting
37 Melville St
Edinburgh, EH3 7JF
t: +44 (0)131 718 4600
w: core-asset.co.uk
At Core-Asset, we’re committed to protecting and respecting your privacy. Our privacy statement explains when and why we collect personal information about people who engage with our services, how we use it, the conditions under which we may disclose it to others, and how we keep it secure. We may change this policy from time to time, so please check this policy occasionally to ensure that you’re happy with any changes.
 
By engaging with us (either by applying for a job we’re advertising, registering through our website, or getting in touch with our business) you’re agreeing to be bound by this policy. Core-Asset Consulting is committed to protecting the privacy of our candidates, clients and website users. For further information, please refer to our full Privacy Statement available on our website.

This email, its content, and any files attached are intended solely for the addressee(s) and may be legally privileged and or confidential.  If you are not the intended recipient please notify the author immediately by telephone, facsimile or email, additionally please do not disclose, distribute, copy, print, or reply to this email if you are not the intended recipient. Core Asset Consulting (Core-Asset) does not accept responsibility for changes made to this email after it was sent.  Messages sent via this medium may be subject to delays, non-delivery and unauthorised alteration.  This email has been prepared using information believed by the author to be reliable and accurate; however Core-Asset carries no warranty as to the accuracy or completeness of the information. Core-Asset virus scan and monitor all e-mails however are not responsible for any damage caused, directly or indirectly by a virus/alteration of this e-mail by a third party after sending.
  
 All email and instant messages (including attachments) may be retained, monitored and/or reviewed by Core-Asset and its agents, or authorized law enforcement personnel, without further notice or consent. Company number: SC282072.

**Comment by charlesabarnes** [comment]
There is a default set of fields that is available to be accessed through the public API.   This list can be modified by contacting Bullhorn Support.  Once you reach out to them, that field should come back in the API.

Let me know if you have any more questions.

**Comment by RichardCore37** [comment]
Thanks Charles.

Best regards,
Richard


________________________________

Richard England
Communications Director
Core-Asset Consulting
37 Melville St
Edinburgh, EH3 7JF
t: +44 (0)131 718 4600
w: core-asset.co.uk
At Core-Asset, we’re committed to protecting and respecting your privacy. Our privacy statement explains when and why we collect personal information about people who engage with our services, how we use it, the conditions under which we may disclose it to others, and how we keep it secure. We may change this policy from time to time, so please check this policy occasionally to ensure that you’re happy with any changes.
 
By engaging with us (either by applying for a job we’re advertising, registering through our website, or getting in touch with our business) you’re agreeing to be bound by this policy. Core-Asset Consulting is committed to protecting the privacy of our candidates, clients and website users. For further information, please refer to our full Privacy Statement available on our website.

This email, its content, and any files attached are intended solely for the addressee(s) and may be legally privileged and or confidential.  If you are not the intended recipient please notify the author immediately by telephone, facsimile or email, additionally please do not disclose, distribute, copy, print, or reply to this email if you are not the intended recipient. Core Asset Consulting (Core-Asset) does not accept responsibility for changes made to this email after it was sent.  Messages sent via this medium may be subject to delays, non-delivery and unauthorised alteration.  This email has been prepared using information believed by the author to be reliable and accurate; however Core-Asset carries no warranty as to the accuracy or completeness of the information. Core-Asset virus scan and monitor all e-mails however are not responsible for any damage caused, directly or indirectly by a virus/alteration of this e-mail by a third party after sending.
  
 All email and instant messages (including attachments) may be retained, monitored and/or reviewed by Core-Asset and its agents, or authorized law enforcement personnel, without further notice or consent. Company number: SC282072.

**Comment by RichardCore37** [comment]
Hi Charles,


I think we've been using the default set of fields - customtext6, customtext7, etc.


Does my developer need an API key?

Best regards,
Richard


________________________________

Richard England
Communications Director
Core-Asset Consulting
37 Melville St
Edinburgh, EH3 7JF
t: +44 (0)131 718 4600
w: core-asset.co.uk
At Core-Asset, we’re committed to protecting and respecting your privacy. Our privacy statement explains when and why we collect personal information about people who engage with our services, how we use it, the conditions under which we may disclose it to others, and how we keep it secure. We may change this policy from time to time, so please check this policy occasionally to ensure that you’re happy with any changes.
 
By engaging with us (either by applying for a job we’re advertising, registering through our website, or getting in touch with our business) you’re agreeing to be bound by this policy. Core-Asset Consulting is committed to protecting the privacy of our candidates, clients and website users. For further information, please refer to our full Privacy Statement available on our website.

This email, its content, and any files attached are intended solely for the addressee(s) and may be legally privileged and or confidential.  If you are not the intended recipient please notify the author immediately by telephone, facsimile or email, additionally please do not disclose, distribute, copy, print, or reply to this email if you are not the intended recipient. Core Asset Consulting (Core-Asset) does not accept responsibility for changes made to this email after it was sent.  Messages sent via this medium may be subject to delays, non-delivery and unauthorised alteration.  This email has been prepared using information believed by the author to be reliable and accurate; however Core-Asset carries no warranty as to the accuracy or completeness of the information. Core-Asset virus scan and monitor all e-mails however are not responsible for any damage caused, directly or indirectly by a virus/alteration of this e-mail by a third party after sending.
  
 All email and instant messages (including attachments) may be retained, monitored and/or reviewed by Core-Asset and its agents, or authorized law enforcement personnel, without further notice or consent. Company number: SC282072.

**Comment by charlesabarnes** [comment]
The default fields that are accessible via the **public-rest-api** are:

`address(address1,city,state,zip,countryID),benefits,bonusPackage,dateAdded,dateEnd,dateLastPublished,employmentType,id,isOpen,isPublic,payRate,publicDescription,publishedCategory(id,name),publishedZip,responseUser(id,firstName,lastName),salary,salaryUnit,startDate,title,travelRequirements,willRelocate,willSponsor,yearsRequired`

to have a field added to that list you need to contact Bullhorn Support.   

Your developer does not need an API key for the public-rest-api

**Comment by RichardCore37** [comment]
Hi Charles,


Bullhorn are saying that we should be using the public rest API. I am mightily confused??

Best regards,
Richard


________________________________

Richard England
Communications Director
Core-Asset Consulting
37 Melville St
Edinburgh, EH3 7JF
t: +44 (0)131 718 4600
w: core-asset.co.uk
At Core-Asset, we’re committed to protecting and respecting your privacy. Our privacy statement explains when and why we collect personal information about people who engage with our services, how we use it, the conditions under which we may disclose it to others, and how we keep it secure. We may change this policy from time to time, so please check this policy occasionally to ensure that you’re happy with any changes.
 
By engaging with us (either by applying for a job we’re advertising, registering through our website, or getting in touch with our business) you’re agreeing to be bound by this policy. Core-Asset Consulting is committed to protecting the privacy of our candidates, clients and website users. For further information, please refer to our full Privacy Statement available on our website.

This email, its content, and any files attached are intended solely for the addressee(s) and may be legally privileged and or confidential.  If you are not the intended recipient please notify the author immediately by telephone, facsimile or email, additionally please do not disclose, distribute, copy, print, or reply to this email if you are not the intended recipient. Core Asset Consulting (Core-Asset) does not accept responsibility for changes made to this email after it was sent.  Messages sent via this medium may be subject to delays, non-delivery and unauthorised alteration.  This email has been prepared using information believed by the author to be reliable and accurate; however Core-Asset carries no warranty as to the accuracy or completeness of the information. Core-Asset virus scan and monitor all e-mails however are not responsible for any damage caused, directly or indirectly by a virus/alteration of this e-mail by a third party after sending.
  
 All email and instant messages (including attachments) may be retained, monitored and/or reviewed by Core-Asset and its agents, or authorized law enforcement personnel, without further notice or consent. Company number: SC282072.

**Comment by charlesabarnes** [comment]
Hello, I am reaching out on my side to make sure we can get this taken care of for you as expediently as possible.

**Comment by RichardCore37** [comment]
Thank you, Charles. Dealing with Bullhorn support but not sure how up to speed they are with the portal.

Best regards,
Richard


________________________________

Richard England
Communications Director
Core-Asset Consulting
37 Melville St
Edinburgh, EH3 7JF
t: +44 (0)131 718 4600
w: core-asset.co.uk
At Core-Asset, we’re committed to protecting and respecting your privacy. Our privacy statement explains when and why we collect personal information about people who engage with our services, how we use it, the conditions under which we may disclose it to others, and how we keep it secure. We may change this policy from time to time, so please check this policy occasionally to ensure that you’re happy with any changes.
 
By engaging with us (either by applying for a job we’re advertising, registering through our website, or getting in touch with our business) you’re agreeing to be bound by this policy. Core-Asset Consulting is committed to protecting the privacy of our candidates, clients and website users. For further information, please refer to our full Privacy Statement available on our website.

This email, its content, and any files attached are intended solely for the addressee(s) and may be legally privileged and or confidential.  If you are not the intended recipient please notify the author immediately by telephone, facsimile or email, additionally please do not disclose, distribute, copy, print, or reply to this email if you are not the intended recipient. Core Asset Consulting (Core-Asset) does not accept responsibility for changes made to this email after it was sent.  Messages sent via this medium may be subject to delays, non-delivery and unauthorised alteration.  This email has been prepared using information believed by the author to be reliable and accurate; however Core-Asset carries no warranty as to the accuracy or completeness of the information. Core-Asset virus scan and monitor all e-mails however are not responsible for any damage caused, directly or indirectly by a virus/alteration of this e-mail by a third party after sending.
  
 All email and instant messages (including attachments) may be retained, monitored and/or reviewed by Core-Asset and its agents, or authorized law enforcement personnel, without further notice or consent. Company number: SC282072.

**Comment by RichardCore37** [comment]
Hi Charles,


Many thanks for your help yesterday. We've solved the two field issues we have.


One other thing - do you know how we override 'City' and 'State' fields within Job Location on the vacancy in order for the career portal to pull info from PublishedZip instead?

Best regards,
Richard


________________________________

Richard England
Communications Director
Core-Asset Consulting
37 Melville St
Edinburgh, EH3 7JF
t: +44 (0)131 718 4600
w: core-asset.co.uk
At Core-Asset, we’re committed to protecting and respecting your privacy. Our privacy statement explains when and why we collect personal information about people who engage with our services, how we use it, the conditions under which we may disclose it to others, and how we keep it secure. We may change this policy from time to time, so please check this policy occasionally to ensure that you’re happy with any changes.
 
By engaging with us (either by applying for a job we’re advertising, registering through our website, or getting in touch with our business) you’re agreeing to be bound by this policy. Core-Asset Consulting is committed to protecting the privacy of our candidates, clients and website users. For further information, please refer to our full Privacy Statement available on our website.

This email, its content, and any files attached are intended solely for the addressee(s) and may be legally privileged and or confidential.  If you are not the intended recipient please notify the author immediately by telephone, facsimile or email, additionally please do not disclose, distribute, copy, print, or reply to this email if you are not the intended recipient. Core Asset Consulting (Core-Asset) does not accept responsibility for changes made to this email after it was sent.  Messages sent via this medium may be subject to delays, non-delivery and unauthorised alteration.  This email has been prepared using information believed by the author to be reliable and accurate; however Core-Asset carries no warranty as to the accuracy or completeness of the information. Core-Asset virus scan and monitor all e-mails however are not responsible for any damage caused, directly or indirectly by a virus/alteration of this e-mail by a third party after sending.
  
 All email and instant messages (including attachments) may be retained, monitored and/or reviewed by Core-Asset and its agents, or authorized law enforcement personnel, without further notice or consent. Company number: SC282072.

**Comment by charlesabarnes** [comment]
you will wanna update that in the front-end code located in one of the html templates.  I am assuming you will want to update it in multiple places so I can't be too specific,  but you will be replacing occurrences in the html that looks something like `job.address.city` with the desired fields

**Comment by RichardCore37** [comment]
Thanks Charles.

Best regards,
Richard


________________________________

Richard England
Communications Director
Core-Asset Consulting
37 Melville St
Edinburgh, EH3 7JF
t: +44 (0)131 718 4600
w: core-asset.co.uk
At Core-Asset, we’re committed to protecting and respecting your privacy. Our privacy statement explains when and why we collect personal information about people who engage with our services, how we use it, the conditions under which we may disclose it to others, and how we keep it secure. We may change this policy from time to time, so please check this policy occasionally to ensure that you’re happy with any changes.
 
By engaging with us (either by applying for a job we’re advertising, registering through our website, or getting in touch with our business) you’re agreeing to be bound by this policy. Core-Asset Consulting is committed to protecting the privacy of our candidates, clients and website users. For further information, please refer to our full Privacy Statement available on our website.

This email, its content, and any files attached are intended solely for the addressee(s) and may be legally privileged and or confidential.  If you are not the intended recipient please notify the author immediately by telephone, facsimile or email, additionally please do not disclose, distribute, copy, print, or reply to this email if you are not the intended recipient. Core Asset Consulting (Core-Asset) does not accept responsibility for changes made to this email after it was sent.  Messages sent via this medium may be subject to delays, non-delivery and unauthorised alteration.  This email has been prepared using information believed by the author to be reliable and accurate; however Core-Asset carries no warranty as to the accuracy or completeness of the information. Core-Asset virus scan and monitor all e-mails however are not responsible for any damage caused, directly or indirectly by a virus/alteration of this e-mail by a third party after sending.
  
 All email and instant messages (including attachments) may be retained, monitored and/or reviewed by Core-Asset and its agents, or authorized law enforcement personnel, without further notice or consent. Company number: SC282072.
