### ISSUE TITLE
Location is not available as a filter

### ISSUE THREAD

**Issue by arnevanbrainbridge** [bullhorn/career-portal#247]
INSERT SHORT DESCRIPTION EXPLAINING THE HIGH-LEVEL REASON FOR THE NEW ISSUE HERE.

## Current behavior

-The location in the jobs is assigned and displayed in the detail of the job, but the locations are not available in the filter in the portal

## Expected behavior

-Ability to filter based on locations (derived from the jobs)

## Steps to replicate behavior

1.

## Screenshots

__Current__

__Expected__

**Comment by charlesabarnes** [comment]
Hello, 

Location should be available in the sidebar of the portal separated by `city, state`.  If this is not displaying there is possibly something wrong with your job data. can you provide a screenshot of the home page of your career portal?

**Comment by arnevanbrainbridge** [comment]
City and State appear to be empty in our Jobpostings, so we will find out what is causing this in Bullhorn.
We assumed location was the source for City and State, but they appear to be separate field in the jobposting.

**Comment by charlesabarnes** [comment]
The career portal concatenates the two fields together in the front end.  If the two fields are not populated in Bullhorn, then it will not display in the front end.   I suggest reaching out to Bullhorn Support to potentially get hands-on assistance with this.
