### ISSUE TITLE
Add job reference to detail of a job

### ISSUE THREAD

**Issue by arnevanbrainbridge** [bullhorn/career-portal#248]
**Is your feature request related to a problem? Please describe.**
When communicating about jobs the title is not usable as a unique reference. The job referenceID however is a unique reference but is not displayed.

**Describe the solution you'd like**
Display the jobID on the detail page of the job.

**Describe alternatives you've considered**

**Additional context**

**Comment by charlesabarnes** [comment]
Hello, this is very similar to #74.  I suggest checking out that issue, however it will require a code modification.  Please let me know if you have any questions.

**Comment by arnevanbrainbridge** [comment]
Yes indeed it is similar and I have seen that the reponse from the API already contains the ID of a jobposting. So now I just have to find out, how to get this displayed in the detail of a job as a line.

**Comment by charlesabarnes** [comment]
You will need to change the places with string interpolation (words that are surrounded by `{{ }}`) with the desired fields in the desired location(s).

**Comment by charlesabarnes** [comment]
I also wanted to provide a reference to our wiki that provides information about doing this. https://github.com/bullhorn/career-portal/wiki/Customization-of-the-Portal 

Please let me know if you have any questions.
