### ISSUE TITLE
Customizing Canadidate Applications by Source

### ISSUE THREAD

**Issue by Royce-Robbins** [bullhorn/career-portal#249]
I'm not sure if this has been dealt with or not (couldn't find anything on it), but we are looking to be able to identify the source of all applications through the career portal. Currently all applications are marked as Corporate Career Portal as source regardless which job board they have come from.

**Comment by charlesabarnes** [comment]
Heya Royce, this is something that can be handled within the default career portal.   If the url has a source parameter added to it (`?source=jobBoard`) you are able to define the source of the application.   This source will need to be applied by the job boards that you are using.  

Please let me know if you have any questions

**Comment by Royce-Robbins** [comment]
Thank you!  Figured this already existed but couldn't find it to save me soul.

Cheers!
