### ISSUE TITLE
Brackets and Quotation Mark Showing Up Around City,State

### ISSUE THREAD

**Issue by vjks** [bullhorn/career-portal#250]
- I downloaded version 2.7.0 of the career portal.
- unzipped it
- uploaded to a folder via FTP. 
- After that I added the company name field, Corp Token and Swim lane. 

The issue I'm having is that when I view the career portal, it's showing brackets and quotation mark around the City and the State. Not sure why. Any help is greatly appreciated. 

This is the URL: https://kj2018.wpengine.com/sales-careers/#/jobs

This is what it looks like:
![image](https://user-images.githubusercontent.com/7833090/53765073-ff445780-3e9c-11e9-9136-a31ff343dda2.png)

**Comment by charlesabarnes** [comment]
Hello!

Inside of the ATS, it appears as if your address fields are set to "allow multiple" within your field mapping settings.  If you uncheck that box there this issue will go away. 

Thanks,
