### ISSUE TITLE
Limiting Published Projects by Current Status in Bullhorn

### ISSUE THREAD

**Issue by Royce-Robbins** [bullhorn/career-portal#251]
Are we able to limit published jobs based on their Job Status in Bullhorn?  For example, if a job is moves from "active" to "On Hold", can it be removed from view automatically on the Career Portal?

**Comment by charlesabarnes** [comment]
Hello,
You could use the "additional filter" options to restrict the number of statuses used. You can also customize the portal to exclude that list of statuses.   

Please let me know if you have any more questions about this.
