### ISSUE TITLE
Candidate form option

### ISSUE THREAD

**Issue by msilverio1975** [bullhorn/career-portal#252]
Hi, my client is looking for an option to add a candidate without a job related to. For example for someone looking for an opportunity that is currently not available. Just to keep their info for future opportunities. Is this possible? Thank you.

**Comment by charlesabarnes** [comment]
This is possible, however you are not able to use the public API to do so.  

However, I have seen people have a "general job" of sorts that applicants can get routed to if there are no opportunities that interest them at the time.  This is the easiest route possible.

**Comment by pbearne** [comment]
@msilverio1975 if your client is using WordPress then [Matadorjobs](https://matadorjobs.com/) plugin does this out of the box as it uses the private API
