### ISSUE TITLE
General Apply Button

### ISSUE THREAD

**Issue by bscottroberts** [bullhorn/career-portal#254]
It seems that the only way for a Candidate to Apply in the Career Portal is to select a Job and apply to a single job. We would like for a Candidate to be able to send us their info (resume) even if we currently do not have an open job that their talents match up to.

**Comment by JackCrouse** [comment]
We agree there should be a way for people to submit resumes if there is not a current opening for thie background.  On our Careers page we list the following text to handle situations like you mentioned:
"If you haven’t found a job opportunity that is the right fit for you, we encourage you to forward a resume for future positions. Please send resumes directly to jobs@techssi.com. We look forward to helping you in your career advancement!"

**Comment by Royce-Robbins** [comment]
We solved this by simply adding an Open Job that has a title of "Open to Opportunities" and the JD clearly outlines that this is a means for candidates to ensure we have their latest CV on file for any req.  We've also had our web developers create a button that directs people to that specific job application and we get a lot of applicants through this.  

Note: If you are  using Canvas, you will need to create a specific Job Type that can be filtered out of all reports

**Comment by MichaelDill** [comment]
It definitely makes sense to have a way for Candidates to easily send you their information. My question for you all, is where would these Candidates go in theory? Just to your General Candidate Pool? My worry is that records could make it into the system without recruiters knowing. With web-responses at least we set the published contact to get an email, but with no associated Job, and no web-response, I'm not sure if we would have the capability to generate the same email notification.

**Comment by DRJ28** [comment]
are we expecting "General apply section", in the coming release?

**Comment by pbearne** [comment]
We have this in the Matador Jobs Plugin https://matadorjobs.com/

**Comment by jesus-escobedo** [comment]
Any updates on this issue? If I create a General Job with a title of "Open to Opportunities", how can I make this job to appear always at the top of the rest without caring about the creation date.

**Comment by charlesabarnes** [comment]
This issue is currently waiting on response to the inquiry that @MichaelDill has posted, as it addresses implementation questions that may need to be addressed to implement such a feature.   This can be done through an admittedly hacky workaround by adding a "general apply" job to your portal and adding a link to it in the sidebar, but adding "official" support for this feature will require more polish.   

For now, I am closing this issue as it is lacking in discussion about the feature,
