### ISSUE TITLE
Cover Letter Field

### ISSUE THREAD

**Issue by renaegolden** [bullhorn/career-portal#255]
I'm trying to add a custom field for applicants to upload a cover letter in addition to their resume. I DO NOT need the cover letter to be parsed. 

Is it possible to add a file upload field to the candidate field types?

**Comment by pbearne** [comment]
Hi Renae

We support this in [Matador Jobs WordPress plugin](https://matadorjobs.com) if that helps

**Comment by charlesabarnes** [comment]
Consolidating this issue with the one in found from #100
