### ISSUE TITLE
Submission Date stamp to custom Candidate field

### ISSUE THREAD

**Issue by n-ellison** [bullhorn/career-portal#256]
I would like to have the Submission Date added as a custom field on a candidate's record.  I only need to record the last submission date because the intent is just to show when the candidate last responded to a job.  For existing candidates, I want the Last Submission custom field to append and overwrite the previous date.

How is this possible?  The submission date is passed into Submission record but not into the Candidate record.

**Comment by charlesabarnes** [comment]
Hello, 

This would need to be done with additional custom code on your webserver outside of the career portal potentially.  I would suggest checking out http://bullhorn.github.io/guides/ to get information about the Bullhorn REST API

Thanks
