### ISSUE TITLE
Can I make a resume upload not required?

### ISSUE THREAD

**Issue by kazington** [bullhorn/career-portal#257]
If someone applies to multiple jobs, we end up getting lots of duplicates of their resume which must be deleted individually.  Is there a way to remove upload the requirement completely?
I've scanned through the code and the upload verification seems to be baked in pretty deep, but I'm hoping there's a workaround.
Thanks!

**Comment by charlesabarnes** [comment]
Currently, you are not able to apply to the public-rest API without some form of resume. This is to ensure the record is successfully parsed into the system. You can do one of two things to meet the requirements for a "abbreviated apply".

First, you can utilize the full Bullhorn Rest API to create a candidate record with the information entered in. You can find documentation on this api [here](http://bullhorn.github.io/rest-api-docs/).

The second option is to just send text in the post body if a resume isn't provided. 

You are able to also change the validation for the send button by modifying the[ enableSendButton method found here](https://github.com/bullhorn/career-portal/blob/master/src/app/modal/modal.controller.js#L115). This will need to be done after executing one of the previously mentioned options.

Please let me know if you have any questions.
