### ISSUE TITLE
filter on wordpress page

### ISSUE THREAD

**Issue by kmoskadet** [bullhorn/career-portal#258]
We are running on a hosted wordpress server. and have installed the oscp plugin.
Adding [oscp] on a page displays the job listings for all categories, and has the ability for user to filter.

We want one page to limit listings to job category Health and another page to limit listings to job category Operations.  Can you tell me where to start?

I was hoping that I would be able to just have  [oscp jobCategory="Health"] on one of the pages and [oscp jobCategory="Operations"] on the other.

**Comment by charlesabarnes** [comment]
Hello,

You are able to do this with the settings in the screenshot below on the portal configuration page.  I suggest checking out our [list of portal configuration options](https://github.com/bullhorn/career-portal/wiki/Portal-Configuration-Options) that we make easily changeable. 

![image](https://user-images.githubusercontent.com/4327754/60043050-c830c680-9684-11e9-8a5d-c3eb9e35e105.png)

**Comment by kmoskadet** [comment]
I am not sure how to phrase this.  Are you saying that each wordpress page needs a separate plugin with its own configuration file?

**Comment by pbearne** [comment]
Hi kmoskadet, 

As you are using WordPress plugin Matador Jobs  Might be what you are looking for as we import the jobs into WP the standard WP taxonomy templating works out of the box (you just need to style it)

Reach out for a demo https://matadorjobs.com

Hope this helps

Paul

**Comment by lewispaige** [comment]
I have 2 divisions on my bullhorn account. I already have the career portal set up for one website which represents one division and have now created a new separate website for the new division (new domain name etc). I want to be able to filter only jobs created on the new division for the new website and to not display jobs from the other division. How would you suggest I do this on the career portal plugin? I can see there are some filtering fields but I am unsure how they work?

**Comment by pbearne** [comment]
Hi @lewispaige,

If you can't filter the OSCP Matador Jobs has an add-on that allows you to filter on any field in the Job object 
Reach out for a quick demo.
paul@matadorjobs.com
