### ISSUE TITLE
#258 Follow Up

### ISSUE THREAD

**Issue by MLS3776** [bullhorn/career-portal#259]
Hello,
Going back to #258 that was closed...what we are really trying to do is install the portal code on 6 pages, remove the "category" search filer from the code so that each page is only showing one specific type of category of jobs so for example, page one only shows IT jobs, page 2 shows Business Operations jobs...and page 6 shows ALL jobs with the category search filter intact.  I was told this could be customized in the code but we just need to know where to do that.  Please advise.

**Comment by charlesabarnes** [comment]
Do you have access to the webhost that WordPress was installed on?  For this to work, you would need multiple installations of the career portal currently, and I don't believe WordPress doesn't make that easy with their plugins.

**Comment by pbearne** [comment]
[matador jobs](https://matadorjobs.com) can this using the native taxonomies in WordPress and taxonomy templates

**Comment by MLS3776** [comment]
> Do you have access to the webhost that WordPress was installed on? For this to work, you would need multiple installations of the career portal currently, and I don't believe WordPress doesn't make that easy with their plugins.

Yes, it's already been installed, just right now it's identical and it's showing all jobs on all pages.

**Comment by uuykay** [comment]
It sounds like you need to create different categories for your jobs, look up the category ids for each job category, and look for where the app.json is being requested. In the code, you will need to adjust so each page's app.json that is requested is different.

For example to request jobs which are from category 2000004, this is what your app.json file needs to have

  "additionalJobCriteria": {
    "field": "publishedCategory.id",
    "values": [2000004],
    "sort": "-dateLastPublished"
  },

**Comment by MLS3776** [comment]
Thanks. I thought we tried that but we’ll check again

Michelle Straughn
443-956-8503


On Sep 11, 2019, at 12:36 AM, William Kuang <notifications@github.com<mailto:notifications@github.com>> wrote:


It sounds like you need to create different categories for your jobs, look up the category ids for each job category, and look for where the app.json is being requested. In the code, you will need to adjust so each page's app.json that is requested is different.

For example to request jobs which are from category 2000004, this is what your app.json file needs to have

"additionalJobCriteria": {
"field": "publishedCategory.id<http://publishedCategory.id>",
"values": [2000004],
"sort": "-dateLastPublished"
},
