### ISSUE TITLE
upgrading plugin breaks portal

### ISSUE THREAD

**Issue by RDCApps** [bullhorn/career-portal#260]
I try to upgrade Wordpress plugin from 0.1.2 to the latest 1.0.1 and it breaks

<img width="1302" alt="broken" src="https://user-images.githubusercontent.com/35538024/60617030-66fda700-9d98-11e9-8b20-b4d60bb82c78.png">

**Comment by charlesabarnes** [comment]
Hello @RDCApps,

Between the two versions we added a fair bit of configuration options.  I suggest verifying some of the configuration settings are set on the plugin configuration page. 

Once those are set, you shouldn't see this issue anymore.

Please let me know if you run into anymore problems when setting those options

Thanks.
