### ISSUE TITLE
Gmail email Job Apply

### ISSUE THREAD

**Issue by JEMosher** [bullhorn/career-portal#261]
Some gmail email addresses will not submit when applicant apply's for a job.  Other gmail addresses do work.  Not sure why one address works and others don't.  We have found two addresses that don't so far.  there could be more.

## Current behavior
some gmail addresses work while others don't
-

## Expected behavior

all email addresses should work with out issue.
-

## Steps to replicate behavior

enter problem email address we receive
![error gmail](https://user-images.githubusercontent.com/52763780/61010138-5322e980-a332-11e9-8adc-b91542ecb4a1.JPG)
![accepeted Gmail](https://user-images.githubusercontent.com/52763780/61010147-5918ca80-a332-11e9-9b9c-8d49aeb40770.JPG)

 an error.  Use another address and it works fine.

1.

## Screenshots

__Current__

__Expected__

**Comment by charlesabarnes** [comment]
Hello, 

This is related to a longstanding issue with having the same email address on deleted candidates.  We currently have an open issue to keep track of this internally, and externally we have issue #51

**Comment by JEMosher** [comment]
Hey Charles

So is there not a fox for this issue then? This looks to have been going  on since 2016.  Is that correct?

Regards,
Eric

Dynamic Data Technology Group
720-851-1700 x200 Office
720-851-5034 Fax
303-653-1573 Mobile
888-281-DDTG (3384) Toll Free
