### ISSUE TITLE
Want to show Salary but it is not showing after adding {{::job.salary}} to list file

### ISSUE THREAD

**Issue by thekuljeet** [bullhorn/career-portal#262]
We were able to show job id following steps mentioned here https://github.com/bullhorn/career-portal/issues/109 however, the same way adding Salary field in the list file didn't work. It doesn't show Salary field at all. This is the code
<span class="card-salary ng-binding">{{::job.salary}}</span>
that was added. 
Any help would be appreciated. Thanks.

**Comment by JoshNewbury** [comment]
Make sure you add salary to search.service.js

 static get _fields()

**Comment by thekuljeet** [comment]
Thanks a lot, that helped. Anyway, we could format it with comma-separated, like $ 100,000?

**Comment by charlesabarnes** [comment]
Hello,

You will potentially want to use AngularJS' currency filters.  Here is an article about them. https://docs.angularjs.org/api/ng/filter/currency
