### ISSUE TITLE
Open Source Career Portal LinkedIn source code not flowing through

### ISSUE THREAD

**Issue by Vikki2912** [bullhorn/career-portal#263]
Hi,

We have recently implemented job wrapping via LinkedIn. 
Candidates are directed to our website to apply (Open Source Career Portal), and our URL has been amended accordingly. However applicants are still coming through with source and submission source as Corporate Career Portal.

We have tried the following URLs:
https://www.tribegroup.com/jobs/?jid=2700#?source=LinkedIn
https://www.tribegroup.com/jobs/?jid=2700&source=LinkedIn

Our Web developers have looked at the apply service and made necessary changes to the UAT site and still no luck when testing!

Can anyone shed any light? We've been working on this for weeks!

Thanks :)

**Comment by charlesabarnes** [comment]
Hello, 

It looks like that your site has the career portal iframed in.  The url parameter isn't being passed to the iframe to give the source of `LinkedIn`.  If you for example go to the directly to job then add the url parameter such as https://www.tribegroup.com/career-portal/#/jobs/2897?source=LinkedIn, it will work.

The parameter would possibly have to be passed down somehow.  It looks like a similar system is working to pass the job IDs down to the iframe. 

Please let me know if you have any more questions.

**Comment by Vikki2912** [comment]
Hi Charles,
Thanks for this, the link you provided worked - I have passed on to our Web Developers :)

**Comment by charlesabarnes** [comment]
No problem.  I love seeing the customizations made to your portal. 

Please let me know if you have any more questions
