### ISSUE TITLE
Sass build error

### ISSUE THREAD

**Issue by Dillonsmart** [bullhorn/career-portal#264]
After following the steps to set up and build the application, during the build command, the console error:

"[Sass] Error in plugin 'gulp-sass'" 

Message:
    src\app\sidebar\sidebar.scss
Error: no mixin named tablet
        on line 14 of src/app/sidebar/sidebar.scss
        from line 31 of src/app/index.scss
     @include tablet() {
   -------------^

## Current behavior

- As above 

## Expected behavior

- The application should build successfully after cloning the repo and following the steps found in the README.MD

## Steps to replicate behavior

1. Clone the repo 
2. Follow the steps in the README.MD file 
3. Error with SASS mixins when building the application

## Screenshots
![sass-error](https://user-images.githubusercontent.com/11349121/63085931-a4805300-bf46-11e9-8815-63c632f11a7c.PNG)

__Current__

__Expected__

**Comment by MichaelDill** [comment]
I have been looking into this issue. Something must have changed in how gulp-sass compiles styles. 

I do know that importing '../mixins' into the relevant style files resolves the errors, but I am not sure the styles are compiling correctly.

**Comment by grantholle** [comment]
Styles aren't compiling correctly despite including `mixins.scss`

**Comment by grantholle** [comment]
I take that back, they may be compiling correctly but they're not being injected into the page.

```html
<!-- build:css({.tmp/serve,src}) styles/vendor.css -->
<!-- bower:css -->
<link rel="stylesheet" href="../lib/angular-tooltips/dist/angular-tooltips.min.css" />
<link rel="stylesheet" href="../lib/bullhorn-icons/fonts/Bullhorn-Glyphicons.css" />
<link rel="stylesheet" href="../lib/normalize.css/normalize.css" />
<link rel="stylesheet" href="../lib/roboto-fontface/css/roboto-fontface.css" />
<!-- endbower -->
<!-- endbuild -->

<!-- build:css({.tmp/serve,src}) styles/app.css -->
<!-- inject:css -->
<!-- css files will be automatically insert here -->
<!-- endinject -->
<!-- endbuild -->
```

This magic stuff isn't working

**Comment by grantholle** [comment]
Running `gulp` appears to _build_ this site correctly after including `mixins.scss`, but the problem the auto-inject stuff happens when running `gulp serve` for development

**Comment by fndtn357** [comment]
I have the same error using gulp or gulp build. This is the result with gulp serve (no rendering see pasted img)
"Running gulp appears to build this site correctly after including mixins.scss" How do I do this?
![Career Portal](https://user-images.githubusercontent.com/322631/63555736-14c34180-c510-11e9-8188-90e48554deba.png)

**Comment by grantholle** [comment]
I would start using the [Angular 7 branch](https://github.com/bullhorn/career-portal/tree/oscp-ng7-universal). It uses the same general principle of using the `app.json` to pull in the configuration and it doesn't have the dual bower + npm craziness.

It works pretty much out of the box and is using Bullhorn's "Nova" UI library.

Make sure you change [this line](https://github.com/bullhorn/career-portal/blob/oscp-ng7-universal/src/app/services/settings/settings.service.ts#L27) and I think that was it...

**Comment by charlesabarnes** [comment]
Hello all!

Wanted to chime in here,  I am looking to see if there is a solution out there for this gulp issue, but I am happy to see the discussion about the upcoming potential changes being made to the Career Portal.   The most up to date version of the Angular 7 career portal can be found on the branch `f/ng7`. As Grant mentioned, it is using webpack so you avoid all of this build weirdness that you currently see.  It was also built with [novo-elements](https://github.com/bullhorn/novo-elements), Bullhorn UI component Library, that is used throughout the Bullhorn Platform.

Now, with that out of the way, I have a couple of disclaimers and warnings about that version as it is not complete and has not been thoroughly reviewed. 

First, the portal is intended to run two ways, first is the way that the current AngularJS portal is set up.  If you take that portal, run `npm run build` you will get a bundle of files with the app.json file that you are familiar with that you will need to configure to your specifications.  You can upload that to your static web host of choice and it **_should_** work, (Not thoroughly tested or vetted so please be warned).   The other way to run it is with server side rendering enabled.   I documented this on the readme in the branch, but there are some edgecases that are being identified and fixed.   

I would advise most users to ensure they are watching the repository so they can snap the next stable release as soon as its available.  


As far as the gulp issue at hand, I am investigating a fix and will have an update within 2 hours.   

Please let me know if you have any questions!

**Comment by charlesabarnes** [comment]
Pull, npm install, and you should be good to go
