### ISSUE TITLE
How to Filter with additionalJobCriteria in app.json

### ISSUE THREAD

**Issue by uuykay** [bullhorn/career-portal#269]
Hi there,

I am after a way to request my list of jobs by certain criteria, right now I only need the ability to request jobs that are under a certain department field. 

In the app.json file, I notice there is a additionalJobCriterian key, and I have been able to use this to filter by "title" but I can't seem to figure out how to filter by my "department" field.

Here's a sample that works
  "additionalJobCriteria": {
    "field": "title",
    "values": ["TEST Math and Chem Tutor"],
    "sort": "-dateLastPublished"
  },

How can I do this for my "department" field?

**Comment by charlesabarnes** [comment]
I am unsure of the success that query.  I am going to run a couple of experiments with different combinations, but off the top of my head, I believe you can only filter by job owner.   I will look into this and see what field to query for department

**Comment by uuykay** [comment]
Hey @charlesabarnes thanks for the reply, but I have been testing "additionalJobCriteria" a bit and I can filter on a lot of things including "title", "employmentType", "id" and more if the value is just a simple string.

For example this works:

  "additionalJobCriteria": {
    "field": "employmentType",
    "values": ["Full-Time"],
    "sort": "-dateLastPublished"
  },

![image](https://user-images.githubusercontent.com/32381131/64135070-31bd1600-ce28-11e9-85c0-af4a82e84aca.png)
I've been inspecting the data in the network and these are the fields I can see. My issue is I want to be able to filter by a tagged category, specifically the department, and it seems like I need to request publishedCategory to either a particular id or name, but I can't seem to get it to work.

**Comment by uuykay** [comment]
Ok I think I've figured it out, just in case this helps someone else who stumbles upon this, this is what you need:
  "additionalJobCriteria": {
    "field": "publishedCategory.id",
    "values": [2000000],
    "sort": "-dateLastPublished"
  },

**Comment by charlesabarnes** [comment]
Beat me to the reply! I was just typing a response up.   I think there was a bit of confusion as category and department are two separate entities inside of Bullhorn. 

Please let me know if you have any questions
