### ISSUE TITLE
How to pass in new fields in submission form

### ISSUE THREAD

**Issue by uuykay** [bullhorn/career-portal#270]
Hi Bullhorn team,

I'm trying to add extra fields to the form, and then submit the data so that it is available in the backend https://app.bullhornstaffing.com site.

For example, I have created this field here by editing the Angular code where it says helloWorld

In the apply.service.js file, I have adjusted it so it captures this value, and also adjusts the url where the POST is made. So for the screenshot my url is (note I have hidden my token):

https://public-rest60.bullhornstaffing.com:443/rest-services/RANDOMTOKEN/apply/78/raw?externalID=Resume&type=Resume&firstName=John&lastName=Smith&email=some_random_email%40asdasd.com&phone=123456&customText6=helloWorld&gender=&ethnicity=&veteran=&disability=&format=pdf

In the backend https://app.bullhornstaffing.com site, I used Field Mapping to assign customText6 to the candidate. It is however empty each time.

I found this forum post which says we're not allowed to add parameters to the /raw endpoint. Can someone confirm? How else are we meant to pass across additional parameters?

https://supportforums.bullhorn.com/viewtopic.php?t=22150

![image](https://user-images.githubusercontent.com/32381131/64316448-32a4a200-cff8-11e9-9cd3-ed248483e14f.png)

**Comment by pbearne** [comment]
Hi William,

Yes, I believe you are right you can't add to fields as the OSCP as it uses the public API

That is one of the reasons we use the private API in Matador Jobs. If your site is a WordPress install we have a plugin that will add this field (of any candidate field) to the form with a check of a checkbox.

Reach out in you need more info

Paul
http://matadorjobs.com

**Comment by MichaelDill** [comment]
Hello William,

Custom Text fields can be exposed to the public API, but you will need to contact support, and have them add customText6 to the list of exposed fields in your settings.

**Comment by uuykay** [comment]
Hi there, there seems to be a missing comment from Michael Dill who may have deleted his comment. He mentioned this was possible by contacting support.

So support has replied to be today, however they have given me a client id / secret / username and asked me to generate a password and use the REST docs. My issue though is that this involves a considerable reconfiguration of endpoints to the Angular career portal. Other people seemed to have been able to access these custom fields from support. 

Can someone confirm it is possible to use the same endpoint in the default Angular career portal just by appending the param customText6=helloWorld

**Comment by charlesabarnes** [comment]
That is currently not possible.

**Comment by charlesabarnes** [comment]
We are looking into ways to add additional fields onto the form in the future and expose those fields via the public API, but currently that is not an option.

**Comment by uuykay** [comment]
Hi @charlesabarnes what's confusing me is that this seems like it was possible for the person who submitted the closed issue #244 
https://github.com/bullhorn/career-portal/issues/244

Am I missing something? I have requested support from Bullhorn to open customText6, customText7, customText8 to allow the portal to POST to it so that it receives data.

**Comment by uuykay** [comment]
If I wanted this functionality, is my only option to rejig the Angular Application so that it calls the private API to create a candidate, and then submit that candidate for a specific job and pass the data I want to those 3 custom fields?

**Comment by charlesabarnes** [comment]
Hello,

What that previous post is referring to is exposing certain job fields for filtering and display on the job and job list.  

Currently the only way to add fields is as you mentioned is to modify the portal to use the full API.

**Comment by uuykay** [comment]
Ok thanks for clarifying, after re-reading issue 244 that makes sense. I've been looking at the full API, and I must say I'm getting tripped up even trying to get an authorization code programmatically.

**Comment by charlesabarnes** [comment]
Hey @uuykay what issue are you running into?  Is it an error or something else?

**Comment by uuykay** [comment]
I was getting tripped up with the OAuth section but since this may be due to my lack of experience with this, I will close this issue since you've answered my questions about the limitations.
