### ISSUE TITLE
IE11 List of Jobs Not Shown Access-Control-Allow-Origin Header Issue

### ISSUE THREAD

**Issue by uuykay** [bullhorn/career-portal#271]
The list of jobs are not displayed when using Internet Explorer 11.

## Current behavior

When running the career portal on IE11, the list of jobs does not show up.
-

## Expected behavior

I expect the list of jobs to show up like it does for Chrome etc.
-

## Steps to replicate behavior

1. This can be seen in localhost, you just need to build the application, and then serve it.
2. Open up in IE11. You still see the sidebar but no list of jobs. In the console you see the errors:

SEC7120: Origin http://localhost:3000 not found in Access-Control-Allow-Origin header.
SCRIPT7002: XMLHttpRequest: Network Error 0x80700013, Could not complete the operation due to error 80700013.

## Screenshots

__Current__
![image](https://user-images.githubusercontent.com/32381131/64666666-6c632600-d49a-11e9-87d5-5cfee72093db.png)

__Expected__
![image](https://user-images.githubusercontent.com/32381131/64666691-84d34080-d49a-11e9-8bba-7800592bd37b.png)

**Comment by charlesabarnes** [comment]
The serving strategy has changed in Career Portal V3 and uses angular-cli
