### ISSUE TITLE
Initial startup not working

### ISSUE THREAD

**Issue by huntermetts** [bullhorn/career-portal#281]
Followed the steps to start the application and throws error.
I have git, nodejs, and the angular cli, I have cloned down the repo, I navigated into the directory, and ran npm install as well as npm start.

## Current behavior

App starts up after running npm start and I've only changed the nav header, but throws errors and displays only the loading dots:

<img width="1622" alt="Screen Shot 2019-10-23 at 11 56 56 AM" src="https://user-images.githubusercontent.com/44845206/67416386-64fc6580-f58c-11e9-8ded-8f5a4cce599e.png">

## Expected behavior

Why errors? What do I need to begin running and creating cleanly?

## Steps to replicate behavior

1. Follow the steps in this repo

## Screenshots
Some of the errors my terminal is giving:

<img width="905" alt="Screen Shot 2019-10-23 at 11 51 16 AM" src="https://user-images.githubusercontent.com/44845206/67416542-9f660280-f58c-11e9-8794-67c9ac8dfbb3.png">
<img width="906" alt="Screen Shot 2019-10-23 at 11 51 26 AM" src="https://user-images.githubusercontent.com/44845206/67416543-9f660280-f58c-11e9-9aba-759f3f0e6b74.png">
<img width="529" alt="Screen Shot 2019-10-23 at 11 51 38 AM" src="https://user-images.githubusercontent.com/44845206/67416544-9f660280-f58c-11e9-96b0-43a2dae6c05b.png">

-Thanks

**Comment by charlesabarnes** [comment]
Did you run `npm run build`?  Also can you post your app.json config file?

**Comment by MichaelDill** [comment]
I think this is a translation issue. If you changed the "Nav Header", did you change a string that is accompanied by a `| translate` pipe? It looks like chomsky can't find a string in it's I18n file.

**Comment by huntermetts** [comment]
Thank you for such a quick response!

Yes I ran npm run build and the "companyName" was the only placed I changed the text string or what I described as the "Nav Header".

Here is my app.json file:

<img width="594" alt="Screen Shot 2019-10-23 at 12 22 10 PM" src="https://user-images.githubusercontent.com/44845206/67418297-25d01380-f590-11e9-8c03-3776d56644ac.png">
<img width="510" alt="Screen Shot 2019-10-23 at 12 22 22 PM" src="https://user-images.githubusercontent.com/44845206/67418298-25d01380-f590-11e9-96ae-e441a2ac81e0.png">

**Comment by charlesabarnes** [comment]
This is because the corp token and swimlane isnt set so it can't construct the proper url  (the XMLHTTP request part).    You can get the proper values from Bullhorn Support

**Comment by huntermetts** [comment]
I've entered the corp token and swimlane into the app.json and still the same issue.

**Comment by charlesabarnes** [comment]
Can you post another screenshot of your app.json please?

**Comment by huntermetts** [comment]
<img width="561" alt="Screen Shot 2019-10-24 at 8 07 09 AM" src="https://user-images.githubusercontent.com/44845206/67488380-574eea80-f635-11e9-8a98-692fd4ad7c0c.png">
<img width="500" alt="Screen Shot 2019-10-24 at 8 07 20 AM" src="https://user-images.githubusercontent.com/44845206/67488381-574eea80-f635-11e9-94c4-742c82229fc5.png">

**Comment by charlesabarnes** [comment]
My apologies if I sound redundant, after updating the config, did you rebuild?

If so, what do you see when you go to [siteroot]/app.json?

**Comment by huntermetts** [comment]
No you're totally fine! 

Turns out I was given the wrong swimlane, once I entered the correct one, everything worked as it should. 

Thanks again for the help.

**Comment by charlesabarnes** [comment]
No problem.  

This version is currently in beta so please let me know of any feedback that you have.  

I plan to address a lot of points in #282 and I am looking forward to any suggestions you may have.

**Comment by huntermetts** [comment]
Great. 

I will do that!
