### ISSUE TITLE
Error on npm start

### ISSUE THREAD

**Issue by moosewebdev** [bullhorn/career-portal#283]
I have just followed the install instructions but am receiving this error. Not quite sure what i missed. 

> career-portal@0.0.0 start C:\Users\Adric\Google Drive\Work\practice\career-portal
> node dist/server

internal/modules/cjs/loader.js:596
    throw err;
    ^

Error: Cannot find module 'C:\Users\Adric\Google Drive\Work\practice\career-portal\dist\server'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:240:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:564:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! career-portal@0.0.0 start: `node dist/server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the career-portal@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Adric\AppData\Roaming\npm-cache\_logs\2019-10-24T18_46_35_608Z-debug.log

**Comment by charlesabarnes** [comment]
Can you screenshot the return of 

`npm -v` and `node -v` please?

**Comment by moosewebdev** [comment]
here is the screenshot
![Annotation 2019-10-24 165354](https://user-images.githubusercontent.com/17207170/67524596-0663e400-f67f-11e9-8da1-6ee813de01a6.png)

**Comment by charlesabarnes** [comment]
can you try the following

`rm -rf node_modules && npm install && npm run build`

then start to see if that works.

**Comment by moosewebdev** [comment]
i get an error

At line:1 char:21
+ rm -rf node_modules & npm install & npm run build
+                     ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks 
("&") to pass it as part of a string.
At line:1 char:35
+ rm -rf node_modules & npm install & npm run build
+                                   ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks 
("&") to pass it as part of a string.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : AmpersandNotAllowed

**Comment by moosewebdev** [comment]
but i ran the build just to try it and it worked. So then i went back and ran npm start and it works. it is showing the loading circles  when i open local host.

**Comment by moosewebdev** [comment]
Is there a demo swim lane and other credentials i can use while my client gets theirs. Only for dev purposes of course.

**Comment by charlesabarnes** [comment]
Hello, we currently don't have any publicly available.  We will look into having public creds in the future.
