### ISSUE TITLE
Jobs are not showing up

### ISSUE THREAD

**Issue by amrt0510** [bullhorn/career-portal#29]
Hi there,

I have downloaded and configured the repo as described in here https://github.com/bullhorn/career-portal/wiki/Downloading-and-Configuring . But when i set this up on my local machine, it is not showing up any jobs. 

I also pushed it to live, with the same configuration. But same error is there. 
I found that api is not responding in a way it should be. Throwing 500 internal server error to all the requests.

http://screencloud.net/v/oxUi 

Request headers: 
GET /rest-services/1BTV61/search/JobOrder?showTotalMatched=true&query=(isOpen:1)&fields=id&sort=id&count=500&start=0 HTTP/1.1
Host: public-rest5.bullhornstaffing.com
Connection: keep-alive
Accept: application/json, text/plain, */*
Origin: http://104.131.137.250
User-Agent: Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36
Referer: http://104.131.137.250/careerportal/index.html
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8,hi;q=0.6

Response: 
{
  "errorMessage" : "an internal error has occurred"
}

Thank you.

**Comment by jgodi** [comment]
I am sorry that it isn't working for you at the moment. Could you possibly provide the contents of your `app.json` or the URL of the live application? That will help us figure out why this isn't working.

Thanks!

**Comment by TheReal** [comment]
@amrt0510 In addition to @jgodi 's request, have you been in contact with Bullhorn Customer Care to activate the public API endpoint necessary for Career Portal use? If no, we can assist by directing a Customer Care specialist your way.

**Comment by TheReal** [comment]
Hey @amrt0510 after some digging it appears that your customer/client public API is not yet configured; a small but necessary step. @jgodi and I will have Customer Care connect with you, get your client configured and ready to go. Since today is a holiday, plan on hearing from them tomorrow or afterwards. Let us know how it turns out!

**Comment by amrt0510** [comment]
Hi @jgodi and @TheReal 
Thanks for the early response,

Here is the URL where you can see the application running http://104.131.137.250/careerportal/index.htm.

Okay let me inform my client about configuring public API access.
Thank You.

**Comment by TheReal** [comment]
@amrt0510 Just following up to make sure you've got what you needed from Bullhorn Customer Care. Are you up and running?

**Comment by amrt0510** [comment]
@TheReal  Thanks. Its working now.

**Comment by PuneetChawla123** [comment]
Hello,

I have downloaded and configured the repo as described in here https://github.com/bullhorn/career-portal/wiki/Downloading-and-Configuring . But it doesn't show any job. It says, **there are no jobs matching the criteria**.

http://poolingmate.com/test/index.html#/jobs
