### ISSUE TITLE
Sitemap not being generated

### ISSUE THREAD

**Issue by Dillonsmart** [bullhorn/career-portal#295]
After cloning the master repo, and running npm start / npm build there is no sitemap or feed directories for sitemap file. 

## Current behavior

- Sitemap not being generated

## Expected behavior

- Sitemap file, root/sitemap directory and root/feed directory to be created

**Comment by charlesabarnes** [comment]
Hello!
When you say it's not being generated, in your browser, when you go to localhost:4000/sitemap, the xml isn't generated? 

The file isn't cached or saved on the server to always deliver the newest jobs

**Comment by Dillonsmart** [comment]
Correct, when navigating to http://localhost:4200/sitemap after using npm run serve the application redriects back to http://localhost:4200/#/

**Comment by charlesabarnes** [comment]
`npm run serve` generates the static version of the site `npm start` is the one that uses node & generates information on the server side.   I know we are working through these issues to get it working with you on #296.

**Comment by Dillonsmart** [comment]
Ok, thank you @charlesabarnes
