### ISSUE TITLE
Npm start failed

### ISSUE THREAD

**Issue by Dillonsmart** [bullhorn/career-portal#296]
Error: (node:19432) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

## Current behavior

- npm start fails on latest build 

## Expected behavior

- npm start should run /dist/server.js

## Steps to replicate behavior

1. In terminal run: npm start

## Screenshots

![npm-start](https://user-images.githubusercontent.com/11349121/69142020-d6610280-0abd-11ea-8972-7a609b5c4e86.JPG)

**Comment by charlesabarnes** [comment]
What version of node are you using?

**Comment by Dillonsmart** [comment]
> What version of node are you using?

v10.5.0

**Comment by charlesabarnes** [comment]
That version should be fine....

I am on 10.12.0 myself, it handles that message as a warning and doesnt throw an error.  

As a troubleshooting step can you try running `rm -rf node_modules/ && npm install && npm run build && npm start`?

**Comment by Dillonsmart** [comment]
Hi @charlesabarnes , I am still getting warnings about the deprecated Buffer() function, but it didnt fall over when running ```npm start```. 

The application has built and started successfully, and the sitemap is generated.

Thanks @charlesabarnes

**Comment by charlesabarnes** [comment]
Perfect!  

That warning will hopefully be addressed in Angular, but I will be looking to see if I can work around it on my end.  

Angular issue for reference: 

angular/angular#32897
