### ISSUE TITLE
Multi-page form for application?

### ISSUE THREAD

**Issue by huntermetts** [bullhorn/career-portal#297]
Is there a way to easily break the application modal into separate pages? 

Say after the first 10 questions I would click a "next" button and that would take me to the next 10 questions? Thank you.

**Comment by charlesabarnes** [comment]
You are able to make the app utilize a [stepper](http://bullhorn.github.io/novo-elements/#/layouts/stepper)

**Comment by huntermetts** [comment]
Perfect thank you for the reference and quick response.
