### ISSUE TITLE
Wordpress Plugin Customization

### ISSUE THREAD

**Issue by sameer458** [bullhorn/career-portal#298]
How can we style the wordpress plugin for bullhorn? i have not found any documents related to that. Can you please share the document or the details regarding the styling of this plugin on WordPress.

**Comment by charlesabarnes** [comment]
Hello, 

for the wordpress Plugin, we do not suggest styling the plugin directly as the style changes could be overridden by an update.  

If you would like to make customizations, I suggest forking the repository and making your changes to your forked repository.  Once your customizations are done, you are able to test the changes by [building](https://github.com/bullhorn/career-portal#building) the portal

**Comment by sameer458** [comment]
ok, I understand but which files do I have to edit to style? as I can see any files related to that. there's custom.css file in the plugin but styling is not working at all.

**Comment by charlesabarnes** [comment]
Since the project has multiple files used for styling there are several approaches that can be taken to have the styles appear.   If the project has been forked, you can make the updates in https://github.com/bullhorn/career-portal/blob/master/src/styles.scss if you would like the updates all in one place.  custom.css file is another option, but you will need to override existing styles so your rules would need to be particularly specific or you must use `!important`.

You are are also able edit the individual component's files as well such as https://github.com/bullhorn/career-portal/blob/master/src/app/job-list/job-list.component.scss

**Comment by sameer458** [comment]
i have tried custom.css option and it's not working at all. tried different things and it's not working. as i am using wordpress plugin on website so i don't see any file in a directory like the above you mentioned.

**Comment by charlesabarnes** [comment]
Yes, you may need to make your customizations outside of the plugin and clone this [source code repository](https://github.com/bullhorn/career-portal)

**Comment by sameer458** [comment]
So you mean to say we can't edit the wordpress plugin directly?

**Comment by charlesabarnes** [comment]
It's possible but not suggested since the next time you upgrade, your changes will be overwritten

**Comment by sameer458** [comment]
got it. i can see 2 CSS files in there but the changes i make in CSS are not visible on the main product. can you please tell me which files do i have to edit? as the files you have suggested are not there in wordpress plugin. i can take care of overwriting issue.

**Comment by charlesabarnes** [comment]
In the static directory you will want to update custom.css.   If your style changes are not working, can you provide the url of your portal so I can take a look?

**Comment by sameer458** [comment]
i tried. the portal is visible here. https://bit.ly/350MaUc
shorten the url for privacy concerns. 

all the styling bullhorn currently have are not from the plugin css file at all.

**Comment by charlesabarnes** [comment]
I have taken a look at the custom.css file and I currently see that it is empty. can you add the styles that you are attempting to make work?
