### ISSUE TITLE
Web page reporting bad Corp Token

### ISSUE THREAD

**Issue by jaherath** [bullhorn/career-portal#299]
Implementing the Career Portal. I received a Swim Lane and Corporate Token from Bullhorn support.  I triple-checked the token entered on the Plugin, and it is correct, but the web site is throwing an error saying the token is bad.

This is the text of the error: 
ERROR 
{…}

error: Object { errorMessage: "Bad corp token", errorMessageKey: "errors.badCorpToken" }

headers: Object { normalizedNames: Map(0), lazyUpdate: null, lazyInit: lazyInit() }

message: "Http failure response for https://public-rest41.bullhornstaffing.com/rest-services/40MAA1/search/JobOrder?query=(isOpen:1)%20AND%20(isDeleted:0)&count=500&fields=id&sort=id: 400 Bad Request"

name: "HttpErrorResponse"

ok: false

status: 400

statusText: "Bad Request"

url: "https://public-rest41.bullhornstaffing.com/rest-services/40MAA1/search/JobOrder?query=(isOpen:1)%20AND%20(isDeleted:0)&count=500&fields=id&sort=id"

<prototype>: Object { constructor: t() }
core.js.pre-build-optimizer.js:14597:18

## Current behavior

-Error on web site

## Expected behavior

-Career portal displays jobs published from Bullhorn

## Steps to replicate behavior

1.https://barfieldrevenue.com/bull-horn/   Password:  bullhorn

## Screenshots

__Current__
![image](https://user-images.githubusercontent.com/58703156/70460586-b3a28800-1a84-11ea-93dc-585fc24f6269.png)

![image](https://user-images.githubusercontent.com/58703156/70460700-efd5e880-1a84-11ea-9877-e0974a36925a.png)

__Expected__

**Comment by charlesabarnes** [comment]
Its possible that the token provided was incorrect, you may want to double check with Bullhorn Support for this

**Comment by jaherath** [comment]
Thank you.  I checked with support.  They gave me the same token.  When I verified it was the same that was entered into the plugin, they sent me to you.

John Herath
General Manager
Barfield Revenue Consulting
(919) 417-4405
john@barfieldrevenue.com<mailto:john@barfieldrevenue.com>
[A picture containing clipart  Description automatically generated]<https://barfieldrevenue.com/>
[cid:image004.png@01D56931.3E3E6C50]<https://www.linkedin.com/company/barfieldrevenue/>[cid:image006.png@01D56931.3E3E6C50]<https://www.facebook.com/barfieldrevenue/>[cid:image008.png@01D56931.3E3E6C50]<https://www.instagram.com/barfieldrevenue/>[cid:image010.png@01D56931.3E3E6C50]<https://twitter.com/willb_brc>

**Comment by charlesabarnes** [comment]
Hello I am tracking this down internally.   But just in case I wanted to check something real quick to be sure.  Are you sure that 0 is not an O?   I switched the corp token to 4OMAA1 and it worked.

**Comment by jaherath** [comment]
Charles,
You were correct.  I switched it from a 0 to an O and it worked.  What a great catch.  I feel a little stupid.  Kind of like the, “Is it plugged in?” question.

Thank you so much!


John Herath
General Manager
Barfield Revenue Consulting
(919) 417-4405
john@barfieldrevenue.com<mailto:john@barfieldrevenue.com>
[A picture containing clipart  Description automatically generated]<https://barfieldrevenue.com/>
[cid:image004.png@01D56931.3E3E6C50]<https://www.linkedin.com/company/barfieldrevenue/>[cid:image006.png@01D56931.3E3E6C50]<https://www.facebook.com/barfieldrevenue/>[cid:image008.png@01D56931.3E3E6C50]<https://www.instagram.com/barfieldrevenue/>[cid:image010.png@01D56931.3E3E6C50]<https://twitter.com/willb_brc>
