### ISSUE TITLE
Error 500 when communicating with BullHorn server

### ISSUE THREAD

**Issue by hsdhillon** [bullhorn/career-portal#30]
Hi,

I configured the career-portal following the instructions on Wiki page and home page but having trouble getting it to work. Looking at the browser console, I see the error 500 when connecting to bullhorn backend server. Here is the URL.. (value of CORP_TOKEN is changed in below URL for privacy)

https://public-rest31.bullhornstaffing.com/rest-services/XXXXXX/query/JobBoardPost?where=(isOpen=true)&fields=id,title,publishedCategory(id,name),address(city,state),employmentType,dateLastPublished,publicDescription,isOpen,isPublic,isDeleted&count=20&orderBy=-dateLastPublished&start=0

I did work with BullHorn support to enable the API on our backend and got CORP_TOKEN and SWIMLANE values from them. In addition to that, I also got the Client ID, Client Secret, Username, Password etc from them. But I couldn't figure out where to use these values when configuring career-portal. Documentation only makes reference to CORP_TOKEN and SWIMLANE when building the portal.

Any help is really appreciated.

**Comment by jgodi** [comment]
Thank you for reaching out. A person from support will be contacting you shortly. To do this, can we get a public endpoint or url for the client so that we can help debug the situation?

Thanks,
Joshua

**Comment by hsdhillon** [comment]
Thanks Joshua!
Here is the URL... http://li1262-218.members.linode.com:3002/

**Comment by hsdhillon** [comment]
Joshua,

Just an update. This was resolved with the help of BullHorn support team.

Even though we received the API details from support team, there was an additional step where we need to fill out an application and send to BullHorn team to enable the portal for API access.

**Comment by jgodi** [comment]
Glad to hear it is all working! Let us know if you need anything else.
