### ISSUE TITLE
MailTo Link On Job Page Removes Characters After Ampersand

### ISSUE THREAD

**Issue by kkbarimah** [bullhorn/career-portal#305]
On the job page in the OSCP, when attempting to share by email a job with an ampersand in the title, the body of the email is not properly sent to the email program.

## Current behavior

- The body of the e-mail is cut off where the ampersand starts. For example, if the job title is "Communications & Marketing Specialist" the body of the e-mail will say "Check out this Communications"

## Expected behavior

- Full position title should be displayed in the body of the e-mail when the title includes an ampersand. 

## Steps to replicate behavior

1. Navigate to an OSCP with a job containing an ampersand. e.g.: "M&A Manager"

2. Share > Email

3.  Observe in the email that opens the body reads "Check out this M"

4. Inspect the email share button and observe the & character in the mailto link:
`<a data-ng-href="mailto:?subject=M%26A%20Manager&amp;body=Check out this M&amp;A Manager job: http%3A%2F%2Fwww.acmeco.com%2F%23%2Fjobs%2F6" href="mailto:?subject=M%26A%20Manager&amp;body=Check out this M&amp;A Manager job: http%3A%2F%2Fwww.acmeco.com%2F%23%2Fjobs%2F6"><i class="bhi-email"></i></a>`

5. Edit the element and encode the ampersand:
`<a data-ng-href="mailto:?subject=M%26A%20Manager&amp;body=Check out this M%26A Manager job: http%3A%2F%2Fwww.acmeco.com%2F%23%2Fjobs%2F6" href="mailto:?subject=M%26A%20Manager&amp;body=Check out this M%26A Manager job: http%3A%2F%2Fwww.acmeco.com%2F%23%2Fjobs%2F6"><i class="bhi-email"></i></a>`

6. Click the email button again

7. Observe the email body reads "Check out this M&A Manager job: http://www.acmeco.com/#/jobs/6"

**Comment by charlesabarnes** [comment]
This will be fixed in the next version release the career portal
