### ISSUE TITLE
OSCP showing 'Not Secure'

### ISSUE THREAD

**Issue by maugusti0001** [bullhorn/career-portal#307]
Michael has set up the Career Portal through Wix and Amazon posting - the portal is working correctly though it says 'Not Secure' in the URL.
I saw a Support ticket recommending to 'Enable the 'Require Secure Connections (HTTPS)' on the site.' but Michael is unsure how to do this.

Website is https://www.talentedrecruitmentgroup.com/
Click current vacancies > Career Portal
Leading to Career Portal here: http://talentedrecruitmentgroupcareers.s3-website.eu-west-2.amazonaws.com/#/

Is there anything we could advise to help resolve this?

**Issue created by Holly Jackson on behalf of Michael Augusti.

**Comment by charlesabarnes** [comment]
Since it appears as AWS S3 is being used, you may want to use [AWS cloudfront](https://aws.amazon.com/premiumsupport/knowledge-center/cloudfront-https-requests-s3/) to serve the career portal content. There are other options to accomplish this, but its the only solution that I have personally used.
