### ISSUE TITLE
Custom URLs / Job Function / View More Button / Tracking Applicants

### ISSUE THREAD

**Issue by kdbrightwing** [bullhorn/career-portal#308]
1. How do we create custom URLs for each job? When I click on a job the URL does not change. OR when I filter by a category the URL does not change.

2. When I post a job through Bullhorn it pulls whatever is in the Job Function dropdown into the category field on the OSCP. If I later change the job function in Bullhorn, it does not make the change on the website, even if I unpublish and republish.

3. How do we replace the scrollbar with a "Load More" button underneath a certain amount of jobs?

4. What is the best way to track candidate job applications in Bullhorn. It shows up under web activity in the job record, but how can we pull a list of all candidates who have applied? It does not add a note to the candidate record or change the source field.

**Comment by charlesabarnes** [comment]
1. Each job has a different URL with an id to denote each job.  If you would like to update the url, you can update the route to include it on the job.
2. The job category field on the publish page needs to be updated for it to reflect in the career portal. This is the "published category" field
3. This is default functionality.  Off of the top of my head we return 20 at a time and show a load more button at the bottom of the list.
4. Each web response gets added in Bullhorn as a submission.  You can filter for web responses on that page, or search for submissions in status of new lead.  Inside of Bullhorn, on the submission tab, it also shows you application activity on the Candidate and Placement.

Please let me know if you have any more questions

**Comment by kdbrightwing** [comment]
1. How do I update the "route"? Where is that located?

2. There is no category on my publish page. Is this because we're on an old version of Bullhorn? Screenshot below.

3. Does this mean once I have more than 20 jobs posted it should switch to a load more button? I have 21 jobs posted and it's still just a scroll bar.

4. Thank you.

![image](https://user-images.githubusercontent.com/62020614/76326960-c0bb5700-62bf-11ea-9905-fc5634c83f49.png)

**Comment by charlesabarnes** [comment]
1) this needs to be done by modifying the code of the portal. Part of this can be manipulated in the app.module.ts file.  The other part that would need to be modified is the job-details page.

2) there is a setting on our end that needs to be updated so you can properly publish your jobs.  Please contact Bullhorn Support to have the setting changed for your career portal.

3) I was incorrect about the threshold value. I checked in the code and it's set to 30, my apologies
