### ISSUE TITLE
Change URL construct

### ISSUE THREAD

**Issue by emmanrs** [bullhorn/career-portal#309]
Hi, 

How do we change the URL construct? Instead of #/jobs/1234
We need it to be jobs/job-advertisement-title/1234

Basically what we need is to have the job title and id at the last part and remove #.

Thanks.

**Comment by pbearne** [comment]
I don't think you can do that with OSCP but you can with Matador Jobs https://matadorjobs.com/

**Comment by charlesabarnes** [comment]
Hello, you will want to modify the route structure for job details in [app.module.ts](https://github.com/bullhorn/career-portal/blob/master/src/app/app.module.ts).  

Next you will also want to modify how the jobs are loaded in the job details component. 

Finally the job list has to be modified so job urls work with the new format.  This happens in [job-list.component](https://github.com/bullhorn/career-portal/blob/master/src/app/job-list/job-list.component.ts)

Please let me know if you have any more questions

**Comment by emmanrs** [comment]
Hi @charlesabarnes, thanks. It worked, but I still have issues with #..

**Comment by charlesabarnes** [comment]
[Hash location strategy](https://angular.io/api/common/HashLocationStrategy) handles that.  you can set that in the app.module [here](https://github.com/bullhorn/career-portal/blob/master/src/app/app.module.ts#L74)

**Comment by emmanrs** [comment]
alright, thanks! :)

**Comment by emmanrs** [comment]
Hi @charlesabarnes, just one last thing, I realized that the URL for title is undefined in, im getting
/jobs/undefined/1234

What's correct way to call it? I tried
jobTitle
title

Thanks. sorry, I'm just new to Angular..

**Comment by charlesabarnes** [comment]
Its like the interpolation in the `<item-title>` tags.  It would be `job.title`

**Comment by mukoy** [comment]
Hi @charlesabarnes, thank so much for you continued support, however, I'm still not able to materialize what the company needs..I tried the following:

this.router.navigate([`jobs/{{job.title}}/${jobId}`]);
and 
this.router.navigate([`jobs/{job.title}/${jobId}`]);

url will be like this
#/jobs/%7Bjob.title%7D/9495

Thanks.

**Comment by charlesabarnes** [comment]
oh you are in a different part than I anticipated, you have to modify the method to accept the job title as well.  Then you can use [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) or string concatenation to form the url

**Comment by mukoy** [comment]
Hi @charlesabarnes, how do we to this "you have to modify the method to accept the job title"? thanks
