### ISSUE TITLE
AWS S3 - Error please refresh message 

### ISSUE THREAD

**Issue by Fortis-Siobh** [bullhorn/career-portal#310]
Hi all - 

I have followed instructions from the below:
https://github.com/bullhorn/career-portal/wiki
then
https://github.com/bullhorn/career-portal/wiki/Downloading-and-Configuring

We cannot host as our Domain is with Wix so AWS was suggested as an alternative. Used this: https://github.com/bullhorn/career-portal/wiki/Uploading-to-Amazon-AWS-S3

Buckets created - files uploaded - testing in Static website hosting but not working.

I tried both the latest and previous versions to upload to the S3 bucket but page is not loading - they all give me this message - An error has occurred while loading. Please refresh the page and try again.

Thanks

**Comment by charlesabarnes** [comment]
Can you provide a link to your portal?

**Comment by Fortis-Siobh** [comment]
http://fortis-rec-dub.s3-website-eu-west-1.amazonaws.com

**Comment by charlesabarnes** [comment]
It appears as if you need to reach out to Bullhorn Support to ensure all of the enablement steps has been completed.  It appears as if everything is set up correctly on your end. 

Please let me know if you have any questions

**Comment by sadeeqaji** [comment]
Hi Fortis. How did you fix your issue?
