### ISSUE TITLE
OSCP not responding

### ISSUE THREAD

**Issue by staceyeschneider** [bullhorn/career-portal#312]
After the latest updates to standard Wordpress (version 5.3.2), the plugin stopped returning values to our jobs page. It is untested with this version. The page now says: 

An error has occurred while loading. Please refresh the page and try again.

Further looking into it shows that there are a series of 500 errors:

Failed to load resource: the server responded with a status of 500 (Internal Server Error)
public-rest41.bullhornstaffing.com/rest-services/DNKE1/search/JobOrder?query=(isOpen:1)%20AND%20(isDeleted:0)&count=500&fields=id&sort=id:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
main.js:1 ERROR theaders: e {normalizedNames: Map(0), lazyUpdate: null, lazyInit: ƒ}status: 500statusText: "Internal Server Error"url: "https://public-rest41.bullhornstaffing.com/rest-services/DNKE1/search/JobOrder?query=(isOpen:1)%20AND%20(isDeleted:0)&count=500&fields=id&sort=id"ok: falsename: "HttpErrorResponse"message: "Http failure response for https://public-rest41.bullhornstaffing.com/rest-services/DNKE1/search/JobOrder?query=(isOpen:1)%20AND%20(isDeleted:0)&count=500&fields=id&sort=id: 500 Internal Server Error"error: {errorMessage: "An internal error has occurred", errorMessageKey: "errors.internalError"}__proto__: Object
ah @ main.js:1
public-rest41.bullhornstaffing.com/rest-services/DNKE1/search/JobOrder?query=(isOpen:1)%20AND%20(isDeleted:0)&count=500&fields=id&sort=id:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
main.js:1 ERROR t
ah @ main.js:1
public-rest41.bullhornstaffing.com/rest-services/DNKE1/search/JobOrder?query=(isOpen:1)%20AND%20(isDeleted:0)&count=500&fields=id&sort=id:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
main.js:1 ERROR t
ah @ main.js:1

-

Previously it returned open jobs.

-

To see the page https://elev8staffing.com/job-search/

**Comment by charlesabarnes** [comment]
Heya, 

this looks like it is unrelated to the career portal and the update of the plugin, but it is more related to the setup on the Bullhorn side.  I suggest reaching out to Bullhorn support as it appears to be something related to your unassigned user.
