### ISSUE TITLE
Bullhorn/Wordpress plugin Issu

### ISSUE THREAD

**Issue by epelosi** [bullhorn/career-portal#313]
After installing the Wordpress plugin for Bullhorn, the integration pulls the job list but it will not pull the job details when you click on the jobs. 

## Current behavior

- The plugin works fine on published Wordpress page but once you click on any job, I get a white screen.

## Expected behavior

- It should open the job details and the ability to attach your resume to apply for the job.

## Steps to replicate behavior

1. Open webpage
2. Click on job
3. See white screen

__Current__

![screenshot 1](https://user-images.githubusercontent.com/47252504/77643996-b7c0bb80-6f36-11ea-96d7-f6e130fce1d3.JPG)

![image](https://user-images.githubusercontent.com/47252504/77644045-ce671280-6f36-11ea-9505-38c7f848dbca.png)

__Expected__

![image (2)](https://user-images.githubusercontent.com/47252504/77644171-053d2880-6f37-11ea-9154-f032094f780b.png)

**Comment by charlesabarnes** [comment]
Hello, it appears as if the data for job location isn't being returned. This can be adjusted through simple configuration.

In the WordPress configuration page, you need to add `address(city,state)` in to ensure that the data is there to use on the jobs.

Please let me know if you have any questions

**Comment by epelosi** [comment]
Adding  address(city,state) did not work, I am still receiving a blank
white screen when clicking on a job.


Best,

Erica Pelosi

Marketing Manager

*TREELINE*

591 North Avenue, Ste. 1
<https://maps.google.com/?q=591+North+Avenue,+Ste.+1+%0D%0A+Wakefield,+MA+01880&entry=gmail&source=g>

Wakefield, MA 01880
<https://maps.google.com/?q=591+North+Avenue,+Ste.+1+%0D%0A+Wakefield,+MA+01880&entry=gmail&source=g>

781-876-8105
pelosi@treelineinc.com <pelosi@treeline-inc.com>

www.treelineinc.com <http://www.treeline-inc.com/>


*https://www.linkedin.com/in/erica-pelosi/
<https://www.linkedin.com/in/erica-pelosi/> *
<https://www.linkedin.com/company/treelineinc/>

**Comment by charlesabarnes** [comment]
Can you post a screenshot of your portal configuration where is included?

**Comment by epelosi** [comment]
[image: image.png]

[image: image.png]

[image: image.png]


Best,

Erica Pelosi

Marketing Manager

*TREELINE*

591 North Avenue, Ste. 1
<https://maps.google.com/?q=591+North+Avenue,+Ste.+1+%0D%0A+Wakefield,+MA+01880&entry=gmail&source=g>

Wakefield, MA 01880
<https://maps.google.com/?q=591+North+Avenue,+Ste.+1+%0D%0A+Wakefield,+MA+01880&entry=gmail&source=g>

781-876-8105
pelosi@treelineinc.com <pelosi@treeline-inc.com>

www.treelineinc.com <http://www.treeline-inc.com/>


*https://www.linkedin.com/in/erica-pelosi/
<https://www.linkedin.com/in/erica-pelosi/> *
<https://www.linkedin.com/company/treelineinc/>

**Comment by charlesabarnes** [comment]
Hello, email replies to issues appear to not show the images, can you post them to the issue thread?

**Comment by epelosi** [comment]
[image: image (3).png]
[image: image (4).png]

[image: image (5).png]


Best,

Erica Pelosi

Marketing Manager

*TREELINE*

591 North Avenue, Ste. 1
<https://maps.google.com/?q=591+North+Avenue,+Ste.+1+%0D%0A+Wakefield,+MA+01880&entry=gmail&source=g>

Wakefield, MA 01880
<https://maps.google.com/?q=591+North+Avenue,+Ste.+1+%0D%0A+Wakefield,+MA+01880&entry=gmail&source=g>

781-876-8105
pelosi@treelineinc.com <pelosi@treeline-inc.com>

www.treelineinc.com <http://www.treeline-inc.com/>


*https://www.linkedin.com/in/erica-pelosi/
<https://www.linkedin.com/in/erica-pelosi/> *
<https://www.linkedin.com/company/treelineinc/>
