### ISSUE TITLE
Add new fields to submission/apply form

### ISSUE THREAD

**Issue by jesus-escobedo** [bullhorn/career-portal#314]
Hello BullHorn team.

I am trying to add custom fields to the "apply" modal form of a job (when a candidate is reading the details of a job and clics on the Apply button) and I know this question may have been asked several times before and actually the most recent issue related to this topic is [#270](https://github.com/bullhorn/career-portal/issues/270) and the answer from support team was that "it was not possible" but were "looking into ways to add additional fields onto the form in the future", so I just want to make a follow up on this and wanted to know if it is currently possible??
 
thanks in advance.

**Comment by pbearne** [comment]
Have you checked out the [Matador Jobs]( https://matadorjobs.com/) Plugin? We can add any field in the candidate object to any form in a couple of checkboxes ticks

Paul

**Comment by charlesabarnes** [comment]
The public API that the career portal uses only supports adding data directly to EEOC fields, first and last name fields, phone number, and email in addition to any information parsed from the resume.  The portal can be converted to use the full API, however, that will involve adding a backend that the career portal can connect to.  

Please let me know if you have any questions.

**Comment by adilJamshad** [comment]
> The public API that the career portal uses only supports adding data directly to EEOC fields, first and last name fields, phone number, and email in addition to any information parsed from the resume. The portal can be converted to use the full API, however, that will involve adding a backend that the career portal can connect to.
> 
> Please let me know if you have any questions.

Hi Charles,

I have received the Full API access. But my motive is to create a few new fields to submission/apply form of OSCP. Is there any guide which can be helpful in upgrading OSCP from public api to full private api? If not, is there any helpful resource which can guide me where to start?

Thank you

**Comment by pbearne** [comment]
@adilJamshad you will have problems First you are going to have to add oAuth2 just to login then use the docs to map the fields
this is not a trivial task. 
The cost of your time is going to more than using [Matador Jobs](https://matadorjobs.com/) on a WordPress install!! 
Get your client to reach out for a demo
