### ISSUE TITLE
Some fields mapping to correct spot in new lead, some undefined.

### ISSUE THREAD

**Issue by huntermetts** [bullhorn/career-portal#315]
Hello there!

I've been able to get the front-end of the career portal to where I would like.
However, when I click "apply" and the ```this.applyService.apply``` function runs, my network output looks like this ⬇️
<img width="1674" alt="Screen Shot 2020-04-06 at 8 18 14 AM" src="https://user-images.githubusercontent.com/44845206/78563434-925a6a00-77e0-11ea-9ab9-d25a54d47777.png">

Which I think is exactly what's supposed to happen (a good sign), but under the "headers" section my query string parameters look like this ⬇️
<img width="809" alt="Screen Shot 2020-04-06 at 8 30 30 AM" src="https://user-images.githubusercontent.com/44845206/78563771-1dd3fb00-77e1-11ea-84d1-8e9b739299d8.png">

There are 3 implementation roadblocks I'm facing.

The first is that there are about 70 fields total in this application, but ONLY the required fields are being passed into the query params. How can I pass ALL values, even if the applicant doesn't fill them out?

The second roadblock is that I filled out the info, but for "typeOfWorkDesired", but "undefined" is passed in. I'm not sure what I did to get it to record some of the info, but not some of the others.

Third would be in the actual Bullhorn Recruiting App only some of those values are making it into the new candidate record. ⬇️
<img width="1502" alt="Screen Shot 2020-04-06 at 8 39 20 AM" src="https://user-images.githubusercontent.com/44845206/78564864-adc67480-77e2-11ea-926c-2eac7112aa7d.png">

<img width="1500" alt="Screen Shot 2020-04-06 at 8 39 57 AM" src="https://user-images.githubusercontent.com/44845206/78564874-b0c16500-77e2-11ea-9f17-f3dde3f84eb3.png">

<img width="1497" alt="Screen Shot 2020-04-06 at 8 40 13 AM" src="https://user-images.githubusercontent.com/44845206/78564892-b4ed8280-77e2-11ea-851d-8d06ea37a427.png">

<img width="1500" alt="Screen Shot 2020-04-06 at 8 40 25 AM" src="https://user-images.githubusercontent.com/44845206/78564910-bb7bfa00-77e2-11ea-9dc8-c140a88d7a55.png">

Why would only a couple values make it into the new candidate record? And how can I get all the values to make it in. I've set up all the field mappings to match up, but the above photos are my result.

I hope this makes sense and my questions are clearly articulated. 
If you need code provided or anything else to help on your end please let me know.

**Comment by pbearne** [comment]
Hi 

I am going to guess that part of your problem is that the public API doesn't support all the candidate fields you are trying to save you may need to use the Private API and I don't know the OSCP can support it.

I know you don't want to hear this but this is a solved problem in the [Matador Jobs ](https://matadorjobs.com/) plugin. Talk to us!

Paul

**Comment by charlesabarnes** [comment]
Hello!

Paul is correct, the public API doesn't support the full list of fields that you are attempting to use.   If you have any more questions about this. Please let me know.
