### ISSUE TITLE
Application Form

### ISSUE THREAD

**Issue by mukoy** [bullhorn/career-portal#316]
Hi, 

1. How do you disable/remove the attachment on application form?
2. If not possible, how do we do it manually, we tried to use Postman: 
https://public-rest91.bullhornstaffing.com/rest-services/12345/apply/1234/raw?firstName=John&lastName=Smith&email=email@domain.com&phone=123456789

but we get "errors.badFile".

Thanks.

**Comment by pbearne** [comment]
Hi Mukoy,
I don't know if you can do that on the public API. It can be done with the private (full) API.
We can set it optional in the [Matador Jobs](https://matadorjobs.com/) application forms

Paul

**Comment by charlesabarnes** [comment]
Hello,
You can just add an empty string for the resume parameter.  Please let me know if you have any more questions.

**Comment by mukoy** [comment]
> Hello,
> You can just add an empty string for the resume parameter. Please let me know if you have any more questions.

Hi @charlesabarnes , doesn't work either, it seems you have a server side validation, do you happen to have a PHP or postman sample that you can share? Our company is just migrating to Bullhorn we have 100k plus users and we don't want them to keep on reuploading everytime they apply.

Thanks.

**Comment by charlesabarnes** [comment]
@mukoy, 

Correction:  You will want to send a blob of data, probably containing the first and last name of the candidate that is applying in place of the resume.  
In the past, this method was used to submit plaintext "resumes" of applicants that applied with previously implemented integrations.

I am providing a sample where the code converted plaintext to a blob: https://github.com/bullhorn/career-portal/blob/37e88fa45fdfeb5f70c4f92fa7bdbb6b99db9f48/src/app/modal/modal.controller.js#L330

Please let me know if you have any questions

**Comment by memoht** [comment]
Hello @charlesabarnes ,
We are investigating this same request in the current version of the career-portal for a client.  In `src/app/apply-modal/apply-modal.component.ts` file, I set the resume to:

```
required: false,
hidden: false
```
With this change, the form isn't submitting when a resume isn't attached. Console indicates line 210 as the issue.
`TypeError: undefined is not an object (evaluating 'this.form.value.resume[0].name')` 

I found this thread and was following the fix, but the current `career-portal` doesn't have a file at `career-portal/src/app/modal/modal.controller.js`. 

Can you provide updated instructions for properly setting resume to optional?

**Comment by memoht** [comment]
I should also clarify that I know these instructions were for hiding the resume completely. In this case we probably want to have resume still be able to be submitted, we just don't want it to be required.
