### ISSUE TITLE
Webflow integration

### ISSUE THREAD

**Issue by PedroAlmeidaPereira** [bullhorn/career-portal#317]
Hello everyone,

I'm a UI designer developing my websites in Webflow. My client want this software integrated in his website, wich i develop on Webflow, but webflow just let me embed HMTL code, and for this, i need to integrate jsn file. Did anyone make this integration with webflow that can help me?

Kind regards, and thanks in advance,
Pedro Pereira

**Comment by pbearne** [comment]
Hi Pedro

All you can do is create an Iframe for an install OSCP in.
But can you run the  REACT OSCP on the webflow server if not you will need to host elsewhere?
You might be better off using a sub-domain for the job-broad. If so you just load OSCP or look at more advance option like [Matador Jobs](https://matadorjobs.com/) (this would need a WP install to host it)

I have to ask why are you using WebFlow, not WordPress? What is it the WebFlow provides that WordPress doesn't?

I hope this helps

Paul

**Comment by PedroAlmeidaPereira** [comment]
> Hi Pedro
> 
> All you can do is create an Iframe for an install OSCP in.
> But can you run the REACT OSCP on the webflow server if not you will need to host elsewhere?
> You might be better off using a sub-domain for the job-broad. If so you just load OSCP or look at more advance option like [Matador Jobs](https://matadorjobs.com/) (this would need a WP install to host it)
> 
> I have to ask why are you using WebFlow, not WordPress? What is it the WebFlow provides that WordPress doesn't?
> 
> I hope this helps
> 
> Paul

Hi Paul!

Thank you very much for your answer :) So, i'm a UI Designer, not a developer. I believe i will have to hire a developer, because this will need some code..

So, i'm using webflow instead of wrodpress, because in webflow i can develop my designs exactly how i draw them in Sketch, and i can develop responsive as i want, and i did not have those options in wordpress, since i don't know how to code. Actually, as a designer, i hate wordpress and love webflow :) But i understand i'm limited since i dunno how to code.

Thanks again for your time,

Pedro
