### ISSUE TITLE
Building & running not working

### ISSUE THREAD

**Issue by jesus-escobedo** [bullhorn/career-portal#319]
Hello. Please help me, I am new to nodejs and angular, I usually work with some other programming languajes and frameworks, and I am trying to build the project to start making some customizations but I have not been able to do it, here the steps I have done following the instructions:
Note: using Windows 7
1. I got a clone of the career-portal github project, I did another clone just today so i have latest version.
2. I installed Node.js 12.16.1
3. Opened a cmd terminal and installed Angular CLI using command "npm install -g @angular/cli"
4. Opened another cmd terminal and locate in career-portal directory
5. Run "npm install" command, see result in file attached:
[npm_install_result.txt](https://github.com/bullhorn/career-portal/files/4565598/npm_install_result.txt)

6. Run "npm run build" command, see extract of result in file attached:
[npm_run_build_extract.txt](https://github.com/bullhorn/career-portal/files/4565649/npm_run_build_extract.txt)

7. "npm start" wont work.

**What am I missing or doing wrong please?**

**Comment by pbearne** [comment]
Hi @jesus-escobedo 
if you are having problems with OSCP maybe it will easier to use [matador Jobs](https://matadorjobs.com/) as its WordPress plugin with settings in the admin.
Paul

**Comment by charlesabarnes** [comment]
Can you try running `npm cache clean --force` and trying again?

**Comment by jesus-escobedo** [comment]
I did the cache clean and then npm install, but the result is the same:
[npm_install_result2.txt](https://github.com/bullhorn/career-portal/files/4582671/npm_install_result2.txt)

`npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

audited 30283 packages in 128.157s
found 1682 vulnerabilities (1126 low, 78 moderate, 476 high, 2 critical)
  run `npm audit fix` to fix them, or `npm audit` for details`

**Comment by charlesabarnes** [comment]
You should probably look into installing windows-build-tools

`npm install --global --production windows-build-tools ` 

Seems like its all related to node-sass.  Looking at  sass/node-sass#2773 seems like some people have had similar issues.

**Comment by jesus-escobedo** [comment]
I install the windows build tools but I see no change in error when executing npm install or npm run build, but I want to add that if I execute npm run serve I get:
`ERROR in ./src/app/privacy-policy/privacy-policy.component.scss
Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: Cannot find module 'node-sass'`

I will create a virtual machine with linux environment to check if is there any difference and let you know.

**Comment by charlesabarnes** [comment]
Any luck?

**Comment by therick** [comment]
We are also running into these issues.

**Comment by charlesabarnes** [comment]
@therick have you attempted to install the windows-build-tools as well?  What version of windows are you on?

**Comment by therick** [comment]
I'm on macOS

**Comment by charlesabarnes** [comment]
Can you post the output from when you run "npm install"?

**Comment by ralphleyga** [comment]
Hi guys, I'm using the latest release of career-portal and encounter issue during npm install.  I'm using MacOS Catalina.

Here are some additional detail.
version: latest release from github
career-portal-3.1.1
```
$ npm -v
6.14.5

$ node -v
v13.8.0
```

Please also checkout the log during `npm install`  
https://pastebin.com/YtK07f95

**Comment by pietervanuhm** [comment]
I have the same problem here on MacOS. Can't install correctly, so can't also run it.

1. Clone git
2. Install Node, AngularCLI
3. CD to career-portal
4. 'npm install'
-- Result is are almost only errors :( 
--- See attachtment npm-install.txt
[npm-install.txt](https://github.com/bullhorn/career-portal/files/4818125/npm-install.txt)
