### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by staffingreach** [bullhorn/career-portal#32]
Is it possible to get the option to add our Google Analytics to the job board? We'd like to know what jobs are attracting candidates and from which boards, plus what is the behavior (bounces, conversions, etc).

**Comment by jgodi** [comment]
This is definitely something that we can look into. Thank you for bringing this up! Some projects that could be integrated to allow this could be:

http://angulartics.github.io/
https://github.com/revolunet/angular-google-analytics

There are a few others. 

The Google Analytics ID would have to go into the `app.json` in order to be configurable on the fly.

**Comment by jeremy-dobler** [comment]
We actually already do this via stripesjs. We could either add a dependency to stripesjs or copy the service. All you need to do is initialize the analytics service by passing the ID and then adding the GA call to any element desired.

**Comment by TheReal** [comment]
Interesting @jeremy-dobler . stripesjs is a closed-source library so making it a dependency would require opening it up, which we'd have to analyze and split of any proprietary functionality. I'd prefer to extract the analytics features, generalize them and put them into symphony. We could then depend on symphony and have the analytics for use in future OSS projects. Thoughts?

**Comment by jgodi** [comment]
Ya. If this gets added I say we just use a very simple library. But it will have to be configurable and only add the dependency and elements of GA is set.

**Comment by jeremy-dobler** [comment]
Totally agree with that. I figured we wouldn't want to open our closed-source library. The service that we use is fairly simple. It is just a wrapper around the analytics.js provided by Google. Porting it over to symphony would be simple enough. I can get this service added to symphony and add the Google Analytics(GA) ID to app.json. We could then track when Jobs are viewed, if GA is enabled.

**Comment by therealjeffix** [comment]
I'd like to add Google Tag Manager to our instance of the Bullhorn Career Portal, then I can manage GA and all other tags using Tag Manager instead of making changes to the code.

Is this as simple as pasting the Tag Manager code into the app.js file?

**Comment by krsween** [comment]
Hey @therealjeffix! Here's a stack on this where someone creates a factory that binds to Google's Tag Manager. Basically a thin shim. =)

http://stackoverflow.com/a/21432148

**Comment by jgodi** [comment]
@therealjeffix There is a [feature branch](https://github.com/bullhorn/career-portal/tree/f/ga) where there is some initial work done on adding Google Analytics to the project via [angulartics](https://github.com/angulartics/angulartics/). It is very simple to add and the branch is almost complete. We just need to add the configuration to the `app.json` and only depend on the module/append the script tabs when Google Analytics is enabled. Any help on this would be greatly appreciated.

@krsween mentioned that angulartics will provide you the same capabilities via: https://github.com/angulartics/angulartics/blob/master/src/angulartics-gtm.js.

Hope this helps!

**Comment by Royce-Robbins** [comment]
Dropping in on the conversation to see what progress has been made (if any) on this.  We are looking to add Google Analytics to our Job Board as well since everything post # is not being captured right now.
