### ISSUE TITLE
How to remove powered by bullhorn

### ISSUE THREAD

**Issue by russellfrazier** [bullhorn/career-portal#320]
I’m trying to hide the powered by text and the bullhorn logo. For some reason I am not having success. Can someone tell me the exact CSS I need to apply to make this happen? And in what file? Thank you in advance.

**Comment by charlesabarnes** [comment]
In the static directory, you can modify the `custom.css` file to include `display: none !important` to hide any selectors of choice

Please let me know if you have anymore questions
