### ISSUE TITLE
Additional language

### ISSUE THREAD

**Issue by klarapins** [bullhorn/career-portal#321]
We would need to translate the portal into Slovene (having it in English puts us in the potentially conflict-zone with our national law provisions). I can provide the translation, but would need your help with setting it up in the plug-in.

**Comment by charlesabarnes** [comment]
Hello! 

In this new portal its relatively straightforward: 

In the i18n folder, you will want to copy one of the translation files such as the English one (`en.json`). Then you will want to change the translated values (do not changed the values that are capitalized.  Once done, you will want to name your file for the browser locale for Slovene `sl.json`.  You may also want to add `sl-SI.json`, but the content can be just empty brackets such as `en-US.json`.

Once done, add the new locale into the `supportedLocales` section of the app.json file.  They are in order of priority. 

Please let me know if you have any additional questions.
