### ISSUE TITLE
You don't have permission to access this resource.

### ISSUE THREAD

**Issue by loadedhype** [bullhorn/career-portal#322]
I have installed the Bullhorn Career Portal and have followed the set up process and Bullhorn verification process. However, the page I have installed the shortcode on is displaying the following error message:

Forbidden
You don't have permission to access this resource.
Apache/2.4.41 (Unix) Server at www.insight-rec.com Port 80

I have tried contacting Bullhorn and they are unable to help any further as they have completed the set up on their end. 

This is also the third time of installing the plugin in on different websites and the first time we are getting this issue without being able to resolve. 

I've been advised it may be to do with the hosting and something being set to private so am also contacting 123-Reg but wondered if anyone else had experienced this issue and knew how to resolve it first.

**Comment by charlesabarnes** [comment]
It is very likely your server does not have a default index document set up.   Usually that is things such as index.html or index.php.   The career portal plugin uses this feature.

You can see this in action by going to the framed URL at https://www.insight-rec.com/wp-content/plugins/bullhorn-oscp  and adding index.html manually to the end of the url

https://www.insight-rec.com/wp-content/plugins/bullhorn-oscp/index.html

Please let me know if you have any more questions

**Comment by loadedhype** [comment]
Hi Charles

Thank you so much for coming back to me on the above. I used your advice and requested the updates be made on our server side. 

It fixed the Permission issue but now the information is being pulled through like this:

http://www.insight-rec.com/wp-content/plugins/bullhorn-oscp/

They said this information:

"However, if you are still encountering issues, please contact the plugin's developers and kindly ask them if there are any server-side changes that need to be made. Also, please ask for the plugin's requirements so we can check if this can run on the server as expected."

So i believe something else needs to be done in order to get this working.

**Comment by charlesabarnes** [comment]
Hello again! It seems like they did not properly set the setting for the default index document, instead they enabled "[directory listing](https://cwiki.apache.org/confluence/display/HTTPD/DirectoryListings)".   Below, I am posting additional information with how to modify the default index document in apache using an .htaccess file.  Basically, for that directory index.html should be the default document when you attempt to access that directory

https://stackoverflow.com/questions/19322345/how-do-i-change-the-default-index-page-in-apache


Please let me know if you have any additional questions.
