### ISSUE TITLE
Mobile interface

### ISSUE THREAD

**Issue by klarapins** [bullhorn/career-portal#323]
INSERT SHORT DESCRIPTION EXPLAINING THE HIGH-LEVEL REASON FOR THE NEW ISSUE HERE.

## Current behavior
Our career portal is not showing properly on phone. Career portal: https://www.first-class.si/zaposlitve/ 
-

## Expected behavior
It would be ideal to show properly, so a candidate can see the whole job description and apply. 
-

## Steps to replicate behavior

1. 

## Screenshots

__Current__
![IMG_5076](https://user-images.githubusercontent.com/65286925/82301040-fa8f9480-99b7-11ea-8705-23f2516932b7.png)

__Expected__

**Comment by charlesabarnes** [comment]
This appears to be due to the excess padding being added by your site's theme.  Removing the padding through your theme's styles will resolve this issuse.

Please let me know if you have any more questions
