### ISSUE TITLE
Facebook Post of job page gives inconsistent 404s

### ISSUE THREAD

**Issue by jrussell-links** [bullhorn/career-portal#324]
INSERT SHORT DESCRIPTION EXPLAINING THE HIGH-LEVEL REASON FOR THE NEW ISSUE HERE.

We are posting our job listings to social media and are having trouble with some users are getting 404 responses while others have no trouble viewing the job listing.
## Current behavior

-Some users recieve 404 response's when clicking on our job posting while others don't.

## Expected behavior

-Clicking on the job posting should show you the job description

## Steps to replicate behavior

1. Navigate to https://www.facebook.com/LinksTechnology/
2. Click on the Post "We are seeking an internal Sr. Full Stack Developer!"
3. You should get sent to this page: https://www.linkstechnology.com/portal/#/jobs/5
4. Some users report getting a 404 while others can see the job description.

## Screenshots

__Current__

__Expected__

**Comment by charlesabarnes** [comment]
How are these jobs being shared?  it appears as if a fbclid is being added in the middle of the urls

**Comment by BlevyLink** [comment]
Our recruiters tell us that they are try ing to share the job postings while creating them.

**Comment by charlesabarnes** [comment]
What do you mean by that? Do you have the steps taken to share the job positings?  I just need to know the workflow used.

**Comment by BlevyLink** [comment]
This was sent over to me illustrating where they are trying to post from in Bullhorn that we are getting the error.

I do not have access to our Bullhorn so if you need more specifics please let me know.

[Facebook posting Error.pdf](https://github.com/bullhorn/career-portal/files/4697008/Facebook.posting.Error.pdf)

**Comment by charlesabarnes** [comment]
Hello, as this appears to be an issue from within Bullhorn itself and not the career portal project, I suggest raising this issue with Bullhorn Support. This will allow this issue to be properly tracked and followed up appropriately once it is fixed. 

Please let me know if you have any additional questions
