### ISSUE TITLE
New Filter

### ISSUE THREAD

**Issue by mukoy** [bullhorn/career-portal#325]
Hi, 

How do we add a new filter on the sidebar, Contract and Part Time?
Thanks.

**Comment by charlesabarnes** [comment]
Hello! 

You will want to Add your filter to the [sidebar template](https://github.com/bullhorn/career-portal/blob/master/src/app/sidebar/sidebar.component.html), then you can add the logic for the filter in the [sidebar-filter.component](https://github.com/bullhorn/career-portal/blob/master/src/app/sidebar/sidebar-filter/sidebar-filter.component.ts) file.

Please let me know if you have any questions about this

**Comment by imAjaypal** [comment]
Hi,

Career Portal does not getting base files from app directory. How should I link this ?
