### ISSUE TITLE
There is no apply button on the website

### ISSUE THREAD

**Issue by LaurenEPT** [bullhorn/career-portal#326]
When testing a job on our Open Vacancies page - you can't apply to it - the pop up looks to be too big for the area, and no "apply" button or option to take candidates to the next stage... can anyone assist?

I have included screenshot below, as well as a link to the page: 
https://papiliotalent.com/open-vacancies/
![image](https://user-images.githubusercontent.com/66240727/83382724-0e89bc00-a3e4-11ea-8bda-e1fb6d8e0e5f.png)

**Comment by charlesabarnes** [comment]
Hello,

This can be solved by either increasing the minimum height on the iframe of the portal, or changing the scale of the iframe through CSS.

Please let me know if you have any additional questions
