### ISSUE TITLE
Inquiry into acceptable fields for groupBy calls

### ISSUE THREAD

**Issue by daportnoy** [bullhorn/career-portal#327]
I'm working with a client, who is trying to customize the filters for their portal.  I've updated the publicRESTJobAPIFieldList PLA to include jobOrder.customTextBlock5, which the client has set as a drop down edit type with only four options.  

We've confirmed that the portal is recognizing the fields, but the issue arises when they are attempting to use the field and values for the job board filters.  They are mirroring the groupBy calls used for location and category to filter results by the values in customTextBlock5, but are encountering an error.

The documentation -- [LINK REMOVED] -- states that to-many fields are ignored,  but no indication of anything else.  Is there a comprehensive list of which fields are compatible with groupBy calls?  Is the fact that they are using a customTextBlock field, despite only set as a drop down, causing the problem?

**Comment by charlesabarnes** [comment]
Hello,

TextBlock fields cannot be used in that way.   I suggest utilizing a customText field if it is available.
