### ISSUE TITLE
Want to show Inquiry Form in Career Portal

### ISSUE THREAD

**Issue by imAjaypal** [bullhorn/career-portal#329]
Hi,

I want to show general inquiry form in Career Portal. Please help us how to show it.

Portal Link: http://aequor.in/careerportal/

**Comment by charlesabarnes** [comment]
Hello!
I suggest taking a look at some of the proposed solutions in #254.   Ultimately your options would be to either create a placeholder job as a "general apply" option or utilizing the Bullhorn API and adding a form to your website.

Please let me know if you have any questions
