### ISSUE TITLE
TS2322: Type 'string' is not assignable to type 'number'.

### ISSUE THREAD

**Issue by samsourav** [bullhorn/career-portal#330]
I cloned the repo and installed all the pre-requisites and dependencies. When I try to build the package for server side rendering using command "npm run build" I get this error :
## Current behavior
ERROR in /home/portal/public_html/server.ts
./server.ts
[tsl] ERROR in /home/portal/public_html/server.ts(37,3)
      TS2322: Type 'string' is not assignable to type 'number'.

## Expected behavior
Build should succeed

## Screenshot

__Current__
![Screenshot_6](https://user-images.githubusercontent.com/55572326/83950369-f2ed3e00-a847-11ea-8f5a-0d731fc8ae8f.png)

**Comment by charlesabarnes** [comment]
Hello!

I haven't been able to reproduce this. I'm imagining its a platform issue.  I have updated the types on master.  It will be alright once you pull again.
