### ISSUE TITLE
Help me to use Field(skillID) in app.json to show in left side filter ?

### ISSUE THREAD

**Issue by imAjaypal** [bullhorn/career-portal#331]
Hi,

Can someone help me in BH Career Portal to resolve below issue.

- How to use **Field(skillID) in app.json** to show in left side filter ?
- Not sure about **Field(skillID or skillId) is case sensitive.
- I have added below my app.json code, please write correct code below.

`  "service": {
    "fields": [
      "id",
      "title",
      "publishedCategory(id,name)",
      "address(city,state,countryName)",
      "employmentType",
      "dateLastPublished",
      "publicDescription",
      "isOpen",
      "isPublic",
      "isDeleted",
      "publishedZip",
      "salary",
      "salaryUnit",
      "skillID"
    ],
    "jobInfoChips": [
      "skillID",
      "employmentType",
      {
        "type": "mediumDate",
        "field": "dateLastPublished"
      }
    ],
    "showCategory": true,
    "keywordSearchFields": [
      "publicDescription",
      "title"
    ]
  },
  "additionalJobCriteria": {
    "field": "[ FILTER FIELD HERE ]",
    "values": [
      "[ FILTER VALUE HERE ]"
    ],
    "sort": "-dateLastPublished"
  },
`

Link: http://aequor.in/careerportal/

I want to show skillID filter in left side: ![BH Career Portal](https://user-images.githubusercontent.com/25078651/84894158-ff7e5b80-b0bd-11ea-85e5-fb3686ded8d8.PNG)

**Comment by charlesabarnes** [comment]
Hello, you are unable to add filters through configuration in the app.json file.  

The code will need to be added in the project for the filter to be added.  This can be done through [customization ](http://bullhorn.github.io/career-portal/customizing.html) of your portal using typescript and html.   Please let me know if you have any additional questions

**Comment by pbearne** [comment]
Hi  Ajay,

If you are using WordPress then look at https://matadorjobs.com/ as you can add the skills tax (and then filter on them) with zero code just an add-on

Paul

**Comment by imAjaypal** [comment]
Hi,

I am not using WordPress. I am using Bullhorn Career Portal from "https://github.com/bullhorn/career-portal/".

And also I did not get issue resolved from link "http://bullhorn.github.io/career-portal/customizing.html".

Please anyone help me to write correct code in app.json file.


Thank You!
