### ISSUE TITLE
Cannot get Career Portal to build locally.

### ISSUE THREAD

**Issue by mdallicardillo** [bullhorn/career-portal#333]
I am new to angular/node and am having a lot of trouble getting the career portal to build succesfully.  I followed the read-me instructions by installing git, node.js and angular-cli, when trying to run npm run build:static I just get an error:

Schema validation failed with the following errors:
  Data path ".builders['app-shell']" should have required property 'class'.

I don't have the foggiest idea what I can do to alleviate this.  Thanks in advance for any help!

**Comment by charlesabarnes** [comment]
what platform are you on?

**Comment by mdallicardillo** [comment]
Thanks for your reply, I'm on windows 10 and I was finally able to get it to build.  In addition to the README instructions I had to install sass and microsoft build tools, and fiddle with the angular build version I believe.  After all that it built and ran successfully.

**Comment by charlesabarnes** [comment]
Thanks for the heads up
