### ISSUE TITLE
Portal SEO value

### ISSUE THREAD

**Issue by inchouse** [bullhorn/career-portal#335]
Hi,

The portal has added an iframe to my page when I input the shortcode (which seems to have been limited to 500px before I edited it) which displays ok now. Will google read this content and so boost SEO for the site?

Thanks

**Comment by pbearne** [comment]
Hi 

Google does not read the Iframe content as it is a JS app in an Iframe a step too far for google :-)

If you or your client need google to index the jobs then come and talk to us at Matador Jobs  https://matadorjobs.com/

**Comment by charlesabarnes** [comment]
There have been some tests where the static javascript *did* successfully work by providing the rich job content in a way google can read, but this has not been thoroughly tested by us so your mileage may vary.  Please let me know if you have any additional questions
