### ISSUE TITLE
Pluging/portal updates for wordpress

### ISSUE THREAD

**Issue by inchouse** [bullhorn/career-portal#336]
Hi,

as a wordpress user, will the portal plugin updates appear in the standard updates area and if they do and I update the plugin, will my style edits to css files be replaced so I need to do the edits again?

Thanks for your time

**Comment by pbearne** [comment]
Hi

This plugin is in the main repo so the updates are automatic as per normal. 
If you change any CSS or code in the plugin it will replace when it is updated

You will need to re-apply each time it updates 

This is because it loading in an Iframe 

Paul
