### ISSUE TITLE
Bullhorn Jobs posting to all websites

### ISSUE THREAD

**Issue by Cmclark21** [bullhorn/career-portal#337]
Hello, I have an issue where the same job is posting to our main career portal (also our main site) as well as our other site with the intended job list. I am trying to have these postings on LinkedIn to be directed toward their correct sites. I cannot tell whether this is a tagging issue, a corporate token/clientID issue on LinkedIn's part, a fielding issue, or something else... Please help!

**Comment by charlesabarnes** [comment]
Hello,
Are you utilizing the branded career portal setting? If so, I suggest reaching out to [Bullhorn Support](https://help.bullhorn.com/s/article/Contacting-Bullhorn-Support-616721232) and they will be able to assist with sorting this issue out. 

Please let me know if you have any additional questions

**Comment by Cmclark21** [comment]
We are utilizing the branded career portal setting. We have three separate
websites that are all funneling through one career portal. All of our jobs
are getting posted to all of our sites, in addition to the specific site it
is supposed to go to. How do we filter each post to a certain division for
each job posting?

Thanks

**Comment by charlesabarnes** [comment]
Hello,
I just reread the question and I realize I initially misunderstood.  

In the `app.json` file you will see a section for `additionalJobCriteria`.  In that section you are able to define a `field` and `values`.   The `field` part is what you will want to filter your jobs to (ie. `customText1`).   The values section should then be set for the appropriate content it will filter for in the specified field.


So if you set `"field": "customText1"`  and `"values": ["A", "B"]`, the portal will only display jobs that has customText1 set to *A* or *B*

Please let me know if you have any additional questions.

**Comment by Cmclark21** [comment]
Charles,
We found the field that we want to use. On the recruiters' end, there are 1
of 5 divisions that they can select from a drop-down menu from our desired
field, customText2. Do we need to include all of these divisions in our
fields? Additionally, do we leave the values section blank or do we include
those divisions? Sorry for all of the confusion and thank you for your help
so far

**Comment by charlesabarnes** [comment]
Hello,

You will only want to include the divisions in the value section that you want to show on that portal.

You will only need to set the field to be `customText1`

**Comment by Cmclark21** [comment]
Last question.. our field is customText2. Are we supposed to label our
values field as "division" or specifically write out that division in their
respective app.json file. I sincerely appreciate all your help!

**Comment by charlesabarnes** [comment]
You set the "field" to be customText2 in the app.json file
