### ISSUE TITLE
How to add extra filter to sidebar

### ISSUE THREAD

**Issue by WilliamM095** [bullhorn/career-portal#338]
Hi there, 

I'm trying to add an extra filter to the sidebar. I downloaded and installed the latest release on my website, so far so good. But now I want to make some custom changes. I tried to add all the files from the Master to the main career-portal directory on my website but when I try to for example delete the first two filters by deleting them inside the sidebar.component.html it doesn't show on the front end. Could you point me in the right direction of how I can place the files correctly inside my latest release so I can change the filters on the sidebar.

Thanks in advance!

**Comment by pbearne** [comment]
Hey William 
Side question, are you adding this to a WordPress site?
If so skip OSCP and look at Matador Jobs https://matadorjobs.com/ as you add filter via shortcode

**Comment by charlesabarnes** [comment]
Hello, It sounds like you are making the right modifications, you just need to [build ](https://github.com/bullhorn/career-portal#building)the portal, please let me know if you have any questions.
