### ISSUE TITLE
WordPress Plug In // Remove Bullhorn Logo

### ISSUE THREAD

**Issue by Caitie-c** [bullhorn/career-portal#339]
We're using the Career Portal WP API. We are having some difficulties removing the Bullhorn logo from the bottom left corner of the job board. What's the best way to do this? 

Thanks!

**Comment by charlesabarnes** [comment]
Hello!

You have several options, adding CSS to the static/custom.css file, but this will require you to readd the CSS whenever you update. Another option is forking the portal so you can make permanent modifications to the portal and keep each change fully under your control.

Please let me know if you have any additional questions.
