### ISSUE TITLE
Possible to add optional/additional fields to application in user app?

### ISSUE THREAD

**Issue by dshaw002** [bullhorn/career-portal#34]
Does the API endpoint that is called on application submission allow additional fields in the POST (e.g. address, etc. if person doesn't upload resume or does)? I am about to edit the code, but see no documentation for this or on the Bullhorn Developer site.

## Current behavior

The API endpoint in questions is:

https://public-rest5.bullhornstaffing.com/rest-services/{swimlane}/apply/{job_id}/raw

With variables:
externalID=Resume
type=Resume
firstName={first}
lastName={last}
email={email}
phone={phone}
format=pdf

-

## Expected behavior

Some documentation on different fields or a link to documentation on editing API endpoint to allow optional fields.

**Comment by jeremy-dobler** [comment]
Currently, we do not support any other parameters than the ones that you listed. There are plans to support additional parameters in the future.

For the time being, you can construct a resume (blob) and send that in the POST call. This would be similar to how Apply with LinkedIn works.

[Create the resume file](https://github.com/bullhorn/career-portal/blob/0e5f95b6afc0738318e2efea7b7df9988150197c/src/app/modal/modal.controller.js#L122)
[Send the resume(blob) in the POST call](https://github.com/bullhorn/career-portal/blob/0e5f95b6afc0738318e2efea7b7df9988150197c/src/app/modal/modal.controller.js#L192)

**Comment by dshaw002** [comment]
Thanks, appreciate your prompt response!

**Comment by jeremy-dobler** [comment]
Hey dshaw002,
I know you closed the issue, but I just wanted to let you know that we would love to see and help out with your work for this feature. Feel free to ask us any questions if you need help. Then once you are finished, you can submit a Pull Request and we will review and merge your feature for the benefit of all.
