### ISSUE TITLE
Make changes to title bar and bullhorn logo/powered by

### ISSUE THREAD

**Issue by inchouse** [bullhorn/career-portal#340]
Hi,

Im trying to remove the large grey bar with the client name and the powered by text and logo.

Ive tried using the custom CSS within the WP custom text, the style.css within the plugin files and the portal files in the top level of the hosting but it doesn't seem to make a difference.

What am I missing?

Thanks in advance.

**Comment by charlesabarnes** [comment]
Hello

Can you provide an example or link of what you have tried?  Usually [CSS Specificity](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity) is key here.
