### ISSUE TITLE
'Symbol' is undefined error in IE 11

### ISSUE THREAD

**Issue by GloryFish** [bullhorn/career-portal#341]
We have implemented the Career Portal and are seeing a Javascript error in IE 11:

```
SCRIPT5009:  'Symbol' is undefined
main.js (1, 1941624)
```

This happens on load and results in the throbber never disappearing. No other UI or jobs are loaded.

We are seeing correct behavior in other browsers.

This is occurring with v3.1.1 of the portal.

## Current behavior

Script error in IE 11 preventing application loading.

## Expected behavior

No errors on load and correct application behavior.

## Steps to replicate behavior

1. Load the Career Portal in IE 11

**Comment by charlesabarnes** [comment]
Hello, as version 3 of the career portal doesn't officially support Internet Explorer, I can suggest 1 of two options.  

1. Update the [polyfils](https://github.com/bullhorn/career-portal/blob/master/src/polyfills.ts) file for the project to get it working in IE. 
2. The next option is to download v.2.7.0 of the portal and use that.  

Please let me know if you have any questions.
