### ISSUE TITLE
New fields in apply modal

### ISSUE THREAD

**Issue by adilJamshad** [bullhorn/career-portal#342]
Hi,

I want to create a few new fields in apply modal. Please guide me the process. I have seen that translate makes an async call to database to get the query.

Thank you

**Comment by pbearne** [comment]
Hi adilJamshad

Talk to your client as this would simple if there used Matador Jobs plugin

Paul

**Comment by adilJamshad** [comment]
> Hi adilJamshad
> 
> Talk to your client as this would simple if there used Matador Jobs plugin
> 
> Paul

Hi Paul,

Basically, I am enhancing Bullhorn OSCP for my company. I need to make a few more fields in modal. But I see that translate library is being used. But the fields that I want to create are questions about the candidate. So, I am just not sure how "BY_CHECKING_THIS_BOX" translates to "By checking this box you're agreeing to our Privacy Policy" in bullhorn as I want to implement similar functionality. If you help me with that I will be extremely grateful.

Thank you

**Comment by pbearne** [comment]
Hi 

We can map any object in a candidate to a form import so adding extra checkbox is  just a ticking a setting and 3 lines of code to make it a checkbox

There are a lot of reasons why migrating from OACP to Matador Jobs is a good option. 
Reach out to me at Paul@matadorjobs.com so I can explain how we can help.

Paul
