### ISSUE TITLE
Receiving Invalid Corp Token error

### ISSUE THREAD

**Issue by sfosam12** [bullhorn/career-portal#344]
I have been working to get the OSCP set up to pull current jobs data to be used elsewhere. I have been able to get the the project to successfully build, but when i go to view the site in localhost, I get the error "Invalid Corp Token". I've verified with a bullhorn support analyst that we have received the correct Corp Token and Swim Lane number. I was directed to this forum to try and find a solution to this issue. Any help would be greatly appreciated!

Thanks!

**Comment by charlesabarnes** [comment]
How have you entered the corp token in?

**Comment by sfosam12** [comment]
I have included it in the app.json file located within the src folder, like so:

`"service": {
    "batchSize": 500,
    "corpToken":"6MQU29",
    "port": null,
    "swimlane": "42",
    "fields": [
      "id",
      "title",
      "publishedCategory(id,name)",
      "address(city,state,countryName)",
      "employmentType",
      "dateLastPublished",
      "publicDescription",
      "isOpen",
      "isPublic",
      "isDeleted",
      "publishedZip",
      "salary",
      "salaryUnit"
    ],
    "jobInfoChips": [
      "employmentType",
      {
        "type": "mediumDate",
        "field": "dateLastPublished"
      }
    ],
    "showCategory": true,
    "keywordSearchFields": [
      "publicDescription",
      "title"
    ]
  },`

**Comment by charlesabarnes** [comment]
so this is during development?  how are you running it?  `npm run serve` or `npm run build && npm start`

**Comment by sfosam12** [comment]
Im using npm run build, then npm start

**Comment by charlesabarnes** [comment]
so the app.json file gets replaced with what is in app.json.template, so you may want to either update the template or update the app.json file in the `dist` directory.

**Comment by charlesabarnes** [comment]
Please let me know if you have any additional questions

**Comment by sfosam12** [comment]
running npm run serve instead seemed to do the trick for me. Thanks for your help!
