### ISSUE TITLE
Uploading to host

### ISSUE THREAD

**Issue by adilJamshad** [bullhorn/career-portal#348]
Hi

I have completed the implementation as per requirements. Now, I want to upload OSCP to host. I have seen that there is already a guide for hosting non-customized version of OSCP. But I have customized the career portal, is there any guide to upload that?
If no, will you please enlist the steps.

Thanks

**Comment by charlesabarnes** [comment]
Hello,

You will want to [build:static](https://github.com/bullhorn/career-portal#building) then upload the output from the `dist` directory into your web host with steps similar to the "non-customized" one.

Please let me know if you have any additional questions about this.
