### ISSUE TITLE
Host Issues

### ISSUE THREAD

**Issue by adilJamshad** [bullhorn/career-portal#349]
Hi,

I have two staging sites on my server. One has SSL certificate and other one doesn't have SSL certificate. Wordpress site is running on the staging with SSL certificate. When I upload the content of /dist  to staging (which does not have active SSL certificate), the career portal works fine. But when I upload the same build to staging (which has active SSL certificate) then there are some css issues and the source code is a bit changed. This source code has the lines which I have removed. 

Please advise!

**Comment by charlesabarnes** [comment]
Do you see any specific errors in the console?

**Comment by adilJamshad** [comment]
> Do you see any specific errors in the console?

No, there are not any errors in the console. Btw, I uploaded the build today again and it is working as per my requirements, now. Everything is good now.

Thank you for your support.
