### ISSUE TITLE
Need to add/remove fields from search filters

### ISSUE THREAD

**Issue by inetweaver** [bullhorn/career-portal#350]
Hello ,

I am using bullhorn wordpress plugin and i would like to add/remove fields from the search filters on the left-hand side?

Thanks
Varinder Singh

**Comment by AGoodrum** [comment]
Hi - did you ever get any resolution for this issue from Bullhorn? I have the same issue which they were unable to help with.

**Comment by pbearne** [comment]
Hi All

We can do this is in [Matador Jobs](https://matadorjobs.com/) by filtering the Taxonomies created via WP filters
reach out if you wish to see it working.

Paul

**Comment by charlesabarnes** [comment]
Hello, this can be done by updating the files located in the sidebar directory.  There is not a simple configuration that can be changed to update the filters available at this time.

**Comment by AGoodrum** [comment]
Hi Charles.

Our account with Bullhorn is now closed, so we shouldn’t have any outstanding tickets!

Kind regards

Aaron

Aaron Goodrum
Director

[ScotForce Healthcare (with Bevel and Drop Shadow)]<http://www.scotforcehealthcare.co.uk/>

Head Office: (01738) 248 300
Mobile: 07731 538 632
E: aaron.goodrum@scotforcehealthcare.co.uk<mailto:aaron.goodrum@scotforcehealthcare.co.uk>
W: www.scotforcehealthcare.co.uk<http://www.scotforcehealthcare.co.uk/>
