### ISSUE TITLE
node-sass package is missing

### ISSUE THREAD

**Issue by calvert42** [bullhorn/career-portal#351]
Hello,
The build crashes in local dev without the node-sass npm package. 
I added "node-sass": "^4.14.1" to the list of dependencies in the package.json and it works. 

Did it worked without this package before ? 
Thanks

**Comment by BenRacicot** [comment]
Can confirm this. Also deps need updating.
`found 1753 vulnerabilities (1181 low, 78 moderate, 492 high, 2 critical)`
