### ISSUE TITLE
custom.css is not applied when a job is clicked

### ISSUE THREAD

**Issue by jasonpshea** [bullhorn/career-portal#352]
I edited the static/custom.css file to add some custom styles. When I click on one of the job positions, the styles are not applied:
https://www.wapitimedical.com/careerportal/

Alternatively, if I start at one of the job positions and click "back" to get to the listings again, the custom styles are ignored:
https://www.wapitimedical.com/careerportal/#/jobs/950

Essentially, the custom.css styles are applied when the page initially loads, but does loses the custom.css styles when an action is performed.

Any guidance is much appreciated!

**Comment by charlesabarnes** [comment]
Hello!  

Thank you for providing the links, I don't believe I am seeing the issue on my end, are you able to provide some screenshots of what CSS is not consistently applying?   To check, I looked at the city filter, noticed that it listed the full list of cities, then I clicked a job, clicked back, and the full list of jobs remained.    I also noticed that the header did not reappear when I clicked on one of the jobs.  

Can you provide screenshots or video of the issue occurring possibly?

**Comment by jasonpshea** [comment]
It does appear that some of the styles render, but some are lost. Check out the scrollbars when you load this first:
https://www.wapitimedical.com/careerportal/

Now check out the scrollbars when you hit a job first and then click "back" to get to the main listing:
https://www.wapitimedical.com/careerportal/#/jobs/950

Any ideas?

**Comment by charlesabarnes** [comment]
This is a video of what I see, I am not seeing any changes to scrollbars

https://gfycat.com/vigilantimpishkitfox

Howeverm after taking a look at the CSS used, I noticed that this is likely due to the selectors used.   

The selectors for `_ngcontent` are inserted by Angular and are used for [ViewEncapsulation](https://angular.io/api/core/ViewEncapsulation).  This can cause some unintended effects.    I suggest avoiding those selectors if possible and achieving the intended specificity another way.

**Comment by jasonpshea** [comment]
In the video when you click on the job it shows a grey background, which shouldn't be there based on the custom styles:
https://www.wapitimedical.com/careerportal/static/custom.css

When you go to a Job directly (not from the initial jobs list screen), you'll see that the background is white:
https://www.wapitimedical.com/careerportal/#/jobs/950

When I go to a job first and click "back", the scrollbars render in the original way (not applying all of the styles in custom.css). Here's a screenshot:

![jobs-scrollbars](https://user-images.githubusercontent.com/69957556/90791675-1e23ed00-e2cf-11ea-9296-777ab008713b.jpg)

**Comment by jasonpshea** [comment]
Also, I will give your suggestion a try, avoid using the selectors. Thanks for your quick replies! I'll let you know.

**Comment by jasonpshea** [comment]
You were correct, it was the selectors I used that was causing the problem. Thanks for helping me work through that!

**Comment by msmedhavisaxena** [comment]
Hi Guys, 

I'm am facing problems in creating the custom.css. So what happens is that I found some of the css code that I want to change in the styles.css, to custom.css to change the colors of the bar and the bar of the job portal form after you click "apply" but none of them work when I modify the changes in the CUSTOM.CSS. 

Why custom.css is required to be the part of the bull horn code when the styles.css is given. 

Your feedback and help will be much appreciated.
