### ISSUE TITLE
GoDaddy Website Builder

### ISSUE THREAD

**Issue by jwitt60** [bullhorn/career-portal#353]
I am being told that this can be uploaded to GoDaddy Website Builder platform. However, I am not seeing where this can happen. Does anyone have any insight on this?

INSERT SHORT DESCRIPTION EXPLAINING THE HIGH-LEVEL REASON FOR THE NEW ISSUE HERE.

## Current behavior

-

## Expected behavior

-

## Steps to replicate behavior

1.

## Screenshots

__Current__

__Expected__

**Comment by charlesabarnes** [comment]
Hello,  

I believe you can not upload HTML/CSS/Javascript files to GoDaddy's Website Builder platform specifically. Does your site have access to any sort of Cpanel where you can possibly upload files?

**Comment by jwitt60** [comment]
No it does not, however, my client is being told that it works with this platform by bullhorn. I didn't think it worked on this platform but just looking for clarification/confirmation.

**Comment by pbearne** [comment]
@jwitt60 when you client moves off GoDaddy Website Builder platform to WordPress :-) Lets have chat about them using the [Matador Jobs plugin](https://matadorjobs.com/) 
The Builder is very limited in its options :-(
