### ISSUE TITLE
Issue with Job Portal and API not accepting resumes

### ISSUE THREAD

**Issue by jmccardle77** [bullhorn/career-portal#355]
INSERT SHORT DESCRIPTION EXPLAINING THE HIGH-LEVEL REASON FOR THE NEW ISSUE HERE.

## Current behavior
An issue with API and Job Portal not accepting the resume we are sending, none of that code has changed so I don't know why it would just stop working. I did not see any errors during my test indicating the API call failed. Attached screenshot of code 200
-Applicants are able to apply without a resume. 

## Expected behavior

- When applicants apply through the website, the resume field will require a resume. 

## Steps to replicate behavior

1.

## Screenshots

__Current__
![no resume code 200](https://user-images.githubusercontent.com/40245990/91869631-1efc3d80-ec44-11ea-92a5-45723cd3cd24.jpg)

__Expected__

**Comment by charlesabarnes** [comment]
Hello,
Just to make sure I am understanding correctly, the resumes on your website aren't required, but when you do submit one, you receive an error?

My apologies if I assessed incorrectly, the screenshot is difficult to see.

**Comment by jmccardle77** [comment]
My apologies. Applicants are able to bypass the resume upload on the website. This was working fine before and now has stopped working. Our Web Developer shared that he has tested and not finding any issues. He provided a code 200 screenshot.

Very Respectfully,


Jamie McCardle   |   Database Systems Manager
____________________________________

P 720-355-1285      |   F 877-228-4392
www.matrixproviders.com<http://www.matrixproviders.com/>
____________________________________

[cid:image001.png@01D68051.C83DD4D0]

[cid:image002.png@01D68051.C83DD4D0]<https://www.facebook.com/MatrixProviders>  [cid:image003.png@01D68051.C83DD4D0] <https://www.linkedin.com/company/matrix-providers-inc/>

CONFIDENTIALITY NOTICE: This transmission and its attachments may contain proprietary, confidential or sensitive information. If you are not the intended recipient, you are hereby notified that any disclosure, copying, distribution or use of the information contained herein is STRICTLY PROHIBITED. If you believe you received this transmission in error, please immediately contact the sender and destroy the material in its entirety.

**Comment by jmccardle77** [comment]
I didn’t answer that clear. Applicants are able to skip the upload resume field and apply without a resume. No error shows. I’m not sure if there is an error in the code though.

Very Respectfully,


Jamie McCardle   |   Database Systems Manager
____________________________________

P 720-355-1285      |   F 877-228-4392
www.matrixproviders.com<http://www.matrixproviders.com/>
____________________________________

[cid:image001.png@01D68052.01FFC020]

[cid:image002.png@01D68052.01FFC020]<https://www.facebook.com/MatrixProviders>  [cid:image003.png@01D68052.01FFC020] <https://www.linkedin.com/company/matrix-providers-inc/>

CONFIDENTIALITY NOTICE: This transmission and its attachments may contain proprietary, confidential or sensitive information. If you are not the intended recipient, you are hereby notified that any disclosure, copying, distribution or use of the information contained herein is STRICTLY PROHIBITED. If you believe you received this transmission in error, please immediately contact the sender and destroy the material in its entirety.

**Comment by charlesabarnes** [comment]
Its possible there is issue in the frontend code, do you possibly have an example for me to look at?   Looking at our example career portal, this does not occur

https://bh-career-portal-example.herokuapp.com/jobs/9499

**Comment by billy-bacon** [comment]
This issue can be closed. I work with Jamie at Matrix. The issue was that the frontend code was not requiring a resume to be attached in order to submit a job application, so applicants were not attaching one and ultimately the job was entered into Bullhorn without a resume.
