### ISSUE TITLE
Restrict Applicants from Applying Multiple Times to the Same Job Reqs

### ISSUE THREAD

**Issue by jmccardle77** [bullhorn/career-portal#356]
INSERT SHORT DESCRIPTION EXPLAINING THE HIGH-LEVEL REASON FOR THE NEW ISSUE HERE.

## Current behavior

- Currently applicants can apply to the same jobs multiple times. 

## Expected behavior

- Require a way to restrict this in the code by the applicant email address. 

## Steps to replicate behavior

1.

## Screenshots

__Current__

__Expected__

**Comment by jmccardle77** [comment]
Is it API call prior to submitting the actual application to determine whether the email address being used for their application already has applied for job X?

**Comment by charlesabarnes** [comment]
There is not currently any functionality to do this outside of the cookie that is added to the user's browser that restricts application to the job
