### ISSUE TITLE
Career portal XML Feed

### ISSUE THREAD

**Issue by adamtannous** [bullhorn/career-portal#357]
Can't access the XML feed for our Career portal. From the documentation (http://bullhorn.github.io/career-portal/search-engine-indexing.html) the feed should site at [your career portal root]/feed, but can't seem to access at all. 

## Current behavior

404 page Not Found

## Expected behavior

XML feed of jobs. Are there any other steps needed to get this working?

## Steps to replicate behavior

1. The career portal is hosted here: https://zzandd.com/clients/remedium/careers/
2. According to the docs, this should be the XML. https://zzandd.com/clients/remedium/careers/feed

## Screenshots

__Current__

__Expected__

**Comment by charlesabarnes** [comment]
Hello! This feature requires the "advanced hosting" option. That version utilizes server side rendering on a node server to deliver and generate content. 

I see currently that the static version of the portal is being used.

**Comment by pbearne** [comment]
Hi Adam 

If you can't swap to advanced hosting and using WordPress have look at [Matador Jobs ](https://matadorjobs.com/)we have the XML all working

**Comment by adamtannous** [comment]
Hi again @charlesabarnes,

Wondering if you could provide a little more guidance.
http://bullhorn.github.io/career-portal/advanced-install.html
Have been following the advanced setup, but getting stuck on the 4th step. Does the application need to be built first before this will startup?

Thanks so much for the help.
Cheers
Adam

**Comment by charlesabarnes** [comment]
Hello, 

I need/would like to update these steps.  Instead of downloading a zip archive of the portal, I suggest cloning the repository first, building the app, then starting from your build files.  

You can find details about building [here](https://github.com/bullhorn/career-portal#building)

**Comment by adamtannous** [comment]
Thanks again for the quick reply @charlesabarnes. Really appreciated. 

Think that's done it now thank you, it was that step that was throwing me off. Loading onto AWS now for further testing, but should hopefully be good to go.

Cheers
