### ISSUE TITLE
Bullhorn Portal Iframe issue

### ISSUE THREAD

**Issue by sbdeveloper13** [bullhorn/career-portal#358]
I am working on a site that requires Bullhorn's portal and have successfully integrated it except when I go to submit the application information in the portal the submit button is cut off and I cannot scroll. I have been informed it is potentially an iframe issue, but beyond integrating [oscp], I have used Elementor to build the site so I am unsure of how to extend the iframe. How do I go about expanding that?

Reference: https://new.ntersol.com/recruiting/

**Comment by charlesabarnes** [comment]
Hello, 

In the plugin settings where the corp token and swimlane was added, there is an option for height.   That determines the height of the iframe.

Please let me know if you have any more questions
