### ISSUE TITLE
iOS / Safari - unable to apply due to bottom share bar

### ISSUE THREAD

**Issue by DrTrills** [bullhorn/career-portal#361]
Unable to tap apply button due to viewport on iOS. See attachment

## Current behavior

- can see job, but cant apply. Apply Button / share hidden. As you can see under the back/forward buttons there is a blue button where you should be able to apply. 

## Expected behavior

- Able to apply for a job on mobile. 

## Steps to replicate behavior

1. Load on mobile.

## Screenshots
![IMG_4A597ACE544B-1](https://user-images.githubusercontent.com/1430005/96572465-25667780-12cd-11eb-97b5-ccd434b27103.jpeg)

__Current__

__Expected__

**Comment by vittoriovinci** [comment]
@charlesabarnes Could you please comment on this?

**Comment by charlesabarnes** [comment]
Hello,

This is something being investigated and will be fixed in the next release

**Comment by andrewg09** [comment]
@charlesabarnes is there a timeline for this fix in a future release? It is still presenting in v3.2.0.

**Comment by charlesabarnes** [comment]
I am testing a potential new fix at  https://bh-career-portal-example.herokuapp.com/

please let me know your thoughts before release

**Comment by DrTrills** [comment]
Looks good on my end- Safari screenshot attached. Thanks Charlie 

![IMG_23462C4E40F7-1](https://user-images.githubusercontent.com/1430005/122582972-c0fbe380-d026-11eb-94ed-73e4d083a8cd.jpeg)

**Comment by charlesabarnes** [comment]
This fix is now in v3.3.0
