### ISSUE TITLE
Trouble implementing Career Portal into Wordpress website

### ISSUE THREAD

**Issue by benmilligan** [bullhorn/career-portal#363]
I've spent some time with a Bull Horn product consultant - haven't been able to finalise the implementation.  I am not overly technical so I appreciate the answer might be quite straightforard.

**Comment by pbearne** [comment]
Hi Ben,

Have you looked at Matador Jobs https://matadorjobs.com/ as it makes it easy to get your job board into WordPress? Reach out for more info and demo to me paul@matadorjobs.com

**Comment by charlesabarnes** [comment]
Hello, What is the question/problem?  Your message doesn't include such information
