### ISSUE TITLE
Plugin Installing Failed

### ISSUE THREAD

**Issue by Manmeet1993** [bullhorn/career-portal#365]
I had made changes in the sidebar. I was able to build the solution using NPM RUN BUILD.
Now when I have the build ready in dist/browser, I zip the folder and renamed the folder to career-portal.zip. (only the browser folder not the server). 

## Current behavior
While trying to install the .zip folder to WordPress I am getting an error "The package could not be installed. No valid plugins were found."
-

## Expected behavior
It should Install properly, and I should be able to use shortcode [oscp]
-
To see the code changes I have made please click on the link below - 

https://groupeiveygroup-my.sharepoint.com/:f:/g/personal/manmeet_duggal_iveygroup_ca/ErvH5bjG4iZCkHOogx6tyYoBuSTsMJi7arjp4nlw9IU8lg?e=QptBTy

The folder I was trying to install as a plugin - 
https://groupeiveygroup-my.sharepoint.com/:u:/g/personal/manmeet_duggal_iveygroup_ca/EUpRu7i606NDrYNmKR4ylq4B_baKXsHMeL_Wky6g7qihoQ?e=HAaaiv

Please let me know if I am missing any step or there is some issue.

**Comment by charlesabarnes** [comment]
Hello,

You need to run `npm run build:static` for your static web build.  

Also the easiest method would be to overwrite the files in the career portal plugin directory in your WordPress instance. you can also host the career portal as you would any other hosted website and link from there on your main webpage.

Please let me know if you have any more questions

**Comment by Manmeet1993** [comment]
Thanks @charlesabarnes I will try that. 
I tried replacing the files and then uploading it as a zip for the plugin it did notwork. 

I will go to blue host and upload the files there and check if that works. 
Also, are there any particular file which needs to be replaced or the whole folder ?

Thanks in advance.
