### ISSUE TITLE
Error message with Career Widget upon page load

### ISSUE THREAD

**Issue by CIBRW** [bullhorn/career-portal#367]
INSERT SHORT DESCRIPTION EXPLAINING THE HIGH-LEVEL REASON FOR THE NEW ISSUE HERE.

## Current behavior
We had several people go to that page for the very first time and receive an error message, reloaded the page and the error message went away. But upon subsequent visits to the page received that script error message at the top of the page. This was also on different browsers. I am like you where I only saw the issue once but can reproduce it on any of my browsers. Does that error message screenshot show any idea of what the error would be from the browser or widget?
-

## Expected behavior

- clean page no error messages

## Steps to replicate behavior

1. Go to https://cibrwarriors.com/careers.
2. Observe error

## Screenshots

__Current__
![cibrbullhornerror](https://user-images.githubusercontent.com/77743708/105206176-11bcee00-5b14-11eb-95fa-7cf8c9320d6a.png)

__Expected__

**Comment by charlesabarnes** [comment]
Hello, looks like there may be intermittent file permission issues on the webserver.  Occasionally I notice that I receive an error 403 navigating to https://cibrwarriors.com/wp-content/plugins/bullhorn-oscp/app.json.  Is this problem new to this page?

**Comment by CIBRW** [comment]
Charles,

Before we close this ticket we just need to know what to do to get this
error to stop displaying. The error comes from the bullhorn json, do you
have any more insights on this? Also to answer your question, no this issue
has been on the page for a while now.


Hello, looks like there may be intermittent file permission issues on the
webserver. Occasionally I notice that I receive an error 403 navigating to
https://cibrwarriors.com/wp-content/plugins/bullhorn-oscp/app.json. Is this
problem new to this page?

**Comment by charlesabarnes** [comment]
Hello, there will be a new version of the plugin released this week that changes how the app.json file is saved/loaded, however, this will likely only be mitigation of this issue, if the plugin configuration is updated, your users may run into this issue in the future while the updates are being made.     

I believe there may be file permission issues with that particular directory on your webserver. I am not sure how to fully resolve them as they are not reproducible within a few of my test environments.

Please let me know if you have any more questions
