### ISSUE TITLE
Update causes app.json 404 message

### ISSUE THREAD

**Issue by PurpleBananaCreative** [bullhorn/career-portal#369]
INSERT SHORT DESCRIPTION EXPLAINING THE HIGH-LEVEL REASON FOR THE NEW ISSUE HERE.

## Current behavior

- Career portal not showing, message: "Application initialization failed, please check your app.json file: Http failure response for https://flexsuisse.com/wp-content/plugins/bullhorn-oscp/app.json: 404 OK"

## Expected behavior

- Career portal should be showing

## Steps to replicate behavior

1. N/A

## Screenshots

__Current__

<img width="1953" alt="Screenshot 2021-02-12 at 11 18 51" src="https://user-images.githubusercontent.com/78959966/107761989-3297ee00-6d24-11eb-82f3-31c9bbe99ef7.png">

__Expected__

**Comment by charlesabarnes** [comment]
Hello, 

when I navigate to your site, I see that it is currently working. You may need to refresh and try again 

![image](https://user-images.githubusercontent.com/4327754/107765369-53961a00-6cf7-11eb-98b5-3bc5d0af2423.png)

**Comment by PurpleBananaCreative** [comment]
Hi Charles,

Thanks for getting back to me so quickly. We managed to fix the issue with it not showing by re-saving the settings and regenerating the app.json (as per an earlier thread you had) however it has destroyed the Custom CSS we had in place (i.e. the Bull wasn't there originally, neither was the column on the left). But thanks for getting back to me.

Charles

**Comment by charlesabarnes** [comment]
Hello, 

I have just added update 3.2.1 for the Wordpress plugin that automatically restores the file if it has been deleted.  Thanks for the shout on this.   As for customizations, [WordPress suggests maintaining frequent backups ](https://wordpress.org/support/article/editing-files) to avoid broken functionality, however I will be looking into strategies for persisting CSS changes.   

Were your custom CSS changes in the `custom.css` file?
