### ISSUE TITLE
The bullhorn Jobs page is not working

### ISSUE THREAD

**Issue by akcareerteam** [bullhorn/career-portal#370]
INSERT SHORT DESCRIPTION EXPLAINING THE HIGH-LEVEL REASON FOR THE NEW ISSUE HERE.

## Current behavior

-The bullhorn Jobs page is not working

## Expected behavior

-it is coming 
up with and error
## Steps to replicate behavior

1.

## Screenshots

__Current__
![image](https://user-images.githubusercontent.com/74678825/107815955-ee5b1c80-6d28-11eb-95aa-9aedee17242a.png)

__Expected__

**Comment by charlesabarnes** [comment]
Hello, 

you may want to try checking and resaving your plugin configuration, or update to the newest version of the career portal plugin.

Please let me know if you have any additional questions.

**Comment by akcareerteam** [comment]
It worked thankyou!!! ;)
