### ISSUE TITLE
How do I add a url link to the privacy policy button?

### ISSUE THREAD

**Issue by akcareerteam** [bullhorn/career-portal#371]
![image](https://user-images.githubusercontent.com/74678825/107864598-a31d3880-6e12-11eb-8878-18cf7021dcc7.png)

**Comment by charlesabarnes** [comment]
Hello, 

I'm assuming you're using the WordPress plugin based on your previously created issue.  You are able to add the privacy policy URL under the `Url for Privacy Statement` option under the career portal plugin options in the WordPress administrator settings. 

Please let me know if you have any additional questions.
