### ISSUE TITLE
Tested out the Amazon endpoint link and I just get an error message. 

### ISSUE THREAD

**Issue by Sleppert** [bullhorn/career-portal#372]
Thank you for reading this! I am trying to implement the career portal on my Squarespace site. I am going to iFrame it in through Amazon, and I setup the Amazon bucket. I hit the endpoint link, and I get a red triangle that says Error_Has_Occured. Can someone help me figure this out?

**Comment by charlesabarnes** [comment]
Hello, this may be due to the configuration on your site. Do you have a link for me to take a look?

**Comment by Sleppert** [comment]
Charles - Here you go:

http://collaborativetalent-careers.s3-website.us-east-2.amazonaws.com/#/

Thanks!

*Steve Leppert* *| Founder*

*a: *Collaborative Talent | P.O. Box 2505 | Westerville, OH 43086
*e:* sleppert@collaborativetalent.com | *w:* www.collaborativetalent.com
<http://www.collaborativetalent.com/>
*m:* 614-312-7206

**Comment by charlesabarnes** [comment]
Hello, looks like the configuration is perfect, however the endpoint needs to be enabled for you.  This can be done by reaching out to bullhorn support. 

Please let me know if you have any more questions

**Comment by Sleppert** [comment]
Thank you!

*Steve Leppert* *| Founder*

*a: *Collaborative Talent | P.O. Box 2505 | Westerville, OH 43086
*e:* sleppert@collaborativetalent.com | *w:* www.collaborativetalent.com
<http://www.collaborativetalent.com/>
*m:* 614-312-7206
