### ISSUE TITLE
Bullhorn iframe makes page look suspicious for user

### ISSUE THREAD

**Issue by dsankit** [bullhorn/career-portal#373]
We are using bullhorn iframe on our website page https://hythegroup.com/jobs/
It is working fine on all browsers except Edge. It gives an issue of non https page whereas it works fine with https on all other browsers.
Could you please look into this and give us a solution.

## Current behavior

-

## Expected behavior

-

## Steps to replicate behavior

1.

## Screenshots

__Current__
![image](https://user-images.githubusercontent.com/8501186/110796894-7ab41d00-829e-11eb-9527-cf79761a2a5b.png)

__Expected__
![image](https://user-images.githubusercontent.com/8501186/110796921-843d8500-829e-11eb-9eda-bb8a3bcb69ac.png)

**Comment by charlesabarnes** [comment]
Hello, 

I am on Edge 89 and I am currently not seeing the error on that page.    Do you know possibly which request is causing that error?  The plugin utilizes the plugin URL provided by WordPress

**Comment by dsankit** [comment]
Hello Charles,

You are right the error is no more there.
I don't know how it get resolved. 

But thanks for informing.
Somehow it is gone.
So, there is no more issue.
Thank you.
