### ISSUE TITLE
connecting the app.json to Godaddy site 

### ISSUE THREAD

**Issue by BleuxGenius** [bullhorn/career-portal#374]
Hell Github world.  I am trying to connect Bullhorn open source career portal to my site using GoDaddy, I am using AWS for the management of this information. I have configured the necessary files for the information. The issue I am having is when I use the custom code feature provided. the code does not configure the app. I am seeing the code instead of the app. Could you please assist me with this issue?

**Comment by charlesabarnes** [comment]
Hello, 

Can you provide a link so I can see an example of what you're referring to?

**Comment by BleuxGenius** [comment]
Here is the link to my website that is not yet published with a domain 
https://indigosrvcs.godaddysites.com/

could you view this, please ?

**Comment by BleuxGenius** [comment]
@charlesabarnes

**Comment by charlesabarnes** [comment]
Alright, I can see what is going on, it appears as if you need to iframe the URL to the career portal, not the app.json file or content of the app.json file.

**Comment by BleuxGenius** [comment]
how would I do that? what steps would I need to take because I am not seeing those steps in the documentation 
@charlesabarnes

**Comment by BleuxGenius** [comment]
okay, I see what I was doing incorrectly, I have updated the file and now it has the correct HTML code. however now the app is just showing as a black box, is there anything I'm missing?

**Comment by charlesabarnes** [comment]
Hello,

I see the iframe as 

```
<iframe id="iframe-undefined1" frameborder="0" sandbox="allow-scripts allow-same-origin allow-forms allow-popups allow-presentation allow-top-navigation" src="javascript: window.frameElement.getAttribute(&quot;srcdoc&quot;);" srcdoc="<script>window.onmessage = function(event) {event.source.postMessage({iframeId: event.data, scrollHeight: document.body.getBoundingClientRect().height || document.body.scrollHeight}, event.origin);};</script><body style='margin: 0;'><div style=&quot;display: flex; justify-content: center&quot;><!doctype html>
{{THE CAREEER PORTAL'S INDEX.HTML CONTENT HERE}}
</div></body>" style="width: 100%; overflow: visible; transition: height 1.5s ease 0s;"></iframe>
```

I'm not sure if godaddy is being weird or something, but it needs to look like this `<iframe src="URL TO YOUR AWS S3 BUCKET" width="blah" height="blah"></iframe>`

**Comment by BleuxGenius** [comment]
Okay, I apologize for the delay in response. So I have updated the iframe to what was listed above, still to no avail I'm not seeing a change on the site. I have also updated the Cpanel to reflect the necessary requirements. do you see a difference on the site?

**Comment by charlesabarnes** [comment]
Hello, I have taken a look and I still see the same behavior.  I suspect that this may be an issue with how Godaddy embeds objects.    Is there a custom code object where you can define the embed behavior yourself?

**Comment by pbearne** [comment]
Hi @BleuxGenius 
when I see clients like you struggling with OSCP I often suggest that they look at the [matador jobs WordPress plugin](https://matadorjobs.com/) as a replacement. 
But we have a had problem with GoDaddy's hosting with the way they are running cron and have had to suggest that clients move hosting so did make that suggest as changing the product and the host was a big ask :-)

But I suspect if change your web host will solve the issue you are having the OSCP will be solved.

Paul

**Comment by BleuxGenius** [comment]
I apologize gentlemen for the delay due to so much back and forth with bullhorn and GoDaddy. I have made the necessary changes to proceed forward utilizing wix.com. Thank you so much @pbearne as I have changed the hosting site. I read an article that stated I could connect the bullhorn with Wix. @charlesabarnes Wix does have an embedded functionality, how would I go about that? just upload the entire file?

**Comment by charlesabarnes** [comment]
Hello, you would utilize the embed functionality to iframe the link to your amazon/other statically hosted site

**Comment by BleuxGenius** [comment]
@charlesabarnes okay, where would I find the iframe code for the oscp?

**Comment by charlesabarnes** [comment]
It would be something like <iframe src="URL TO YOUR AWS S3 BUCKET" width="blah" height="blah"></iframe>

**Comment by BleuxGenius** [comment]
just so I understand correctly, I'm creating this code myself correct? or am I looking for the iframe code on bullhorn documentation, or I'm going on Amazon to locate it there? @charlesabarnes

**Comment by BleuxGenius** [comment]
would it be easier to do an API on Wix ?

**Comment by BleuxGenius** [comment]
@charlesabarnes

**Comment by charlesabarnes** [comment]
Building an integration that utilizes the API will not be easier
