### ISSUE TITLE
311

### ISSUE THREAD

**Issue by KramerF** [bullhorn/career-portal#377]
We're experiencing an issue with our Wordpress site's career portal successfully integrating with our Bullhorn ATS. our Representative advised us the issue is similar issue #311, and the site is throwing an 403 error.

**Comment by charlesabarnes** [comment]
Hello, 

what steps have you taken to resolve this? That particular issue is an issue with the webserver itself when it does not have a default index page set. The error is not directly related the the career portal project.

**Comment by KramerF** [comment]
Good morning,

We’re all pretty coding-illiterate, so we haven’t taken any steps just yet to remedy the error. Our rep Tyler just suggested we contact github’s bullhorn portal and ask for assistance

Kramer Frye
Recruiter
E: ***@***.***
www.cci-nursing.com<http://www.cci-nursing.com/>
P: 724-830-9918 ext 1012
F: 724-830-9919
C: 724-689-6854
Confidential Information of Community Care, Inc. This e-mail and any attachments may contain information that is confidential and/or privileged and prohibited from disclosure or unauthorized use under applicable law. If you are not the intended recipient, you are hereby notified that any unauthorized or improper disclosure, copying, distribution, or taking action in reliance  upon the contents of this transmission is strictly prohibited. The information contained in the message is intended only for the personal and confidential use of the recipient (s) named above. If you have received this e-mail in error, you are instructed to notify the sender by reply e-mail and delete it to the fullest extent possible once you have notified the sender of the error. This message is not intended to serve as an electronic signature or other evidence of acceptance or agreement through electronic means.

**Comment by charlesabarnes** [comment]
Hello, 

This is something that you likely will need to work with your web host or the developer that set up your site to correct the configuration on your webserver.

Please let me know if you have any additional questions
