### ISSUE TITLE
Careers portal via amazon aws - How can I Add a company logo to the top of my page, and instead of using he "powered by bullhorn" add a secondary company logo?

### ISSUE THREAD

**Issue by ibbyg** [bullhorn/career-portal#379]
How can I Add a company logo to the top of my page, and instead of using he "powered by bullhorn" add a secondary company logo? I have no experience with coding and just getting set up on amazon AWS took me almost 4 hours.

**Comment by charlesabarnes** [comment]
Hello, this modification requires knowledge of HTML and CSS. There is no exact path forward here as this can be done a million and one ways based on a ton of variables. 

Unfortunately, we are not able to give step by step guidance here.
