### ISSUE TITLE
Apply with LinkedIn - Denied

### ISSUE THREAD

**Issue by jontheophilus** [bullhorn/career-portal#38]
Just a quick note to let everyone know we tried to apply for enhanced API access through LinkedIn to enable Apply with LinkedIN, but we were denied for some reason (they do not give a reason why). Has anyone been able to successfully apply?

Dear developer,

Thanks for submitting your request for enhanced API access through the LinkedIn developer site. We reviewed the information provided in your application and determined that your use case does not qualify for enhanced API access. 

Due to the high volume of requests we receive, we unfortunately cannot provide detailed feedback about your individual application. If you have further questions about the use cases we support through our open APIs, please review our developer site (https://developer.linkedin.com/) and API terms of use (https://developer.linkedin.com/legal/api-terms-of-use).

Thanks for being part of our developer community.

-The LinkedIn Business Development Team

**Comment by stetsona** [comment]
We would need to pursue partner access here.  If you look through their
terms of service there are many terms that we (Bullhorn) don't comply with.

**Comment by jontheophilus** [comment]
I would think the individual company would have to apply for partner access since we are the ones hosting the code. It seems the Apply with LinkedIn feature is well within the API terms of service if you are using it to allow LinkedIN members to apply to jobs on your corporate career website.

**Comment by TheReal** [comment]
Thanks @jontheophilus ! You are exactly correct. We built Bullhorn Career Portal with a by-client LinkedIn integration in mind, knowing that the terms of service should be met by Apply with LinkedIn partners if they are individual career websites instead of a vendor (such as Bullhorn). We are pursuing another channel with which we can hopefully gain more insight from LinkedIn as to why partnership applications are being rejected and what we can do to change that. Stay tuned.

In the meantime, there is a workaround where a Bullhorn Career Portal client can establish an individual developer partnership, which opens access to partial data on anyone's LinkedIn profile. This is enough to make the Apply with LinkedIn integration work, albeit with less data in the candidate record generated by the process. @krsween can you post here with details on how one establishies an individual developer partnership, or point to the relevant documentation in the wiki?

**Comment by stetsona** [comment]
Sorry, yes I should have been a bit clearer.  The eligibility criteria in their api terms states that you cannot use the APIs for for hiring, marketing or selling.  At the bottom of section 1.4 you can see that if you do not meet the eligibility criteria they suggest that you apply for the partner program which may allow you to ignore some of this eligibility criteria.

Here's LinkedIn's partner page: https://developer.linkedin.com/partner-programs

**Comment by jontheophilus** [comment]
What parts would the code not comply with? According to Section 1.4.5:

**Comment by krsween** [comment]
Hey @jontheophilus—

So sorry to be late on this thread! While your team works to iron out LinkedIn's partner details, I can point you to our documentation for registering yourself as a developer, which gives you (limited) access to LinkedIn's public API. 

[Here](https://github.com/bullhorn/career-portal/wiki/Downloading-and-Configuring#unable-to-register-as-a-partner-with-linkedin) (sometimes this anchor link doesn't work, so search for 'Unable to register as a partner with LinkedIn?') we've documented (1) some of the limitations of registering as a developer and (2) the process for registering. It's fairly straightforward:

* Go to [LinkedIn's Developer Portal](https://www.linkedin.com/developer) and register your account as a developer
* Create and app
* Enable the `r_basicprofile` & `r_emailaddress` permissions; then,
* Take the `Client ID` LinkedIn gives you and use that inside of your CareerPortal `app.json` file as the value for `integrations.linkedin.clientId`.

If you need any additional help on this, feel free to reach out!

K.

**Comment by TheReal** [comment]
Just a quick ping to @jontheophilus that we are continuing to investigate this issue via our partnership with LinkedIn. No news to share yet, but stay tuned. We'll hold the issue open until we have some sort of definitive answer.

**Comment by jontheophilus** [comment]
@TheReal I actually just spoke with our LinkedIn account rep who put me in touch with someone from their integration team. In short, because Bullhorn is an ATS partner with LinkedIN it is allowed to get full API access (r_fullprofile & r_contactinfo) for use with Apply with LinkedIn. 

Someone from the LinkedIn team is going to reach out to Bullhorn to help clarify the process, but once the "app" is created on the LinkedIn developer portal that "Client ID" will need to be sent to someone at LinkedIn for the full API access to be turned on.

**Comment by krsween** [comment]
Hi, @jontheophilus —

Did the integration team member at LinkedIn provide you with information about becoming a Partner? @TheReal can articulate this better than I, but each instance of Career Portal represents a different app. Each app, though, should qualify (provided LinkedIn's [Terms Of Service](https://www.linkedin.com/legal/user-agreement) are adhered to) to become a Partner, and once that partnership is signed off by LinkedIn they should give you Partner access to their API. 

I know members of our team have been trying to work in collaboration with LinkedIn to make this process easier, but if I'm following this correctly LinkedIn may be able to provide you with additional information about becoming a partner.

**Comment by jontheophilus** [comment]
Yes, each instance of the Bullhorn Career Portal will need to have an app created on the LinkedIn side and that client id sent to someone at LinkedIn who can give the appropriate access. The sense I got was that the generic partner request form goes to a group who is not aware of the partnership between Bullhorn and LinkedIn.

**Comment by TheReal** [comment]
Thanks @jontheophilus , great info from the client-side perspective. That awareness, or at least a discreet process to elevate an app's client id to appropriate access, is the angle we are working through our channel with LinkedIn. Your research corroborates our (developer group) understanding of how we can make this work. No additional call to action here, hopefully we'll have something definitive soon.

**Comment by tazplay** [comment]
Under 'MyApps' make sure you've added your career portal under the 'Valid SDK Domains' within the Javascript page.

**Comment by krsween** [comment]
### Update From LinkedIn
We've received an update from the LinkedIn development team that they are aware of the iOS Safari issue and are planning to develop a new version of their Apply With LinkedIn API. We will continue to provide updates as we receive them as well as provide information regarding how that will influence our roadmap.

**Comment by developergoutam** [comment]
Hi there I have deployed the latest version career-portal-v1.5.0.zip
But fetched a problem with Apply with LinkedIn Option.
Deployed Server Address : http://54.221.230.11:8080/career-portal/
Error Message "Heads Up! If the LinkedIn sign in page does not appear shortly, please make sure your browser allows pop-ups. Click here to retry."
though my browser allows pop-ups.
![2](https://cloud.githubusercontent.com/assets/20899777/17506733/f4bceb4e-5e28-11e6-8a49-e4220688a5df.png)

**Comment by john-pennington** [comment]
@developergoutam Looks like you've commented both here and on PR #70 . Since you have more details in the PR, let's address it there.
