### ISSUE TITLE
Adding a text field to the Application Pop up form.

### ISSUE THREAD

**Issue by CIBRW** [bullhorn/career-portal#381]
Hello,

I am trying to add a new text field to the Application pop up form when a user clicks "Apply Now". I have tried  uploading the "referredBy" field to the app.json in several spots but no luck and the app breaks. Does anyone have any info on how to properly add a text field to the application form below the Veteran and Disability Status dropdowns?

**Comment by charlesabarnes** [comment]
There is not a straightforward way to do this as it would require conversion from the public api endpoint to one that requires authentication. The public api only handles basic fields.  Please let me know if you have any more questions

**Comment by pbearne** [comment]
Hi @CIBRW 

If you are on a WordPress site (or can use one) The [matador jobs ](https://matadorjobs.com/)Plugin can do this out of the box

Reach out to me for a demo/more info
Paul@matadorjobs.com
