### ISSUE TITLE
Job filtering

### ISSUE THREAD

**Issue by muppetdrummer** [bullhorn/career-portal#382]
Hello I need some help please.

I have built a WordPress site and I am using the Bullhorn plugin. The client has requested:

Filter by Vacancy Title
Filter by State (although county would be preferable as in the UK we don’t use the term state)
Filter by Skill (the secondary ones on bullhorn)

The portal doesn't currently do this so how do I get the filtering to work?

Thanks
Mark

**Comment by pbearne** [comment]
To do this with OSCP you may have to fork the code even if the skills are in the public API
Check out the [Matador jobs plugin](https://matadorjobs.com/) we can do this.

Paul

**Comment by muppetdrummer** [comment]
Thanks Paul

This looks like it's just what we're after. I will share it with the client.

Much appreciated ;-)

**Comment by charlesabarnes** [comment]
For Future readers: You are able to added additional `sidebar filter` components to the [sidebar template](https://github.com/bullhorn/career-portal/tree/master/src/app/sidebar).  

This adds additional filters, there is not a simple configuration to accomplish this at this time.
