### ISSUE TITLE
Career Portal Forbidden

### ISSUE THREAD

**Issue by jossSpinks** [bullhorn/career-portal#383]
Using the Plugin, I have set up my feed and attempted to display this on my website: http://www.foundationpersonnel.co.uk/jobs/ 

The current feed is being displayed as 'Forbidden' and an error message appearing. All content in the Plugin has been added in correctly and there are no current concerns on the server side. 

Do you have any ideas as to how to resolve this?

<img width="1225" alt="Screenshot 2021-04-29 at 14 08 54" src="https://user-images.githubusercontent.com/83022749/116555907-cd03d880-a8f4-11eb-94ca-84acf977cf8d.png">

**Comment by charlesabarnes** [comment]
That particular issue is an issue with the web server itself when it does not have a default index page set.  Update this in your webhost configuration to include index.html and it should work
