### ISSUE TITLE
businessSectorID won't display

### ISSUE THREAD

**Issue by metacrawler23** [bullhorn/career-portal#384]
The Industry field or the businessSectorID won't display on the bullhorn JSON Feed after I put the businessSectorID inside app.json.

The support already added the businessSectorID to the publicRESTJobAPIFieldList System and  still won't work.

## Steps to replicate behavior

1. insert businessSectorID to app.json  under fields
2. ng serve

![image](https://user-images.githubusercontent.com/35279634/118417991-2a679a00-b6e9-11eb-9a39-56cc52087ccb.png)

**Comment by charlesabarnes** [comment]
Hello, 

`businessSectorID` is not a field in Bullhorn.  business sector is a to-many association that will likely need to be formatted like `businessSector(id)`  

[Entity Reference Documentation for reference.](http://bullhorn.github.io/rest-api-docs/entityref.html#joborder)
