### ISSUE TITLE
Nationwide skilled trades career portal link providing 404 error

### ISSUE THREAD

**Issue by Michelle5stones** [bullhorn/career-portal#385]
INSERT SHORT DESCRIPTION EXPLAINING THE HIGH-LEVEL REASON FOR THE NEW ISSUE HERE.
I work for the web development company that built this site: http://www.nationwideskilledtrades.com/. We have downloaded the career portal, uploaded it to the FTP server by following the youtube video that you provide on how to upload to FTP. When I test the link that is registered with bullhorn: http://www.nationwideskilledtrades.com/Careerportal I am recieving a 404 Not Found The requested document was not found on this server. Web Server at capitalweldingandfabrication.com
## Current behavior
404 Not Found The requested document was not found on this server. Web Server at capitalweldingandfabrication.com
-

## Expected behavior
When I click on http://www.nationwideskilledtrades.com/Careerportal it should open the bullhorn software that has been uploaded or "Career Portal"
-

## Steps to replicate behavior

1.

## Screenshots

__Current__

__Expected__
![2021-05-19_13-59-09](https://user-images.githubusercontent.com/84472113/118871900-a3afea00-b8ad-11eb-861b-bcd3d265fdde.jpg)
![2021-05-19_14-00-06](https://user-images.githubusercontent.com/84472113/118871909-a579ad80-b8ad-11eb-9191-2eed90a85cb6.jpg)
![2021-05-19_13-59-49](https://user-images.githubusercontent.com/84472113/118871916-a6aada80-b8ad-11eb-9231-e700f8559b09.jpg)

**Comment by charlesabarnes** [comment]
What directory did you upload everything in.  Can you provide a screenshot of the uploaded files?  The career portal is transpiled into `html`,`css`, and `javascript` so no weird setup is required.

**Comment by Michelle5stones** [comment]
I use Filezilla, went into Nationwide Skilled Trades, created a directory
file titled 'Careerportal' as the video prompted and then dragged all of
the bullhorn files that came with download to that file.

Blessings,

Michelle Travis
Executive Assistant
Web Master

**Comment by charlesabarnes** [comment]
Can you provide the video you are referring to?  Also please provide a screenshot of the uploaded files as well as the surrounding file structure.

**Comment by Michelle5stones** [comment]
https://github.com/bullhorn/career-portal/wiki/Downloading-and-Configuring

https://github.com/bullhorn/career-portal/wiki/Uploading-via-Site-Host-FTP

You couldn't see the uploaded files and surrounding file structure on the
screenshots that I provided already?


Blessings,

Michelle Travis
Executive Assistant
Web Master

**Comment by charlesabarnes** [comment]
Thank you for the links.  Honestly forgot the videos were out there but they should be still accurate.

Screenshots get stripped out of email replies on Github.  so I am unable to view them

**Comment by Michelle5stones** [comment]
[image: 2021-05-19_13-59-09.jpg]
[image: 2021-05-19_14-00-06.jpg]
[image: 2021-05-19_13-59-49.jpg]
Blessings,

Michelle Travis
Executive Assistant
Web Master

**Comment by charlesabarnes** [comment]
Hello,

They have to be posted directly on the Github site for me to be able to view them.  Attached below is a screenshot of all I can see.

![image](https://user-images.githubusercontent.com/4327754/118870921-a9590000-b8ac-11eb-9df3-c095a9514e7a.png)

**Comment by Michelle5stones** [comment]
how do I do that? where on github do I have to go to upload the screenshots?



Blessings,

Michelle Travis
Executive Assistant
Web Master

**Comment by charlesabarnes** [comment]
To the issue you created.  You are able to add it as reply.  Or follow the link at the bottom of the email where it says  `view it on GitHub`

**Comment by Michelle5stones** [comment]
I just edited the issue that I created and added the screenshots  :)


Blessings,

Michelle Travis
Executive Assistant
Web Master

**Comment by charlesabarnes** [comment]
That folder needs to be put in the same directory that the `/Resources/` or `/Portals` directory is located inside of

**Comment by Michelle5stones** [comment]
So the Careerportal folder needs to go in /Portals and then drag all of the
files for the career portal need to be in that folder correct? Sorry, just
being thorough.

Blessings,

Michelle Travis
Executive Assistant
Web Master

**Comment by charlesabarnes** [comment]
It needs to go in the parent directory of `/Portals`.   If the Careerportal folder is placed inside of `/Portals` then the route to the portal would then become http://www.nationwideskilledtrades.com/Portals/Careerportal
