### ISSUE TITLE
I want to remove "APPLY WITH LINKEDIN" Button from our OSCP

### ISSUE THREAD

**Issue by skedmonds** [bullhorn/career-portal#386]
INSERT SHORT DESCRIPTION EXPLAINING THE HIGH-LEVEL REASON FOR THE NEW ISSUE HERE.

## Current behavior
the button is there, and we just want direct application to our OSCP.  We don't want people to apply through LinkedIn
-

## Expected behavior
Make the button go away
-

## Steps to replicate behavior

1. http://www.pmqs-nc.com/careerportal/#/jobs/313   <<<<See that blue button to apply with LinkedIn?  I want it gone!

## Screenshots

__Current__

__Expected__

**Comment by charlesabarnes** [comment]
Remove the clientID in the app.json and this will remove the button.  Another option is to upgrade your portal as this button is not present in more recent versions of the career portal

**Comment by skedmonds** [comment]
How difficult is it to upgrade my portal?  I haven't done anything with it since I set it up a few years ago, lol.

**Comment by charlesabarnes** [comment]
It should be just as straightforward (hopefully).  Just a matter of replacing files on your webserver.   I am providing the installation instructions below: 

http://bullhorn.github.io/career-portal/basic-install.html

**Comment by skedmonds** [comment]
Thank you!
