### ISSUE TITLE
Meta property tags for social sharing on Bullhorn

### ISSUE THREAD

**Issue by techtechte** [bullhorn/career-portal#387]
We have followed the steps which were mentioned in the Bullhorn GitHub & Successfully changed it for the first time, But somehow when we tried changing it for the second time it's not getting updated.
Can you please help us with this?

https://github.com/bullhorn/career-portal/issues/78

**Comment by charlesabarnes** [comment]
Can you provide a link, what is expected, and what it is doing?

**Comment by techtechte** [comment]
(https://github.com/bullhorn/career-portal/issues/78)
We have followed the steps which were mentioned in the Bullhorn GitHub & Successfully changed it for the first time, But somehow when we tried changing it for the second time it's not getting updated.
Can you please help us with this?

**Comment by charlesabarnes** [comment]
I am unable to assist if no details such as the behavior that is being seen and if a link to the portal is not provided.
