### ISSUE TITLE
search by state

### ISSUE THREAD

**Issue by davidjarboe** [bullhorn/career-portal#39]
INSERT SHORT DESCRIPTION EXPLAINING THE HIGH-LEVEL REASON FOR THE NEW ISSUE HERE.

## Current behavior
When you type a search for "Texas" for instance, it shows zero results, although I have 3 job openings in Texas currently.
-

## Expected behavior
I would think that all three jobs would display if someone searched by state
-

## Steps to replicate behavior

1. Type the name "Texas" into the search box and hit enter.

## Screenshots

__Current__

__Expected__

**Comment by krsween** [comment]
Hi @davidjarboe—

Could you possibly provide the URL of the live application? That will help us figure out why this isn't working.

Thanks!
K.

**Comment by davidjarboe** [comment]
Yes, I'm sorry.
www.verticalrecruiting.com/careers

**Comment by krsween** [comment]
Hi @davidjarboe—

Thanks for the quick reply! I tested out the filter by location, and that seems to be working, so I'm assuming you're trying our 'Keyword Search' feature and it's not searching by location. That feature is currently searches the keywords of each opportunity—not including location. Adding the ability to search location as a keyword is a good idea, though. We considered adding this feature in the past, but have chosen to keep faceted search and keyword search as separate behaviors. However, I’d love to see and contribute to a fork of this app with that functionality! 

Thanks!
K.

**Comment by davidjarboe** [comment]
When you say you did a filter by location... how did you do that?  I don't
seem to have any other search options besides "Keyword Search".



On Thu, Mar 17, 2016 at 7:27 PM, Kameron Sween <notifications@github.com>
wrote:

> Hi @davidjarboe <https://github.com/davidjarboe>—
>
> Thanks for the quick reply! I tested out the filter by location, and that
> seems to be working, so I'm assuming you're trying our 'Keyword Search'
> feature and it's not searching by location. That feature is currently
> searches the keywords of each opportunity—not including location. Adding
> the ability to search location as a keyword is a good idea, though. We
> considered adding this feature in the past, but have chosen to keep faceted
> search and keyword search as separate behaviors. However, I’d love to see
> and contribute to a fork of this app with that functionality!
>
> Thanks!
> K.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/bullhorn/career-portal/issues/39#issuecomment-198143402>
>



-- 

David Jarboe - President
Vertical Recruiting <http://www.verticalrecruiting.com>
(855) 998-4952 (toll free)
(855) 998-4962 fax



This email and any files transmitted with it are confidential and intended
solely for the use of the individual or entity to whom they are addressed.
If you have received this email in error please notify the system manager
and the person who sent this message.  If you are not the intended
recipient you are notified that disclosing, copying, distributing or taking
any action in reliance on the contents of this information is strictly
prohibited.

**Comment by krsween** [comment]
Just beneath the `Keyword Search` each location listed can be selected as a filter. You can also select multiple locations. :smiley:

**Comment by davidjarboe** [comment]
Ok.  I thought you meant that you had a different "additional" search box
or drop down menu.

Sorry.

Thanks for your response.  I think that would be great to implement (the
search location functionality).  I guess I could include text about
location in all the job descriptions, but I haven't been.

Thanks for your prompt responses.

David

On Thu, Mar 17, 2016 at 7:31 PM, Kameron Sween <notifications@github.com>
wrote:

> Just beneath the Keyword Search each location listed can be selected as a
> filter. You can also select multiple locations. [image: :smiley:]
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/bullhorn/career-portal/issues/39#issuecomment-198144263>
>



-- 

David Jarboe - President
Vertical Recruiting <http://www.verticalrecruiting.com>
(855) 998-4952 (toll free)
(855) 998-4962 fax



This email and any files transmitted with it are confidential and intended
solely for the use of the individual or entity to whom they are addressed.
If you have received this email in error please notify the system manager
and the person who sent this message.  If you are not the intended
recipient you are notified that disclosing, copying, distributing or taking
any action in reliance on the contents of this information is strictly
prohibited.

**Comment by krsween** [comment]
I didn't have RecordIt on my personal machine, so I had to install it quickly. Here's filtering:

![ko8owfmjaz](https://cloud.githubusercontent.com/assets/5342395/13865269/de80d6da-ec7f-11e5-9be6-54cef9574a06.gif)

**Comment by krsween** [comment]
My pleasure, @davidjarboe! If you decide to tackle adding that feature, @ me in a commit or merge req and I'll gladly help out where I can.

Best of luck!
K.
