### ISSUE TITLE
Career Portal stopped working

### ISSUE THREAD

**Issue by DennisChristoforatos** [bullhorn/career-portal#391]
INSERT SHORT DESCRIPTION EXPLAINING THE HIGH-LEVEL REASON FOR THE NEW ISSUE HERE.

## Current behavior
When going to the Job Board link on my company website, https://www.bradleyscottresources.com/job-board/  the following error appears: 

Application initialization failed, please check your app.json file: Http failure response for https://www.bradleyscottresources.com/wp-content/plugins/bullhorn-oscp/app.json: 404 OK

Opened a ticket with Bullhorn Support and advised to "make sure the app.json is correctly in place (downloading and re-uploading, if necessary) and uninstalling/reinstalling the Wordpress plugin."  

I don't know where to find the app.json file and I have already deleted and re-installed the Bullhorn plugin through WordPress.
-

## Expected behavior
The job board should appear allowing users to search for open jobs
-

## Steps to replicate behavior

1. Navigate to the the link https://www.bradleyscottresources.com/job-board/

## Screenshots

__Current__

__Expected__

**Comment by charlesabarnes** [comment]
Hello @DennisChristoforatos 

It appears as if this installation isn't utilizing the shortcode for the portal which does have a method to regenerate the `app.json` file for you if it was ever deleted.  However, this should be resolved by resaving your plugin settings under plugins > career portal in the admin section.


Please let me know if there are any additional questions.
