### ISSUE TITLE
Can't Hit Apply Button On a Laptop With the Addition Apply With LinkedIn Feature

### ISSUE THREAD

**Issue by Nathan281** [bullhorn/career-portal#41]
When applying to a job on the career portal from a laptop, you cannot see the apply button.  Normally you could, but with the apply from LinkedIn addition, you cannot.  It cuts off the bottom of box that is used to fill out name and attachment.  The only way around this is to hit the tab key.  But even then, it does not look right.

## Current behavior

-  You cannot hit the apply button on the career portal if you are on a laptop and the career portal supports the apply with LinkedIn Integration.

## Expected behavior

-  You should be able to scroll down to the apply button.

## Steps to replicate behavior

1.  Go to http://www.coyotecrk.com/careerportal/#/jobs on a laptop.
2.  Go to any job and hit apply.
3.  The applicants information box displays but is cut off half way though the attach resume portion.

## Screenshots
![cant apply](https://cloud.githubusercontent.com/assets/18013384/13962472/1babcf8a-f02f-11e5-8519-047f70239d1c.PNG)

__Current__

![tab key](https://cloud.githubusercontent.com/assets/18013384/13962523/5d9e066a-f02f-11e5-8633-4df1b23e89b4.PNG)

__Expected__

**Comment by bulbajackel** [comment]
Took a look at this, on a couple of computers.  It appears to be exclusive to devices with 1366x768 monitors.

**Comment by jgodi** [comment]
@bulbajackel Thank you for reporting this. We will investigate the matter and come up with the best course of action to resolve this. In the meantime, if have an idea and want to submit a pull request I will gladly help in any way I can. 

If this is your first time contributing to an open source project you can refer to [How to Submit a PR](https://yangsu.github.io/pull-request-tutorial/) and ping me for any help!

Thanks again!

**Comment by mpukita** [comment]
This is a problem for us as well.

http://www.fastswitch.com/careerportal/#/jobs/

Any idea on a fix timeframe?

**Comment by tazplay** [comment]
To alleviate this pain immediately, you can adjust the margins to push up the box to the top of the screen its being viewed on within the 'styles/app-XXXXXXXXXX.css' file

Edit this -
```
.modal-container>div.modal {
	max-width: 500px;
	margin: 80px auto;
	height: auto
}
```

To this:
```
.modal-container>div.modal {
	max-width: 500px;
	/*margin: 80px auto;*/
	height: auto
}
```

**Comment by krsween** [comment]
Thanks to @bulbajackel we have moved the Apply Via LinkedIn experience to the apply details page instead of in the modal. This frees up screen real estate and allows users on smaller screens to see the apply button. Our minimum screen resolution is now **1280x800**.
