### ISSUE TITLE
Forbidden - you don't have permissions to access this resource - Apache/2.4.46 (Unix) Server at www.nobulrs.com Port 80

### ISSUE THREAD

**Issue by mattnobul** [bullhorn/career-portal#413]
## Current behavior

- I have integrated the bullhorn plug-in onto our word press website but now I get "Apache/2.4.46 (Unix) Server at www.nobulrs.com Port 80" error message when I load up the page. I have checked previous comments about having an index page and checked on 123 reg and can confirm there is an index.php there. The page it should be loading on is - www.nobulrs.com/jobs

## Expected behavior

- The customer portal loads correctly.

## Screenshots

![image](https://user-images.githubusercontent.com/88542808/128510235-b1c5889c-04b3-473f-89c9-4e598f70185b.png)

**Comment by charlesabarnes** [comment]
index.html has to be added to the list of default index pages, not just index.php.  You can view that it works by navigating directly to the iframe source and adding index.html to it. https://www.nobulrs.com/site/wp-content/plugins/bullhorn-oscp/index.html
