### ISSUE TITLE
After applying successfully to one job in IE11, candidates cannot view additional jobs

### ISSUE THREAD

**Issue by kbushkoBH** [bullhorn/career-portal#42]
Most recent versions of Bullhorn Career Portal do not appear to support multiple applications in the same IE11 browsing session.

## Current behavior

- Viewing version 1.4 or 1.4.1 of the portal in IE11, applicants cannot view subsequent jobs after one successful application

## Expected behavior

- After completing an application, applicants should be able to view and apply to additional jobs

## Steps to replicate behavior

1. Navigate to the following career portal sites in IE11 and attempt to apply to multiple positions in the same browsing session. The portal hosting version 1.3 allows multiple applications in IE11, the other two portals do not display individual job pages correctly following a successful application.

http://sl4company.s3-website-us-east-1.amazonaws.com
version 1.3

http://sl5testcorp.s3-website-us-east-1.amazonaws.com
version 1.4

http://sl32testcorp.s3-website-us-east-1.amazonaws.com
version 1.4.1

## Screenshots

__Current (in IE)__
Using http://sl5testcorp.s3-website-us-east-1.amazonaws.com

Blank page displays for job 51 after a successful apply to job 66:
![enduserview](https://cloud.githubusercontent.com/assets/18052144/14019934/f0853114-f1a2-11e5-8fcb-a72c154c64a1.PNG)

Error appears in console:
![consoleerror](https://cloud.githubusercontent.com/assets/18052144/14019994/3c3a1688-f1a3-11e5-92fb-6c2fe2051517.png)

GET call response indicates content should display:
![getresponse](https://cloud.githubusercontent.com/assets/18052144/14020080/72834020-f1a3-11e5-99ee-1abcc84f7d47.PNG)

**Comment by jgodi** [comment]
The issue in particular is with https://github.com/bullhorn/career-portal/blob/9f893cf19ebd18e6a946312f7e92a5fa8bf45ee9/src/app/detail/detail.controller.js#L44. I am guessing that we are either (1) not loading the correct polyfills or (2) should just switch to use `indexOf() !== -1` or something similar.

**Comment by jgodi** [comment]
Fixed via https://github.com/bullhorn/career-portal/pull/43, verifying right now.

**Comment by TheReal** [comment]
Fixed in [release v1.4.2](https://github.com/bullhorn/career-portal/releases/tag/v1.4.2).
