### ISSUE TITLE
WordPress Career Port reporting invalid Corp Token

### ISSUE THREAD

**Issue by memoht** [bullhorn/career-portal#426]
INSERT SHORT DESCRIPTION EXPLAINING THE HIGH-LEVEL REASON FOR THE NEW ISSUE HERE.
Setting up OSCP Portal using the latest edition (v.3.30) of the WordPress plugin. I have confirmed with the client and by digging through the `app.json` file on their Bullhorn portal that the `swimlane` and `Corp Token` values are correct.
I plug the shortcode in the page and it returns
```
Application initialization failed, please check your app.json file: Invalid Corp Token
```

## Current behavior

- Portal fails to initialize
- The site is running WordPress 5.8.1 so don't know if something there is the issue since this plugin isn't tested on this latest version.

## Expected behavior

- Expect portal jobs to show

## Steps to replicate behavior

1. Download and activate [WordPress plugin](https://github.com/bullhorn/career-portal/wiki/Using-the-Bullhorn-Career-Portal-on-Wordpress)
2. Enter swim lane and Corp token
3. Put shortcode [oscp] on page

## Screenshots

__Current__

__Expected__

**Comment by charlesabarnes** [comment]
The steps to replicate are not accurate as it does not provide any information about the corp token

**Comment by memoht** [comment]
@charlesabarnes The corporate token was provided by the Bullhorn client and is alphanumeric. I don't guess this key is all that private since I dug it out of their career portal to confirm by looking at the `app.json` file. What can I do to provide the needed info?

**Comment by charlesabarnes** [comment]
You can add it here as the corp token is not private information.   If you have a link to the site that is not working also works

**Comment by memoht** [comment]
@charlesabarnes It appears to have started working now. Apologies and thank you.
