### ISSUE TITLE
Bullhorn portal for wordpress not working.

### ISSUE THREAD

**Issue by BrentBBest** [bullhorn/career-portal#446]
INSERT SHORT DESCRIPTION EXPLAINING THE HIGH-LEVEL REASON FOR THE NEW ISSUE HERE.

## Current behavior

- the error is : An error has occurred while loading. Please refresh the page and try again.

## Expected behavior

- This is my first time using this plugin so I don't k ow how it should look when up and running. I have tried uninstalling, reinstalling, clearing the cache the port is correct and they key is correct but there seems to be issues on the back end. I'm running the newest wordpress version and using Elementor as the page builder. Any help to get this up and running would be golden.

**Comment by charlesabarnes** [comment]
Hello, this will potentially be better handled with Bullhorn Support as it's specifically an issue with the API and not specifically the career portal.   Please let me know if you have any questions.

**Comment by BrentBBest** [comment]
Thanks for the quick follow up !
