### ISSUE TITLE
Accessing XML version of feed

### ISSUE THREAD

**Issue by memoht** [bullhorn/career-portal#456]
I have been working on accessing the RSS/XML functionality in the OSCP and followed the link to deploy to Heroku you provided in ticket #411 (https://heroku.com/deploy?template=https://github.com/bullhorn/career-portal). 

I can now access the `/feed` URL but it is an `RSS` feed, not an `XML` feed. We are working with a Bullhorn client and trying to get them to setup advanced hosting, but an XML feed is what we need.

Where is the config setting or how do we get `/feed` to generate XML instead of RSS?

**Comment by charlesabarnes** [comment]
RSS is a specification that is valid XML. is there anything specific that you are looking for?

**Comment by memoht** [comment]
Hello @charlesabarnes Having worked with PPC traffic for several years, the defecto standard in the industry for sharing feeds has been via XML rather than RSS. While RSS is valid XML, there are significant differences in the context of trying to share job postings. 

For example,  `CDATA` wrappers around content help to deal with parsing issues that can be encountered due to the wide variety of possible content. As a practical aside, attempting to open an RSS feed in a browser like Safari won't even render, but an XML feed renders as expected. 

Being a job portal, I would expect the Bullhorn OSCP portal to be capable of generating either RSS or XML and to allow some customization of fields, for example to include the Job pay rate field. But if it were to support only one, it seems straight XML would have been the more common choice.

**Comment by charlesabarnes** [comment]
There was no XML or RSS generation previously. Version 3.0 was the first version with any server side functionality. When sharing with third parties, Bullhorn has always offered the option for sharing JSON using the public API. This option will be _dramatically_ more performant than using the career portal as a middleware.  If it's an option you can use I would suggest sticking with that. 

The server side logic just converts the JSON data and puts it in a format that is useful for job boards who don't consume the JSON content. This functionality can be extended by forking and cloning this repo.

**Comment by memoht** [comment]
Thanks, I thought you might mention the API. Interacting with the API involves a different level of dev work and workflow than just reading an XML feed. I personally prefer parsing JSON content over XML, but dealing with building a custom client to handle OAuth, tokens, refreshing tokens and then querying the API to get a feed of jobs is more complicated.
From what I have read, there is no single endpoint you can hit to get a JSON feed from a Bullhorn site without going through the OAuth process.
Either way, I appreciate your response and insight into the behavior of the OSCP.

**Comment by charlesabarnes** [comment]
The public API is unauthenticated.  A single URL you can use to get all of your bullhorn jobs.  This is the endpoint that the career portal uses

**Comment by memoht** [comment]
Can you point me to the docs or where we would find the correct endpoint for a particular client? We have their swimlane and corp token.

**Comment by charlesabarnes** [comment]
Just to provide additional information for future readers:

This API only can be accessed when it's enabled and you can specify which fields can be accessed (with assistance of bullhorn support). 


I think providing this line of code below may be useful but basically it's 
https://public-restSWIMLANE.bullhornstaffing.com/rest-services/CORPTOKEN/search/JobOrder?query=.....

From there, the queries and fields are very similar to the docs in https://bullhorn.github.io/rest-api-docs/


https://github.com/bullhorn/career-portal/blob/master/generateXml.ts#L40

**Comment by memoht** [comment]
Thanks. I'll go ahead and close this ticket. You have been very helpful.
LLAP 🖖

**Comment by onthebrandywine** [comment]
For anybody who happens to come across this thread, to expand on what Charles said above. You can find the exact query being used by your career portal by:
In Chrome, open the Developer window (F12), click on the Network tab. Load up your career portal then scroll through the various calls made. Eventually you will find the query that returns the JSON formatted jobs to the portal. This (or a version) of it is what you give to the job boards requesting the feed. The query will be something similar to:

https://public-restXX.bullhornstaffing.com/rest-services/<CorpToken>/search/JobOrder?query=(isOpen%3A1%20AND%20isDeleted%3A0)&fields=id,title,publishedCategory(id,name),address(city,state),employmentType,dateLastPublished,publicDescription,isOpen,isPublic,isDeleted&count=20&sort=-dateLastPublished&start=0
