### ISSUE TITLE
Have "State" as a filter option instead of "City, State"

### ISSUE THREAD

**Issue by therealjeffix** [bullhorn/career-portal#46]
INSERT SHORT DESCRIPTION EXPLAINING THE HIGH-LEVEL REASON FOR THE NEW ISSUE HERE.

The top level filters include "city, state" and "category". For national companies the list of cities is extensive and usability suffers. 

-

It'd be fantastic to have the option to just have "State" as a filter (and/or as a parent filter with matching cities as a child filter). We tried to do change the call to only "State", but ran into a 400 - Bad Request response from the API.

-

## Steps to replicate behavior

1.

![img-20160326-wa0007](https://cloud.githubusercontent.com/assets/14004105/14064156/50366f28-f3ac-11e5-95aa-5f941b1ff610.jpg)
![img-20160326-wa0006](https://cloud.githubusercontent.com/assets/14004105/14064157/50375f96-f3ac-11e5-8136-68c8ae943009.jpg)
![img-20160326-wa0005](https://cloud.githubusercontent.com/assets/14004105/14064158/50378d36-f3ac-11e5-8ff3-02835867a737.jpg)

__Current__

__Expected__

**Comment by krsween** [comment]
Hey, @therealjeffix—

This would be a really neat idea to see come to life. Having custom taxonomies could really reveal some new possibilities to this app. Likely this change would require a solution UI-side. I see that you tried changing the query on the backend, but I don't believe we support that. Have you tried solving this client-side (i.e. via Angular)?

Thanks!
K.

**Comment by jontheophilus** [comment]
I agree - we have thousands of open positions all over the country. One thing we do on our custom Bullhorn job portal is a zip code radius search if you enter a city/state or a zip code. This helps grab those positions in the same metro area with a different city name.

We use this REST service as a helper:[https://www.zipcodeapi.com/]( https://www.zipcodeapi.com/)

**Comment by therealjeffix** [comment]
@krsween thanks, good to know query changes aren't supported. We looked into aggregating the data post-query into States and ran into a few issues, but we'll give it another go.

**Comment by therealjeffix** [comment]
@krsween lets say the user selects "Texas" from the filter list, we have to query for each city in Texas, then merge the results. This also led to 400 Bad Request errors (some kind of throttle or request frequency capping?). 

Is this the type of UI-side solution you are suggesting or would you approach it differently?

**Comment by acrowe2** [comment]
Hi, @therealjeffix 

I was investigating the issue you reported and noticed that the where clause that you are using has an extra ')'.  You have `(isOpen = true) AND (address.state='AL'))`, but it should be `(isOpen = true) AND (address.state='AL')`.  Perhaps fixing this will return the results you want.  I hope this helps.

**Comment by krsween** [comment]
Hey, @therealjeffix —
The team here swarmed and it looks like there is an API that can return data by state—contrary to my understanding! (Way to go @acrowe2!)

I think this solves a part of the problem in that the initial step of aggregating a series of state queries (by state) may no longer be needed, which gets around API limitations too as there are fewer queries. 

Does this level of custom taxonomies solve the entire scope of the problem, or is there a need to have an additional layer on top of this?

K.

**Comment by therealjeffix** [comment]
@acrowe2 @krsween let me attempt and get back to you, thanks for looking at this.

Custom taxonomies would be a cool feature, but for now grouping by state will be all I need.

**Comment by krsween** [comment]
Our pleasure! Let us know how this goes. I'm going to resolve this issue for now.

**Comment by therealjeffix** [comment]
Got it up and running. Thanks again!

**Comment by whreed** [comment]
@therealjeffix  Can I ask where you go to edit the query?  I only have access to this github for a client project, what other access do I need to see backend information?  Is this access Bullhorn where they submit job postings to be published?

**Comment by therealjeffix** [comment]
You can edit the query from the app-<###>.js file (in this GitHub repository). If you want access to your client's Bullhorn CRM you'll need to request that from your client, this repository is not the same as access to the software account.

**Comment by whreed** [comment]
Do you care to share how you got it to just show states on the side but still keeps city state in the job listing?
