### ISSUE TITLE
Career Portal set up in WordPress plug in. BH verified that I don't have special characters... Pulling jobs on portal but when clicking on job nothing is there... Showing blank page in portal

### ISSUE THREAD

**Issue by BRAVARUSSELL** [bullhorn/career-portal#460]
INSERT SHORT DESCRIPTION EXPLAINING THE HIGH-LEVEL REASON FOR THE NEW ISSUE HERE.

## Current behavior

-

## Expected behavior

-

## Steps to replicate behavior

1.

## Screenshots

__Current__

__Expected__

**Comment by charlesabarnes** [comment]
Hello, I believe you may have been directed to the wrong place.  Bullhorn support is the best place to troubleshoot career portal issues. 

Please let me know if you have any questions

**Comment by BRAVARUSSELL** [comment]
I was instructed by Bullhorn Support to post on this issue.  Everything is set up properly but the portal isn’t working correctly.  Bullhorn support looked through and made sure that there weren’t any character issues that would cause this to happen.  They have escalated the ticket but specifically advised me to submit this issue to GitHub!


Jenny Russell
President

[Text  Description automatically generated]<http://www.bravarecruiting.com/>
C: ‪407.212.1454
Schedule a Call<https://calendly.com/jenny-russell>
www.BravaRecruiting.com<http://www.bravarecruiting.com/>
[Icon  Description automatically generated,Icon  Description automatically generated]
[A picture containing text, clipart, vector graphics  Description automatically generated]<https://www.linkedin.com/company/brava-recruiting>                   [Logo  Description automatically generated] <https://twitter.com/BravaRecruiting>

**Comment by BRAVARUSSELL** [comment]
https://bravarecruiting.com/wp-admin/plugins.php?page=bullhorn-oscp


Jenny Russell
President

[Text  Description automatically generated]<http://www.bravarecruiting.com/>
C: ‪407.212.1454
Schedule a Call<https://calendly.com/jenny-russell>
www.BravaRecruiting.com<http://www.bravarecruiting.com/>
[Icon  Description automatically generated,Icon  Description automatically generated]
[A picture containing text, clipart, vector graphics  Description automatically generated]<https://www.linkedin.com/company/brava-recruiting>                   [Logo  Description automatically generated] <https://twitter.com/BravaRecruiting>
