### ISSUE TITLE
Customization Support Request for Branding

### ISSUE THREAD

**Issue by jlukus** [bullhorn/career-portal#47]
I would appreciate if someone could please provide some information (I can pass on to our developer) on how to customize the Career Portal with our brand, i.e. logo, font, color, etc.

From what I understand, the portal can be put in an iframe in order to surround it with branded corporate content the user must edit the CSS files to change colors and appearance

Is there a basic framework or template example with which to work?

Is it just a matter of embedding the code in the download within an iframe on a standard web page? 
If it is, great - but we need to know where to put that web page and what to name the file, and then what code to insert in the iframe. 

Any information you can provide would be greatly appreciated!
Thank you!

**Comment by krsween** [comment]
Hi, @jlukus —

One approach to get started customizing Career Portal would be to (1) clone the repo, (2) follow the steps in the README ('Install build tools and dev dependencies') to get your local dev environment setup, and then (3) modify the app's SCSS & HTML to suit your preferences.

The app _was_ designed to have an easy entry points for common configuration. For example, in the `src/app/index.scss` file lines 6-26 are variables used throughout the app to define colors and the primary font. By changing these values, any reference to those values will get inherited throughout the app. Our hope is that this solves a large portion of common customizations. 

Additional customizations can, of course, be added by modifying the SCSS and HTML files that contain elements you'd like to embellish.

Does this provide you with enough information to get your developer started?

**Comment by jlukus** [comment]
Hi Kameron,

Thank you very much for your prompt reply!

I will forwarding the information on to the individual who is responsible for making the updates to the site.  I apologize for my lack of technical background, but I would appreciate if you could please give me a bit more detail for the below items, so that I understand what I am sending to her.

(1) clone the repo, What does this mean?

(2) follow the steps in the README ('Install build tools and dev dependencies') Where is this information located?
Thanks again!
Jackie


[Lightwell]<http://www.lightwellinc.com/>



Jacqueline Lukus
Recruiter Coordinator
Lightwell
www.lightwellinc.com<http://www.lightwellinc.com/>
Jackie.Lukus@lightwellinc.com
p +1 (614) 918-9895
[Twitter]<http://twitter.com/lightwellinc>

[LinkedIn]<http://www.linkedin.com/company/lightwell-inc>

[Facebook]<http://www.facebook.com/Lightwellinc/>

[YouTube]<http://www.youtube.com/user/lightwellinc>

[Blog]<http://info.lightwellinc.com/blog>

**Comment by bulbajackel** [comment]
@jlukus Cloning the repo is making a copy of the code to edit yourself.  You will also be able to find the location of the README file here https://github.com/bullhorn/career-portal   At the bottom of the page it includes the steps to get started with building your own portal to test out.   The code is also documented really well to determine where you will make the required changes.     

I will say though, a iframe can do a lot in terms of customization. Your developer will be able to add it to your site with relative ease.   An example implementation that is often shared is [here](http://itrgroup.com/careerportal/).

**Comment by krsween** [comment]
Thanks for the help @bulbajackel! @jlukus if you have any more questions for us, please let us know. Otherwise, I'll mark this issue as closed. 

Best of luck as you build out your Career Portal!

**Comment by jlukus** [comment]
Thank you both for your help!
