### ISSUE TITLE
Site not displaying HTML

### ISSUE THREAD

**Issue by saltinajo** [bullhorn/career-portal#48]
INSERT SHORT DESCRIPTION EXPLAINING THE HIGH-LEVEL REASON FOR THE NEW ISSUE HERE.

## Current behavior
Load site and it is just blank.  Used to display the jobs and the powered by Bullhorn logo but now it's just blank.  I have reloaded the site several times from scratch and nothing.
-

## Expected behavior
Expect to see the landing page with jobs

-

## Steps to replicate behavior

1. Go to site and nothing displays.

## Screenshots

__Current__
![screen shot 2016-03-31 at 10 56 31 am](https://cloud.githubusercontent.com/assets/18193608/14182066/6322a5b2-f72f-11e5-8f1f-e777ce206b4c.png)

__Expected__
![unnamed](https://cloud.githubusercontent.com/assets/18193608/14182050/4fb229bc-f72f-11e5-87ba-b254bd57d66f.png)

**Comment by krsween** [comment]
Hi, @saltinajo —

Can you send us a link to this instance of your app?

**Comment by saltinajo** [comment]
http://www.aviztech.com/careerportal

T

**Comment by krsween** [comment]
Looks like there's an error in your `app.json`

http://www.aviztech.com/careerportal/app.json#

**Comment by krsween** [comment]
If you replace `â€œ` with a double-quote `"`, this should fix your issue.

**Comment by saltinajo** [comment]
Ok.  Oops.  Fixed that but it still isn't displaying.  Do you still see the
error?

**Comment by krsween** [comment]
You probably need to rebuild the app `grunt build` now that that configuration is all set and then deploy that to your site. 

Have you tried that?

**Comment by krsween** [comment]
Or not:

<img width="1151" alt="screen shot 2016-03-31 at 12 08 15 pm" src="https://cloud.githubusercontent.com/assets/5342395/14182457/43626d34-f739-11e5-90ab-cf0e345217b0.png">

**Comment by saltinajo** [comment]
Gracias.  Thanks for sure a quick reply.  Much appreciated.
