### ISSUE TITLE
jobInfoChips does not display the correct value for 'type'

### ISSUE THREAD

**Issue by icasnerd** [bullhorn/career-portal#486]
TO DISPLAY THE PRIORITY ASSIGNED TO THE JOB BY RECRUITERS IN BULLHORN ATS

## Current behavior

- When you update the 'jobInfoChips' json object in app.json to display 'type'--which is the priority a job is assigned by the recruiter in Bullhorn ATS. However, the returned value is an integer and not the actual string value selected by the recruiter in the backend. 

## Expected behavior

- According to the documentation for 'jobInfoChips', we should be receiving the actual value selected in the backend. 

## Steps to replicate behavior

1. Install the Career Portal in WordPress and connect it to your Bullhorn account.
2. In the Career Portal settings page, find the field that says "fields to use in API requests" and add _type_ to the field list. This is the priority field recruiters use to select the priority for a job.
3. Then find a field called "fields to display as chips on your jobs. default is 'employmentType'" and enter the field _type_. 
4. Now load the Career Portal and you should see integers instead of the Priorities available to assign a job.

## Screenshots

__Current__

<img width="716" alt="Screen Shot 2022-08-03 at 10 40 22 PM" src="https://user-images.githubusercontent.com/5786237/182758161-588be909-3157-42ed-ade5-028fe574dede.png">

__Expected__

<img width="716" alt="Screen Shot 2022-08-03 at 10 40 22 PM" src="https://user-images.githubusercontent.com/5786237/182758712-8a56e6f5-7f8c-4784-a10e-4b9b7e203145.png">

**Comment by pbearne** [comment]
Hi Victor,  I may be able to help.

Try removing the values in Bullhorn, so you have just the labels 

We have had to filter this a few times in Matador Jobs
If the client can't then reach out.

Paul

**Comment by icasnerd** [comment]
Thanks for sharing, Paul. I will look into.

**Comment by pbearne** [comment]
Hi Victor,
This is fixable in matador Jobs as we have filters that allow this
Contact me at paul@matadorjobs.com, and we'll jump on a call so I can show you how.

Paul

**Comment by icasnerd** [comment]
Hi Paul,
Nevermind. After some debugging, we found the issue and fixed it.
