### ISSUE TITLE
Hello, we are getting intermittent errors when applicants try to submit an application through the WordPress bullhorn plugin on the website www.qanalysts.com/careers 

### ISSUE THREAD

**Issue by wandke** [bullhorn/career-portal#511]
INSERT SHORT DESCRIPTION EXPLAINING THE HIGH-LEVEL REASON FOR THE NEW ISSUE HERE.

## Current behavior
When pressing Apply, sometimes it goes through and is submitted, sometimes the user gets an error.
-

## Expected behavior
The application should be submitted every time.
-

## Steps to replicate behavior

your team sent me this after we reported the issue:  When troubleshooting these issue with Support we attempted to replicate the issue in two instances. Both instances were able to submit the application. One was submitted for 'Data Collection and Quality Control Technician' and the second was for 'Site Lead III' (the same one that was presented in the screenshot that was provided). I have also attached a video of this troubleshooting step to our Ticket for documentation.

## Screenshots

__Current__

__Expected__

**Comment by pbearne** [comment]
Did you get this solved?

I am reaching out as a Bullhorn Partner.
I would love to discuss your job board and why you might want to upgrade.
I have created a short whitepaper to help explain -
https://matadorjobs.com/why-replace-oscp-with-matador-jobs/

If you are not the right person, can you connect me to them?
