### ISSUE TITLE
LinkedIn Sign-in Window Does Not Appear

### ISSUE THREAD

**Issue by mpukita** [bullhorn/career-portal#52]
INSERT SHORT DESCRIPTION EXPLAINING THE HIGH-LEVEL REASON FOR THE NEW ISSUE HERE.

## Current behavior

When using "apply with LinkedIn" on our Bullhorn Career Portal:

http://www.fastswitch.com/careerportal/#/jobs/

... the selection never results in a connection to LinkedIn.  Pop-ups are allowed and we've tried this on Chrome, Firefox, and Safari.  

There is also no results when trying to select the "here" option from:

"Heads Up! If the LinkedIn sign in page does not appear shortly, please make sure your browser allows pop-ups. Click **here** to retry."

All other integration using the LI API appear to be working within candidates, contacts, etc.

## Expected behavior

When using the "Apply with LinkedIn" option on a job displayed on the BH Career Portal, a window to sign into LinkedIn should/would appear.

"here" selection would actually result in something happening when selected.

## Steps to replicate behavior

1. Go to http://www.fastswitch.com/careerportal/#/jobs/

2. Select any job displayed

3. Try to apply using LinkedIn.

4. Once this fails, try selecting the "here" option to retry the request.

![screen shot 2016-04-11 at 7 35 42 am](https://cloud.githubusercontent.com/assets/18218668/14425865/854657ce-ffb8-11e5-9051-b28804f0bc84.png)

**Comment by kbushkoBH** [comment]
Hi @mpukita - It sounds like your domain root might not have saved correctly within the LinkedIn App you created at developer.linkedin.com - Can you verify you have added and saved http://www.fastswitch.com/careerportal as a value to the "Valid SDK Domains" input located in the JavaScript Settings tab for your app?

**Comment by mpukita** [comment]
Just did so, but there may be a disconnect between how we are accessing the
LI API since the key on my account is different than theone BH entered for
us ­ we crossed wires.

We¹ll see if this helps.  Thank you!


From:  kbushkoBH <notifications@github.com>
Reply-To:  bullhorn/career-portal
<reply+0115feacf924e2a90e9b039b9cc7e2fcef780b44555a5f7892cf00000001132363179
2a169ce08c92a9e@reply.github.com>
Date:  Monday, April 11, 2016 at 9:05 AM
To:  bullhorn/career-portal <career-portal@noreply.github.com>
Cc:  Mark Pukita <mpukita@fastswitch.com>
Subject:  Re: [bullhorn/career-portal] LinkedIn Sign-in Window Does Not
Appear (#52)


Hi @mpukita <https://github.com/mpukita>  - It sounds like your domain root
might not have saved correctly within the LinkedIn App you created at
developer.linkedin.com - Can you verify you have added and saved
http://www.fastswitch.com/careerportal as a value to the "Valid SDK Domains"
input located in the JavaScript Settings tab for your app?


You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/bullhorn/career-portal/issues/52#issuecomment-208330487>

**Comment by kbushkoBH** [comment]
That's a good point too, @mpukita - the ClientID provided by Bullhorn for your LinkedIn Recruiter Integration should not be used for the Apply with LinkedIn feature on your Career Portal. 
If you've created an app at developer.linkedin.com specifically for the Apply with LinkedIn feature, you will want to use the ClientID referenced in the Authentication section of that page, and not the one provided by BH previously. 
If you update your app.json to include the ClientID you created independently, that should get you up and running. Apologies for the confusion - we've updated our setup instructions to help clarify this part going forward.

**Comment by mpukita** [comment]
Giving that a try.  Thanks!

**Comment by mpukita** [comment]
Any idea how long it takes for changes like these to roll out in production with LI and BH?

**Comment by mpukita** [comment]
LinkedIn sign-in window now displaying.  Changing the API key / Client ID did the trick.
