### ISSUE TITLE
Feed won’t validate: remove "children" element from RSS feed

### ISSUE THREAD

**Issue by davidfchuck** [bullhorn/career-portal#527]
INSERT SHORT DESCRIPTION EXPLAINING THE HIGH-LEVEL REASON FOR THE NEW ISSUE HERE.

## Current behavior  The generateXml.ts file inserts element name "children" into the RSS feed.  After 2 weeks of using the new dynamic hosted OSCP, Google Console still only identifies one link within the RSS (we have 141 job openings currently).   After investigating, I'm attempting to validate the RSS feed per W3.org.  I've got it all nailed down, except this.

-

## Expected behavior - I'd like each job listing to populate within the "channel", but without the "children" tag/.  "children" just needs to be invisible within RSS feed.

-

## Steps to replicate behavior

1.  Setup your instance of the OSCP.  Visit (yourdomain)/feed.  View the page source, or have the RSS Feed validated at https://validator.w3.org/feed/.

## Screenshots

![children in rss feed](https://github.com/bullhorn/career-portal/assets/101425444/0b96ac34-044f-41dc-9c40-60e4f38743b1)

__Expected__
RSS feed to validate without being wrapped in ‘children’ .. rename “children” object to something valid within RSS language.

**Comment by davidfchuck** [comment]
I figured out a work around...
by including ".children" in the jsonxml push... it removed the parent tag 'children' in the feed, and also removed the title/link/description.  It's good enough for now... Google reads all 142 links now. Thx

**Comment by pbearne** [comment]
Hi David 

Where are you trying to read the RSS from?

Most Job board need custom feeds

Paul
