### ISSUE TITLE
Error when applying with LinkedIn

### ISSUE THREAD

**Issue by mpukita** [bullhorn/career-portal#54]
INSERT SHORT DESCRIPTION EXPLAINING THE HIGH-LEVEL REASON FOR THE NEW ISSUE HERE.

## Current behavior

Cannot seem to apply for positions using the LinkedIn apply feature.  Receive this result on Chrome and Firefox:

![screen shot 2016-04-11 at 10 19 06 am](https://cloud.githubusercontent.com/assets/18218668/14430316/0c254d2a-ffcf-11e5-95cb-4e0f5d6fa4c6.png)

## Expected behavior

Ability to apply.

## Steps to replicate behavior

1. Go to job:

http://www.fastswitch.com/careerportal/#/jobs/31197

2.  Try applying using LinkedIn

(I tried my profile:  https://www.linkedin.com/in/markpukita

**Comment by mpukita** [comment]
Tried with a different email address and it worked.  Does this present a problem for applicants who are already in our BH database being able to apply for a (new) job?

**Comment by kbushkoBH** [comment]
If you have returning applicants whose candidate records are active in Bullhorn, they should be able to apply as often as desired. However, we are aware of (and are currently investigating) an issue that occurs when an applicant uses an email address that is associated to a deleted candidate record in the associated database. Is it possible your email was added to a test candidate that was later deleted?

**Comment by mpukita** [comment]
Yes.
Mark PukitaCEOFast Switch, Ltd.614.336.3690mpukita@fastswitch.com 

-------- Original message --------

**Comment by krsween** [comment]
Thanks @kbushkoBH for tackling this.  :+1:  

@mpukita if you have any additional questions feel free to reach out. I'm going to mark this issue as closed.

**Comment by SyedHannan786** [comment]
Dear All,

I am facing the exact same issue while applying for jobs at linked In. I will be highly thankful if anyone could help me out.

**Comment by jfkquality** [comment]
I saved the application then went back to the job and clicked Continue, completed applying and submitted successfully.
