### ISSUE TITLE
Easiest way to ONLY modify colors / contrast for Career Portal

### ISSUE THREAD

**Issue by mpukita** [bullhorn/career-portal#56]
We find the color scheme makes it hard for applicants to "see" or "find" the sliders, etc., because their shade is so close to the adjacent entities.  Is there a very simple way to modify the colors ONLY?  

I know enough about this to be extremely dangerous.  I can see the parameters for the colors in the src/app/index.scss file.  Can we use this locally on our server and modify, or is it more complicated than this?

Again, a fool with a tool is still a fool (that would be me).

**Comment by jgodi** [comment]
The colors there are application wide. You will find the styles for the sidebar and the filters here: https://github.com/bullhorn/career-portal/blob/master/src/app/sidebar/sidebar.scss#L180. There you can modify the colors for the sidebar/inputs for your build and customize it as much as you need.

Let us know if you need any further guidance.
