### ISSUE TITLE
Closed Jobs Displaying

### ISSUE THREAD

**Issue by jontheophilus** [bullhorn/career-portal#62]
INSERT SHORT DESCRIPTION EXPLAINING THE HIGH-LEVEL REASON FOR THE NEW ISSUE HERE.

## Current behavior

- We've noticed several "closed" job orders are showing up in the job portal search results.

## Expected behavior

- Closed job orders in Bullhorn should no longer show up in the search results or allow applications.

## Steps to replicate behavior

- We can provide example job order numbers in our Bullhorn instance for testing.

**Comment by bulbajackel** [comment]
Hello Jon,
Can you provide a link to the jobs that should not be on your career portal?

**Comment by kbushkoBH** [comment]
Hi Jon, I just spoke with a member of the BH Support team and we believe both the closed jobs and the sort order issues may be related to the configuration of your app file, which appears to contain values associated to a staging environment and not a production environment. 
Please feel free to let us know here or let support know whether updating the values in the app file does the trick. Btw, your site looks great!

**Comment by jontheophilus** [comment]
Yes - I can confirm this, we were given corp tokens that point to our staging instance of Bullhorn, not our production instance.
