### ISSUE TITLE
Question: Sorting Results

### ISSUE THREAD

**Issue by jontheophilus** [bullhorn/career-portal#63]
INSERT SHORT DESCRIPTION EXPLAINING THE HIGH-LEVEL REASON FOR THE NEW ISSUE HERE.

## Current behavior

- When you have no filters selected, how does the results get sorted? I'm seeing a lot of jobs from 2015 showing up first. 

## Expected behavior

- I would think regardless of which filter you use (location/category) it should order the jobs by date added (most recent first) or give the user the option to sort/filter by the various columns (job title, location, etc).

## Steps to replicate behavior

1.

## Screenshots

__Current__

__Expected__

**Comment by bulbajackel** [comment]
Hello Jon, 
In my experience I have noticed that the order that jobs are sorted is the order that jobs are published from within Bullhorn.

**Comment by bulbajackel** [comment]
Also, to add to my previous comment, to move a job to the top you can use the republish button within the Bullhorn publish screen.

**Comment by jontheophilus** [comment]
Yes - I can confirm it's sorting by date added. Our display issue was related to another issue that's been resolved. I still think some additional filtering/sorting options would be a nice feature to add down the road.
