### ISSUE TITLE
Location List - Duplicate Cities After Selection

### ISSUE THREAD

**Issue by jontheophilus** [bullhorn/career-portal#64]
## Current behavior

-Selecting a city in the Location filter seems to cause duplicate entries for some cities in the location list.

-Clearing the location list does not seem to reset the location list back to a distinct list.

-I am noticing this behavior using a fresh copy of the career portal, pointing to our production instance of Bullhorn.

-When I use the same code, and point it to our staging instance of Bullhorn, this does not happen.

-Tested in Chrome, Edge, and Firefox
## Expected behavior
- City should only be shown once in the list.
## Steps to replicate behavior
1. Visit [Cloned Copy of BH Career Portal](http://dev-bullhorn-portal.netlify.com/)
2. Select 'Carmel, IN"
## Screenshots

Nothing selected:
![capture](https://cloud.githubusercontent.com/assets/420029/14830110/f966374a-0bbc-11e6-92fe-3a6cffcbc3b5.JPG)

City Selected:
![capture2](https://cloud.githubusercontent.com/assets/420029/14830102/eb68cc20-0bbc-11e6-966e-4453a4f8843d.JPG)

**Comment by bulbajackel** [comment]
Hey,  I apologize for the time, but I have seen this before, this is because in your system that you have closed jobs that are still published in that location.     I suggest unpublishing those before closing them and it should resolve this issue.
