### ISSUE TITLE
How to set up Email Notification when new Web Response 

### ISSUE THREAD

**Issue by tim41916** [bullhorn/career-portal#65]
INSERT SHORT DESCRIPTION EXPLAINING THE HIGH-LEVEL REASON FOR THE NEW ISSUE HERE.

## Current behavior

-

## Expected behavior

-

## Steps to replicate behavior

1.

## Screenshots

__Current__

__Expected__

**Comment by jeremy-dobler** [comment]
Hi @tim41916 

We are actually in the process of implementing this in our public backend REST service. You can look forward to it being released in the following months.

To answer your question, it is not actually possible to send an email directly from Javascript. You would have to set up a backend service to do it for you. For more information, see http://stackoverflow.com/questions/7381150/how-to-send-an-email-from-javascript. But luckily, we are creating and maintaining this service for you :)

**Comment by DaveGarlock** [comment]
It looks like emails are now going out. My question now is if there's any way to control the content of the emails: what's being sent now could be made much more useful with this ability. For example, putting the job title in the subject line and putting candidate information in the body instead of the job description.

**Comment by bulbajackel** [comment]
Hey Dave, 

Currently there is not a way to edit that within the Career Portal files since this is on Bullhorn's end.  That will have to be implemented in to the Bullhorn Service itself.

**Comment by DaveGarlock** [comment]
Ha - I had asked a Bullhorn support person first, figuring that was where this was controlled, and he told me that they had no control over it and I should ask here. Ah well, thanks for your help - I'll try to find a Bullhorn support person who knows more.

**Comment by krsween** [comment]
Hey, @DaveGarlock—I'm going to follow up with our internal support team directly and try to identify where our conversations broke down. 

I'm sorry that you haven't received the correct information, but I will be sure to address this and once I have more information I'll reach out to you directly or post a follow up. Thanks for your patience!

**Comment by krsween** [comment]
Update: @DaveGarlock I've talked with our CS team and they will be reaching out to you this afternoon or first thing tomorrow morning with additional information. Thanks again for your patience.

**Comment by DaveGarlock** [comment]
That sounds great. Thank you.
