### ISSUE TITLE
Request for XML feed from career portal

### ISSUE THREAD

**Issue by kbushkoBH** [bullhorn/career-portal#69]
In the legacy version of the Bullhorn Career Portal, an XML feed was automatically generated when jobs were published and the feed and could be shared freely to third party sites and job boards. 
## Current behavior
- Currently there is no freely accessible XML feed associated with the career portal, although Bullhorn offers built in options for sending jobs to Indeed and SimplyHired.
## Expected behavior
- Career portal users would like to be able to send their postings via XML to various destinations beyond Indeed and SimplyHired.

**Comment by DaveGarlock** [comment]
Hi. Does anyone have any idea when this change will go live, roughly? Bullhorn apparently stopped offering XML feeds otherwise, so this seems pretty necessary for this to be a viable job listing tool.

**Comment by jmccardle77** [comment]
Hi, I am curious about this as well.

**Comment by pbearne** [comment]
HI Guys
We have this as part of the Matador WordPress plugin if that helps
[https://matadorjobs.com/products/jobs-xml-feeds/](https://matadorjobs.com/products/jobs-xml-feeds/)
