### ISSUE TITLE
500 error api connection

### ISSUE THREAD

**Issue by graph-io** [bullhorn/career-portal#72]
INSERT SHORT DESCRIPTION EXPLAINING THE HIGH-LEVEL REASON FOR THE NEW ISSUE HERE.

## Current behavior
New Career Portal Have yet to successfully display job listings
-

## Expected behavior
Display job listings in Bullhorn
-

## Steps to replicate behavior

1. access the website: https://jobs.globalpathsolutions.com/

## Screenshots

__Current__
Errors listed in Google Inspector Counsel: 
https://public-rest32.bullhornstaffing.com/rest-services/239ARD/query/JobBo…tion,isOpen,isPublic,isDeleted&count=20&orderBy=-dateLastPublished&start=0 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
2https://public-rest32.bullhornstaffing.com/rest-services/239ARD/search/JobO…showTotalMatched=true&query=(isOpen:1)&fields=id&sort=id&count=500&start=0 Failed to load resource: the server responded with a status of 500 (Internal Server Error) 

__Expected__

200 OK

I do not see any logs available. Are there any beyond my host provided PHP/Apache logs?

Ian

**Comment by kbushkoBH** [comment]
Hi Ian,

Bullhorn Support needs to complete the setup by matching your site to your database. I've sent them https://jobs.globalpathsolutions.com so they can complete the enablement and they will be reaching out to you shortly to confirm.

**Comment by krsween** [comment]
Hi, @graph-io—

To answer your other question:

> I do not see any logs available. Are there any beyond my host provided PHP/Apache logs?

Typically REST services just emit a status code (in this case a 500) indicating a generic error and then we comb through our logs to see where the particular problem lies. In this case, Bullhorn support is still working on enabling this feature for you. That wouldn't show up on your server logs.

I'll leave this open until our support team finalizes this. =)

**Comment by krsween** [comment]
Looks good to me! 👍
