### ISSUE TITLE
Ability to easily customize Job Title

### ISSUE THREAD

**Issue by cubexg** [bullhorn/career-portal#74]
Upon discussions at BH Engage, we are looking for a way to customize the Job Title easily on a per job basis.  We are looking to emulate functionality that Bullhorn Reach gave us, but the current iteration of the career-portal does not allow us to do this without either modifying the overall XML schema and using a different API pull, or doing back-end work and creating a new set of pulls.  We currently have a custom text field being used in our instance that allows for a custom job title, but the API pulls are limited.

Any suggestions to build this functionality in would be great.  Thanks!
## 
## 
## Steps to replicate behavior

1.
## Screenshots

**Current**

**Expected**

**Comment by charlesabarnes** [comment]
Hey Dave, 

Going through a couple of older issues and this one I wanted a bit of clarification on as we have a simpler way of achieving this and I wanted to see if this is what you were looking for.  

You are able to modify the fields that are accessible within the public API by contacting Bullhorn Support.   After that is done, you are able to change on the [frontend what fields are being pulled into the portal](https://github.com/bullhorn/career-portal/blob/master/src/app/services/search.service.js#L18).  After the fields are changed, you are then able to replace job.title with [job.customText3](https://github.com/bullhorn/career-portal/blob/master/src/app/list/list.html#L13) (or something similar) wherever you need it. 

I am gonna close this now as the API calls are more open for this purpose.  Please let me know if you have any questions however.
