### ISSUE TITLE
Specific Pull from Private Label

### ISSUE THREAD

**Issue by cubexg** [bullhorn/career-portal#76]
Looking for a way to pull from a specific PL rather than entire DB if possible.  

## Current behavior
CP pulls all data across all Reqs - want to filter to only a specific PL.
-

## Expected behavior

-

## Steps to replicate behavior

1.

## Screenshots

__Current__

__Expected__

**Comment by pbearne** [comment]
This might not help but you can do that with the WordPress plugin https://wordpress.org/plugins/bh-staffing-job-listing-and-cv-upload-for-wp/

**Comment by krsween** [comment]
This issue has been escalated to internal support.
