### ISSUE TITLE
How do you iFrame the Portal into your webpage?

### ISSUE THREAD

**Issue by BullhornUser** [bullhorn/career-portal#77]
How do I iframe the portal into my website?

**Comment by bulbajackel** [comment]
Hello, 

To create an iframe on your website for the portal you will want to insert code into your website where you would like it located using the Iframe tags.   ex.  `<iframe src= "careerportaladdress.com"/>`  

To learn more about using iframes please refer to this article http://www.w3schools.com/tags/tag_iframe.asp.  

Feel free to let me know if you have any more questions
