### ISSUE TITLE
Meta property tags for social sharing

### ISSUE THREAD

**Issue by bulbajackel** [bullhorn/career-portal#78]
Hello,

I wanted to start a discussion about social media sharing and how links appear on sites such as Facebook. Currently, whenever a career portal link is shared on facebook, it is fairly bland (examples will be provided below).  Currently what controls the content that appears are meta tags that is included in the head of index.html.  When adding this simple information, it can make your social media sharing more professional and attractive in the appearance.   

Here below, there is an example of the current appearance of the Bullhorn links shared from within Bullhorn or the link pasted directly to facebook.
### Current appearance

![image](https://cloud.githubusercontent.com/assets/4327754/17080678/5f5a69c4-50fd-11e6-8689-1101bdcb1cb9.png)

Adding this code to the head of index.html (after building my career portal) has generated this "potential appearance"

```
<meta property="og:url" content="https:/acme.com/" />
<meta property="og:image" content="http://i.imgur.com/rzJuFL5.png" />
<meta property="og:title" content="cool job!" />
<meta property="og:description" content="This job is great!" />
```
### potential appearance

![image](https://cloud.githubusercontent.com/assets/4327754/17080692/21e00f9e-50fe-11e6-9620-40f662b8d6e3.png)

I used [this tool ](https://developers.facebook.com/tools/debug/) from facebook to generate the above images for testing purposes.    

Since this site is built on Angular there is the potential of including the job titles on the share links however, this will introduce a new controller file, additions of bound data values in the meta tags, and potential modifications to the gulp build files (which I am not too familiar with).  Any thoughts on this implementation?   I would love to see what discussions sprout from this topic!

**Comment by piersrr** [comment]
Did anything happen with this? Would love to see this implemented or ways others have had a go at it

**Comment by RichardCore37** [comment]
Hi Charles, has there been any progress here? Our career portal has just gone live and when I share one of the vacancies on social media it doesn't scrape an image, the job title, nor any job description. I would like the option to automatically scrape an image of choice, include the job title and summary. Is this possible?

**Comment by pbearne** [comment]
Hi Richard
Just had a look at your site and it doesn't look like you are using the OSCP so you will have to talk to webflow team / your developers to fix this

**Comment by RichardCore37** [comment]
Hi Paul, yes it is the OSCP. It's just been restyled to fit into our website styling.
