### ISSUE TITLE
follow all set of commands, but portal i think not installed

### ISSUE THREAD

**Issue by djeet** [bullhorn/career-portal#79]
I follow all commands to setup bullhorn career portal, but i think its not working. Can someone help me.

See below what i did
1. first clone the career portal
2. node install, bower install, gulp install
3. fire gulp command

after that fired 2 commands
## 

gulp --corpToken='[CORP_TOKEN]' --sl='[SWIMLANE]' --companyName='[COMPANY_NAME]' --liClientId='[LINKED_IN_CLIENT_ID]'
gulp serve --corpToken='[CORP_TOKEN]' --sl='[SWIMLANE]' --companyName='[COMPANY_NAME]' --liClientId='[LINKED_IN_CLIENT_ID]'
## 

I think here i am missing some info.
I have corp token, swimlane, i used bullhorn login as company name and linked id

but no such processing when hit. so something is wrong

my main focus on bower as when i hit bower install no such processing done

and this is my directory structure
http://puu.sh/qotnW/0236e0db5f.png

I think setup didn't installed properly too.

Can you guide what went wrong.

Thanks!

**Comment by bulbajackel** [comment]
Hello Djeet,

it looks like you are running linux, which version of node did you install? Also, what linux distribution are you using? I want to attempt to reproduce this.

**Comment by djeet** [comment]
Hello bulbajackel,

Yes its 'Ubuntu 14.04.3 LTS'

node js - v0.10.25
npm - v1.3.10

http://puu.sh/qpd1T/423479dcb0.png

Let me know.

Thanks!

**Comment by jgodi** [comment]
Thank you @djeet! Can you try updating your version of NodeJS/NPM? 

If that doesn't work, do you mind posting the output from your terminal when running the `gulp` command?

Hope that helps!

**Comment by krsween** [comment]
@djeet are you still unable to run CP?

**Comment by char2** [comment]
Hello Guys,

There is much progress from last time. There were issues with the last server. Tested on new, kindly see below:

nodejs version - 0.10.37
http://puu.sh/qxSP9/2c97c46466.png

npm version - 1.4.28

git version
http://puu.sh/qxSQm/6c431a52cb.png

npm install -g bower
http://puu.sh/qxSME/d80e5abad6.png

npm install -g gulp
http://puu.sh/qxSSU/1a548bf328.png

npm install
big response, ending is like
http://puu.sh/qxT65/29110dcf6b.png

bower install
http://puu.sh/qxTdS/6f577b0209.png
then bower install with --allow-root
long output, last response - http://puu.sh/qxUba/c15bc68a7a.png

gulp build
http://puu.sh/qxUgc/2103093bf5.png

then
gulp --corpToken='[token]' --sl='[swimlane]' --companyName='[company]' --liClientId='[linkedid]'
http://puu.sh/qxUsO/bdb5ae1d57.png

this is the directory structure now
http://puu.sh/qxUMi/85cf1be7e7.png

is it correct?

**Comment by djeet** [comment]
Hello Guys,

There is much progress from last time. There were issues with the last server. Tested on new, kindly see below:

nodejs version - 0.10.37
http://puu.sh/qxSP9/2c97c46466.png

npm version - 1.4.28

git version
http://puu.sh/qxSQm/6c431a52cb.png

npm install -g bower
http://puu.sh/qxSME/d80e5abad6.png

npm install -g gulp
http://puu.sh/qxSSU/1a548bf328.png

npm install
big response, ending is like
http://puu.sh/qxT65/29110dcf6b.png

bower install
http://puu.sh/qxTdS/6f577b0209.png
then bower install with --allow-root
long output, last response - http://puu.sh/qxUba/c15bc68a7a.png

gulp build
http://puu.sh/qxUgc/2103093bf5.png

then
gulp --corpToken='[token]' --sl='[swimlane]' --companyName='[company]' --liClientId='[linkedid]'
http://puu.sh/qxUsO/bdb5ae1d57.png

this is the directory structure now
http://puu.sh/qxUMi/85cf1be7e7.png

is it correct?

**Comment by bulbajackel** [comment]
Hey, djeet, your commands put a built and a ready to be uploaded version of the career portal in the /dist directory. Currently what is shown in the screenshots is correct.  

If you upload the contents of dist to your webserver, what happens?
