### ISSUE TITLE
Apply Process -- Apples Pages File Format Error

### ISSUE THREAD

**Issue by cdues** [bullhorn/career-portal#80]
Does Bullhorn have any plans to support Apples "Pages" file format. If not, is there a workaround we can use for these file formats? 

Maybe redirect the application to a 3rd party who can convert the pages file format to a supported file extension? 

 

![pages example](https://cloud.githubusercontent.com/assets/20928131/17518297/63af35e8-5e15-11e6-8f59-103f155944f0.png)

**Comment by krsween** [comment]
Hey, @cdues—As a Pages user, it is a little irritating to have to convert everything into .docx or .pdf files, but until Apple open sources their file types, they can only be read by Apple's software. Since our parser isn't written on OSX, that prevents us from being able to support parsing .pages or any Apple proprietary format. Should that change I will convert this issue to triage. I hope this helps!

**Comment by cdues** [comment]
Kameron,

Thanks for the quick reply!

There are 3rd party systems/parsers  that can handle pages… is there any way to point the portal application towards that system?

Workflow:
BH Portal  Apply--> 3rd Party Parser --> Load via the BULLHORN API.

Chris Dues – Service Delivery Manager



c.dues@daxtra.com <mailto:c.dues@daxtra.com>


T: (804) 767-1351 ext. 7003


F:  (540) 301-6470


daxtra.com<http://www.daxtra.com/>

**Comment by krsween** [comment]
There are services that do that. @bullhornthompson was actually telling me about one he found.

You could modify the POSTing of resumes on your instance of CP to submit certain file-types to a third-party API and then wire in a deferred method to POST that converted file to our API. The POST URL is in the [apply.service.js](https://github.com/bullhorn/career-portal/blob/master/src/app/services/apply.service.js) and the form validation of file types can be modified in the [modal.controller.js](https://github.com/bullhorn/career-portal/blob/master/src/app/modal/modal.controller.js) file.

**Comment by krsween** [comment]
You could also wire into the type-validation of that file type and offer a link to convert the file somewhere, or instructions on how to convert it locally. Just a few ideas...

**Comment by cdues** [comment]
Kameron – Thank you so much!! We are going to try and handle this via the DAXTRA CAPTURE solution ( check marketplace for more info)

Chris Dues – Service Delivery Manager



c.dues@daxtra.com <mailto:c.dues@daxtra.com>


T: (804) 767-1351 ext. 7003


F:  (540) 301-6470


daxtra.com<http://www.daxtra.com/>
