### ISSUE TITLE
Customizing the display of BH Jobs pages in WordPress

### ISSUE THREAD

**Issue by rduermyer** [bullhorn/career-portal#84]
II am working with a client who has a WordPress site using Bullhorn. When a visitor clicks on the list of available jobs and when the visitor clicks through to a specific job, the client would prefer that the page layout match the rest of his site and that the navigation menus be available for Job Seekers to click through to other areas of the site. Is it possible to display the Bullhorn jobs inside an iframe or something on the page? That would also allow me to include his Google Analytics code when the page is displayed. 

I tried adding the Bullhorn code to a new WordPress page template, but Bullhorn doesn't display at all.  If that's not possible without using an expensive WordPress plugin, is it possible to add a code snippet inside the Bullhorn code that would open a new window when Bullhorn is loaded? At least that way, visitors could get back to the site without cycling through multiple back button clicks.

Your assistance and guidance would be greatly appreciated.

**Comment by bulbajackel** [comment]
Hello rduermyer,

This would be possible with using an iframe on your WordPress page.   You may require a plugin such as https://wordpress.org/plugins/iframe/ but it will ensure that you put a window of your career portal into the site and the navigation bar as well as any styling you have surrounding the Iframe would be visible. 

Please let me know if you have any questions.

**Comment by pbearne** [comment]
or you can use the plugin https://wordpress.org/plugins/bh-staffing-job-listing-and-cv-upload-for-wp/and have native listing with good SEO support ( no SEO with an iframe )

**Comment by rduermyer** [comment]
All set. Looks great. Thanks!

**Comment by rduermyer** [comment]
Now that the page is successfuly displaying in an iframe on the site, it opens with the Filter (search) pane collapsed. The client would like it to display with the Filter pane expanded when opened, just as it does if I go directly to the standard Jobs page without pulling it into an iframe. Any thoughts?

**Comment by bulbajackel** [comment]
Hey,

Whether or not the Filters panel is expanded is determined by the horizontal resolution of the window/iframe.   If you expand the iframe width to be wider than 768px it should be expanded by default.

**Comment by rduermyer** [comment]
Thanks! Though 768px didn't work for me, 1100 sure did.

**Comment by GLenotre** [comment]
Is there a way to do this without using an iframe?

**Comment by pbearne** [comment]
no
This is a node app and isn't compatible with WordPress (PHP)
 
You may need to use the WP plugin
https://wordpress.org/plugins/bh-staffing-job-listing-and-cv-upload-for-wp/
https://github.com/pbearne/Bullhorn2WP - use this version

Paul

**Comment by bulbajackel** [comment]
Hey Glenotre,

When utilizing the portal, what are you achieve? As far as keeping styling and a nav bar, you do have the option that Paul mentioned or usually we suggest an iframe.   Please let me know how I can help or maybe a direction I can guide you and I'll be happy to help.

**Comment by krsween** [comment]
I definitely like with @pbearne's solution, but I wanted to clarify a few details about Career Portal.

> This is a node app

Just to clarify a little bit: We use node as a tool for bundling this application and for things like managing our dependencies and it can be used for serving the app,  but you don't need node to host this application. You could certainly setup a node server for this app really easily and we allow that, but it's not required. You can upload our [app bundle](https://github.com/bullhorn/career-portal/releases) anywhere HTML, JS, and CSS can be served.

>it isn't compatible with WordPress (PHP)

It can be—I promise. This is a little bit technical, so bear with me. On your WordPress server you'd need to upload the source code that we [generate](https://github.com/bullhorn/career-portal/releases) and unzip it into a directory that WordPress allows us to serve it from (like plugins!) and then use an iFrame pointed to that directory to serve up the Portal. 

_...but that process really sucks..._

Which is super complicated sounding and not at all intuitive, so I made a [plugin](https://wordpress.org/plugins/bullhorn-career-portal/) to do all of that for you. With this plugin you can (1) install the plugin, (2) add your configuration details in the settings section of WordPress Admin, (3) and create a post with the code `[oscp]` in it. Then Career Portal will appear there with all your template stuff.

**Comment by GLenotre** [comment]
Thanks for all this quick help.

It's not clear to me what the plugin does that I don't already have. We already have zip file & unzipped doc in our files, and I placed it in an iFrame here: http://abbtech.com/careersportal/. I'm styling it as we speak.

What I'm trying to achieve: 1) I'm trying to match the style to our site, so I'm just changing the CSS on that. 2) Also, there's some content that is missing/changed from the original list feed like job numbers. Here's a reference: [http://ejob.bz/ATS/CompanyPortal.do?companyGK=19115](url)

**Comment by krsween** [comment]
It can make the process of customization easier because in order to customize Career Portal you'll be modifying a bunch of source code that'll then get packaged up into a `dist` directory. With the plugin you have all your settings saved in the WP Admin view, but without it you'll need to manually copy all of your settings into the app.json  or (see readme) add them as build parameters.

To brand Career Portal:
1. Clone the open source repo and follow [these](https://github.com/bullhorn/career-portal/blob/master/README.md) steps, and customize this file: `/src/app/index.scss`. 
2. Then you can build the app using this command `gulp build`
3. Then copy the `dist` contents into the Wordpress plugin directory `plugins/bullhorn-career-portal/oscp` or wherever you copied the zip of our latest release.
4. Make sure that all the setting are set in the configuration panel for the plugin in WP-Admin or in the App.JSON
5. Preview the page and make sure everything looks good.

**Comment by GLenotre** [comment]
I couldn't activate the plugin. I get this error: Parse error: syntax error, unexpected '[', expecting ')' in /var/www/vhosts/nameofmywebsite.com/httpdocs/wp-content/plugins/bullhorn-career-portal/wp-oscp.php on line 311

**Comment by krsween** [comment]
Did you add all your settings in `Plugins > Career Portal`? You'll need the [required](https://wordpress.org/plugins/bullhorn-career-portal/other_notes/) fields to be filled out. Also, what version of WP is this on? So I can create a sandbox if we need one...
