### ISSUE TITLE
Only show jobs written in current portal language

### ISSUE THREAD

**Issue by EricNLecuyer** [bullhorn/career-portal#85]
My clients want to publish their jobs both in English and French. To avoid duplicates and poorer user experience, we would like to only show jobs written in the portal's language (i.e. if the portal's locale is fr-FR, only show jobs written in French).

As a starting point, I believe that the jobs' language could be defined in Bullhorn's backend with an unused custom field. The user would have to make a separate job posting for every language. Once that's done...I am not sure what to change on the portal side. Would it be in Search Service?

In my view, the ideal solution would show the jobs with the corresponding language **and** those with an empty/unused "language" custom field value. That way, users who don't need translation could ignore it while those who do could implement it easily from the backend.

Thanks for your help and your ideas!

**Comment by krsween** [comment]
Hey @EricNLecuyer—

I think this is closely related to [Issue 58](https://github.com/bullhorn/career-portal/issues/58). Instead of filter by a company, though, you'd like to filter from a locale. Issue 58 walks through resolving a similar issue on the front end. Let me check and see if we expose a locale field via REST. 

More to come.

**Comment by john-pennington** [comment]
@krsween 's automatic country filter concept (with the portal interrogating its configured locale at runtime, and then post-fixing an additional static filter to all job searches) could support this requirement today if the country of a job is a sufficient inference for the language / locale context under which said job should display. @EricNLecuyer if you went with this approach you would want one of your locales to be the "kitchen sink" locale, where the filter is not post-fixed, so you don't drop any jobs from displaying on at least one of your Career Portals.

Additionally, we have received multiple requests to support a list of additional client-specified Job fields in the Bullhorn Public REST API (the data service that powers Bullhorn Career Portal) as an extension point for various portal customizations. For example, a client could chose to expose the [Job].customText1 field as an extended field in the Bullhorn Public REST API. It would then be available for querying, sorting, (Lucene-based) searching, grouping and faceting by Public REST API consumers, including Career Portal. Although this solution is more abstract than a static filter based on an inference, it would support a use case where a client desired to host multiple Career Portals for various regions, countries and/or languages.

This capability is currently under consideration but has not been formally assigned to our product roadmap. This GitHub issue has been linked to the internal JIRA ticket for tracking purposes @ BH-42290.

**Comment by krsween** [comment]
So close to  solution, too. I sorry we couldn't get this tied off.

As new developments emerge, I'll update this thread and #58. Thanks for your patience!

**Comment by charlesabarnes** [comment]
Hello I have been revisiting older issues and sharing new developments that we have that can possibly help.  

With the public API you are now able to leverage customText fields! to add the required fields you will need to contact Bullhorn support to make it available in your requests.  With this, you are able to add a language dropdown to your jobs or something similar that could get filtered.  Please let me know if you have any questions.
