### ISSUE TITLE
Layouting of career portal

### ISSUE THREAD

**Issue by djeet** [bullhorn/career-portal#89]
Hello Guys,

I am doing layouting of career portal
see, this is the layout I am achieving
http://puu.sh/qV6ip/c2a01c11fc.jpg
I need the `salary` and `total results` attribute

and on left side (filter area), have to add 2 new filters
http://puu.sh/qV6rn/6cb561dec7.jpg 

can anyone suggest a solution for this?
and does anyone know how to get app.js actual file, without minification?

**Comment by djeet** [comment]
I am doing regular updates in CP
see page - http://brewingcode.org/elevano_wp/career-portal/#/jobs

1. I want to know total jobs count or search result count - http://puu.sh/qW3YX/d297414e05.png
2. can I get `short description`?

Looking forward to hear a response from anyone.

**Comment by bulbajackel** [comment]
Hello Djeet,

To address your first question, you can get the total number of results by grabbing the total from the call that the search service makes when you load the career portal. 
`https://public-rest31.bullhornstaffing.com/rest-services/1BTV61/search/JobOrder?showTotalMatched=true&query=(isOpen:1)&fields=id&sort=id&count=500&start=0`

Two address the second question, by short description do you mean the description that is seen on the list view?  If so, that is just the normal description truncated after a certain number of characters. 

Please let me know if you have any questions
