### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by MDDesignstl** [bullhorn/career-portal#90]
When a Candidate is applying through the Career Portal there are times when a 500 Internal Server error is received. This is sometimes caused by a corrupted resume. This can usually be remedied easily by trying again, or re-saving the resume in word or another relevant program. However, some candidates may become discouraged easily, and will leave without ever successfully applying. We would like a remedy to this that could come in a couple possible forms:

1 )Enhanced Error Messaging: If the Resume is the issue causing the Internal server error, a message asking the Candidate to try a different Resume, or stating that the resume is corrupted would be helpful (if this is possible to determine).

2 ) Limited Profile Creation: If the Resume is what caused the Application process to fail, then maybe it could try again and create a candidate profile with limited information (Name, Email). That way we could at least contact the candidate instead of losing them.

3) Limited Profile Creation + attach file:  If the Resume is what caused the Application process to fail, then maybe it could try again and create a candidate profile with limited information, but also attach the file (but, not parse it). That way we could download the resume and try ourselves, or gain assistance from Bullhorn Support.
## Current behavior

-Applying to a Job with certain resumes may cause an Internal Server error that is generic an not helpful
## Expected behavior

-NA

**Comment by charlesabarnes** [comment]
I just wanted to update this thread.   Options 2 & 3 were added to the api to the apply query.  If there is an error parsing the resume for reasons due to formatting or corruption the candidate is still added to the system and the resume is attached to the candidate.  Please let me know if you have any questions.
