### ISSUE TITLE
Changing .Json variables

### ISSUE THREAD

**Issue by DaveGarlock** [bullhorn/career-portal#93]
I'm probably missing something obvious, because I'm fairly new to this. I'm trying to set up a new career portal, and it seems to me that to change some of the language used in the portal I should be able to change the data in variables in the json files in /res/en-US  However, when I change the variables' data, nothing seems to change on the site.

## Current behavior

For example, I change the value in sidebar.json to   "showMoreLabel": "Show More Categories" from   "showMoreLabel": "Show More", save and refresh the site; the label in the sidebar still says "Show More"

## Expected behavior

The label should change to "Show More Categories"

**Comment by bulbajackel** [comment]
Hey Dave,

Can you provide a link to your site? I wanna take a look to see if it is a caching issue or something else.

**Comment by DaveGarlock** [comment]
Sure. http://www.scionstaffing.com/jobportal/#/jobs  I have tried clearing
the cache.

Dave

**Comment by bulbajackel** [comment]
Hey Dave,

On the website, I was able to see "Show More Categories" here is a screenshot http://i.imgur.com/LYusTXy.png. Maybe it took some time to carry over to your production site?

**Comment by DaveGarlock** [comment]
Ok, with an additional clearing of the cache, I see it now too. Must have
either been that it took  time or a cacheing issue. Thanks for your help.

Dave
