### ISSUE TITLE
Not pulling job posts in Worpress

### ISSUE THREAD

**Issue by deemm** [bullhorn/career-portal#96]
I have followed the link and updated the info but on way or another i haven't been able to display my job posts at my wordpress site.

Could you please  help me with this
http://dev.deliveredoncloud.com/vernovis/portal/#/jobs

Thanks

**Comment by bulbajackel** [comment]
Hello Demm,

I suggest double checking the app.json file.  Currently the corp token looks incorrect.  You can see that here: http://dev.deliveredoncloud.com/vernovis/portal/app.json

Thanks

**Comment by deemm** [comment]
but this is what i received, 

Hi,
 
Your token is %25%27%22C%2EWPX%20%0A and your swim lane is swim lane 9

**Comment by deemm** [comment]
can you please guide me to some extent what format is for corp token ? and from where i should get it ?

**Comment by bulbajackel** [comment]
Hello Deemm,

To receive the proper format for the corp token or the swimlane, please have an authorized contact reach out to Bullhorn Support.   To contact Bullhorn Support  please follow the steps in this article http://bullhorn.force.com/pkb/articles/Documentation/Contacting-Bullhorn-Support

Please let me know if you have any more questions, Deemm

**Comment by deemm** [comment]
this is our staging environment, does that have anything to do with it ?

**Comment by stetsona** [comment]
Hello Deemm,

In your app.json your corp token is set to "corpToken":
"%25%27%22C%2EWPX%20%0A" this isn't correct.

Also, there are a few other issues with your app.json.

For instance you has a space after the swimlane:

"swimlane": "9 "


You may also want to change your corp name to :

"companyName": "Vernovis",

**Comment by deemm** [comment]
okay then i am working to get corp token again from bullhorn, till then here are the errors that i am getting, 
http://prntscr.com/cvdwod

Can you help me with these

Thanks

**Comment by bulbajackel** [comment]
Hey Deemm,

The errors that are being produced are due to the corp token and swimlane being incorrect since they are used to build the system queries.  Once they are updated, the errors will disappear.

**Comment by deemm** [comment]
i have updated the corp token but still the same issue

**Comment by pbearne** [comment]
As/If you need this in WordPress you might want to look at this plugin https://wordpress.org/plugins/bh-staffing-job-listing-and-cv-upload-for-wp/

**Comment by kbushkoBH** [comment]
The process for activating the career portal includes one final step in which you notify Bullhorn support that you have completed the upload process - and this allows them to complete the configuration necessary to connect the portal to the jobs in your system. I have completed this step for you at this time, however none of the Vernovis jobs have been designated for publishing. To designate jobs for publishing, mark them both "open" and "published." Our support team is trained to assist with the job publishing process.

The Bullhorn career portal can absolutely be hosted on a Wordpress site, but Bullhorn does not officially support any Wordpress plugins. Please use the utmost due diligence with your data whenever using a third party solution not fully vetted via the Bullhorn Marketplace.

**Comment by pbearne** [comment]
Hi kbushkoBH

I need to comment as feel your statement doesn't make it clear how the portal and WordPress play.

The portal can't hosted in a WordPress site( install ). It can hosted on the same server as a WordPress install but it this in not a integrated install and nothing is shared between the programs.

So let's fix this. How can I get the open source WordPress plugin vetted via the Bullhorn Marketplace? Love to see you supporting WordPress as more and more of your clients are using WordPress to run their sites.

Many thanks if you can help.

Sorry for the off topic reply

**Comment by kbushkoBH** [comment]
Hi Paul,

You can apply to become a partner [here](http://www.bullhorn.com/marketplace/partner-application/), but you are also welcome to take advantage of the open source nature of this project to build a version more compatible with the Wordpress program and its themes, if that is of interest to you.

My comment above is meant to clarify that Wordpress plugins are not necessary to complete setup of this portal and are not designed or endorsed by Bullhorn, even though they may offer a valid and desirable alternative career portal solution for a Bullhorn customer.

This project uses a limited access public REST connection that does not require the Bullhorn customer to request or share full access API credentials, and we always advise exercising caution when sharing API credentials with any third party.

**Comment by pbearne** [comment]
Thanks 

I have filled the form in and wait to hear back. I would love to extend this project but I am not sure how a node.js project would play with the PHP of WordPress :-(

The WordPress Plugin is using oAuth so doesn't store the full access API credentials

Thanks

**Comment by deemm** [comment]
Hi all, i have successfully pulled the jobs at my staging enviornment but i am unable to apply for any post as it gives the error
can you look into this please
http://dev.deliveredoncloud.com/vernovis/portal/#/jobs/1814

Thanks

**Comment by kbushkoBH** [comment]
Two candidates have been created in your system via the career portal apply process: 29353 and 29354, the latter of which was my successful test. If you attempted to apply with an email address that resides on a deleted candidate record this can cause an error as well - this is commonly reported on setup by internal users but rarely encountered by real applicants. 

Additionally the recommended method for publishing the jobs was not followed and they were sent to the portal without a published category or a date last published. [Our support team](http://bullhorn.force.com/pkb/articles/Documentation/Contacting-Bullhorn-Support) is happy to assist you with the publishing process.
