### ISSUE TITLE
Portal page loading blank

### ISSUE THREAD

**Issue by williampatey** [bullhorn/career-portal#98]
PORTAL PAGE LOADING BUT BLANK.

## Current behavior

I have followed the steps to upload the file directory via ftp having configured them with the corp token and swimlane provided to me by bullhorn but my portal is just showing blank.

See below:

http://huntconsultinggroup.co.uk/careerportal/

## Expected behavior

Have I missed some other file uploads as there doesn't seem to be any html etc in the original repository......

## Steps to replicate behavior

1.

## Screenshots

__Current__

__Expected__

**Comment by bulbajackel** [comment]
Hey William, I bet you are on a mac, I see a couple of weird formatting occurences going on with your app.json at http://huntconsultinggroup.co.uk/careerportal/app.json.  You want to make sure that you remove your corp token and Swimlane from the brackets and ensure there are no spaces between the quotation marks and the string of characters.  To get assistance with getting your app.json file set up, an authorized support contact can contact Bullhorn Support to get this resolved. 

To contact Bullhorn Support please follow the steps in this article http://bullhorn.force.com/pkb/articles/Documentation/Contacting-Bullhorn-Support

**Comment by williampatey** [comment]
Thanks Bulbajackel, I have made the corrections you have mentioned but am still getting a blank page. Any other ideas? Bullhorn have told me they won't offer any support as my clients platform is wordpress....

**Comment by williampatey** [comment]
I seem to be getting this error:

Error: JSON Parse error: Unterminated string parse@[native code] xt@http://huntconsultinggroup.co.uk/careerportal/scripts/vendor-8f007a856d.js:7:10899 http://huntconsultinggroup.co.uk/careerportal/scripts/vendor-8f007a856d.js:7:11368 o@http://huntconsultinggroup.co.uk/careerportal/scripts/vendor-8f007a856d.js:6:834 Et@http://huntconsultinggroup.co.uk/careerportal/scripts/vendor-8f007a856d.js:7:11350 a@http://huntconsultinggroup.co.uk/careerportal/scripts/vendor-8f007a856d.js:7:12078 u@http://huntconsultinggroup.co.uk/careerportal/scripts/vendor-8f007a856d.js:7:30996 http://huntconsultinggroup.co.uk/careerportal/scripts/vendor-8f007a856d.js:7:31168 $digest@http://huntconsultinggroup.co.uk/careerportal/scripts/vendor-8f007a856d.js:8:5052 $apply@http://huntconsultinggroup.co.uk/careerportal/scripts/vendor-8f007a856d.js:8:6829 o@http://huntconsultinggroup.co.uk/careerportal/scripts/vendor-8f007a856d.js:7:13973 v@http://huntconsultinggroup.co.uk/careerportal/scripts/vendor-8f007a856d.js:7:15816 onload@http://huntconsultinggroup.co.uk/careerportal/scripts/vendor-8f007a856d.js:7:16359

**Comment by krsween** [comment]
Hey, @williampatey—

I just looked at your app's [configuration file (app.json)](http://huntconsultinggroup.co.uk/careerportal/app.json) and I still see that there are some errors. Try overwriting your app.json with this (exactly):

```
{
    "acceptedResumeTypes": [
        "html",
        "text",
        "txt",
        "pdf",
        "doc",
        "docx",
        "rtf",
        "odt"
    ],
    "companyName": "Hunt Consulting Group",
    "defaultLocale": "en-US",
    "supportedLocales": [
        "en-US",
        "fr-FR"
    ],
    "minUploadSize": 4096,
    "maxRelatedJobs": 5,
    "maxUploadSize": 5242880,
    "service": {
        "batchSize": 500,
        "corpToken": "2FDUY1",
        "port": null,
        "swimlane": 23
    },
    "integrations": {
        "linkedin": {
            "clientId": "[ CLIENTID HERE ]"
        }
    },
    "defaultGridState": "list-view"
}
```

The issue doesn't look like it's with Wordpress. I think it lies with this config file. More information about this configuration file can be found [here.](https://github.com/bullhorn/career-portal/wiki/Downloading-and-Configuring)

Thanks!
K.

**Comment by williampatey** [comment]
Thanks K, really appreciate your help. 

have mode those changes but still seem to be getting getting the same issue.

Whats buggin men is that when I access www.huntconsultinggroup.co.uk/careerportal/app.json it's not showing the changes but when I access app.json via either filezilla or ssh it's showing the changes. 

Can you let me know if you can see the changes?

Again I can't thank you enough for your help.

**Comment by krsween** [comment]
They haven't updated yet on my end. May want to double-check that your changes are getting uploaded remotely and not locally.

**Comment by williampatey** [comment]
As you can see I have changed my app.json to app.jsonbroken but its still loading in my browser......?
![screen shot 2016-10-25 at 21 07 38](https://cloud.githubusercontent.com/assets/23039209/19702396/57e483e8-9af7-11e6-9464-02372c716fa9.png)

**Comment by williampatey** [comment]
deleted and re-uploaded and voila!

Thank you all for your help. Brilliant

**Comment by krsween** [comment]
Great to hear it! Best of luck @williampatey.
